const data = [
    {
        hours: 9,
        pins: 98,
        timestamp: '2021-09-20',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 9,
        pins: 98,
        timestamp: '2021-09-21',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 9,
        pins: 98,
        timestamp: '2021-09-22',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 9,
        pins: 98,
        timestamp: '2021-09-23',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 9,
        pins: 98,
        timestamp: '2021-09-24',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 9,
        pins: 98,
        timestamp: '2021-09-25',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 9,
        pins: 98,
        timestamp: '2021-09-26',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },

    {
        hours: 9,
        pins: 98,
        timestamp: '2021-09-27',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 6,
        pins: 87,
        timestamp: '2021-09-28',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 9,
        pins: 76,
        timestamp: '2021-09-29',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 12,
        pins: 56,
        timestamp: '2021-09-30',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 15,
        pins: 34,
        timestamp: '2021-09-01',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 10,
        pins: 34,
        timestamp: '2021-10-02',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 4,
        pins: 101,
        timestamp: '2021-10-03',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },

    {
        hours: 9,
        pins: 98,
        timestamp: '2021-10-04',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 6,
        pins: 87,
        timestamp: '2021-10-05',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 9,
        pins: 76,
        timestamp: '2021-10-06',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 12,
        pins: 56,
        timestamp: '2021-10-07',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 15,
        pins: 34,
        timestamp: '2021-10-08',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 10,
        pins: 34,
        timestamp: '2021-10-09',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
    {
        hours: 4,
        pins: 101,
        timestamp: '2021-10-10',
        reference: 'Lorem ipsum.',
        description: 'Lorem ipsum dolor sit.',
    },
];
export default data;
