import { combineReducers } from 'redux';
import {
    CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_REQUEST,
    CLIENT_FETCH_DRAWING_TEMPLATES_REQUEST,
    CLIENT_FETCH_ALL_DRAWINGS_REQUEST,
    CLIENT_FETCH_SINGLE_DRAWING_REQUEST,
    CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_FAILURE,
    CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_SUCCESS,
    CLIENT_FETCH_DRAWING_TEMPLATES_FAILURE,
    CLIENT_FETCH_DRAWING_TEMPLATES_SUCCESS,
    CLIENT_FETCH_ALL_DRAWINGS_SUCCESS,
    CLIENT_FETCH_ALL_DRAWINGS_FAILURE,
    CLIENT_FETCH_SINGLE_DRAWING_FAILURE,
    CLIENT_FETCH_SINGLE_DRAWING_SUCCESS
} from 'constants/client/actionTypes/clientDrawings';

export default combineReducers({});

function isFetchingReducer(state = false, action) {
    switch (action.type) {
        case CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_REQUEST:
        case CLIENT_FETCH_DRAWING_TEMPLATES_REQUEST:
        case CLIENT_FETCH_ALL_DRAWINGS_REQUEST:
        case CLIENT_FETCH_SINGLE_DRAWING_REQUEST:
            return true;
        case CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_FAILURE:
        case CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_SUCCESS:
        case CLIENT_FETCH_DRAWING_TEMPLATES_FAILURE:
        case CLIENT_FETCH_DRAWING_TEMPLATES_SUCCESS:
        case CLIENT_FETCH_ALL_DRAWINGS_SUCCESS:
        case CLIENT_FETCH_ALL_DRAWINGS_FAILURE:
        case CLIENT_FETCH_SINGLE_DRAWING_FAILURE:
        case CLIENT_FETCH_SINGLE_DRAWING_SUCCESS:
            return false;
        default:
            return state;
    }
}
