import React from 'react';

import UserSyncDataTable from '../presentational/UserSyncDataTable';

const UserSyncDataTableContainer = () => {
    const headers = [
        'Sync ID',
        'Start Date',
        'Completion Date',
        'Errored?',
        'Device Type',
        'App Version',
        '# Pins Synced',
        '# Pin Histories Synced',
    ];
    const syncData = [
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
        {
            syncID: 'Some data',
            startDate: 'Some data',
            completionDate: 'Some data',
            errored: 'Some data',
            deviceType: 'Some data',
            appVersion: 'Some data',
            numOfPinsSynced: 'Some data',
            numOfPinHistory: 'Some data',
        },
    ];

    return <UserSyncDataTable headers={headers} syncData={syncData} />;
};

export default UserSyncDataTableContainer;
