//drawing
export const EDIT_FLOOR_PLAN = 'EDIT_FLOOR_PLAN';

//generic
export const SUCCESS_MODAL = 'SUCCESS_MODAL';
export const CONFIRM_DELETE = 'CONFIRM_DELETE_MODAL';
export const CONFIRM_ARCHIVE = 'CONFIRM_ARCHIVE_MODAL';
export const CONFIRM_SUBMIT = 'CONFIRM_SUBMIT_MODAL';

// company
export const PIN_IMAGE = 'PIN_IMAGE';

//ADMIN
//template builder
export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const EDIT_TEMPLATE = 'EDIT_TEMPLATE';

export const RENAME_TEMPLATE_SECTION = 'RENAME_TEMPLATE_SECTION';
export const ADD_TEMPLATE_SECTION = 'ADD_TEMPLATE_SECTION';

export const ADD_TEMPLATE_QUESTION = 'ADD_TEMPLATE_QUESTION';
export const EDIT_TEMPLATE_QUESTION = 'EDIT_TEMPLATE_QUESTION';

export const ADMIN_EDIT_SERVICE = 'ADMIN_EDIT_SERVICE';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_PASSWORD = 'EDIT_USER_PASSWORD';

export const DELETE_COMPANY_PERMISSIONS = 'DELETE_COMPANY_PERMISSIONS';
export const DELETE_COMPANY_USER = 'DELETE COMPANY_USER';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DELETE_ENQUIRY = 'DELETE_ENQUIRY';
export const DELETE_OPERATIVE = 'DELETE OPERATIVE';

export const DELETE_CLIENT_FROM_DRAWING = 'DELETE_CLIENT_FROM_DRAWING';

export const ERROR_MODAL = 'ERROR_MODAL';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';

export const ADD_CARD = 'ADD_CARD';
export const ADD_SERVICE_TO_SUBSCRIPTION = 'ADD_SERVICE_TO_SUBSCRIPTION';
export const BUY_CREDITS = 'BUY_CREDITS';
export const PAY_INVOICE = 'PAY_INVOICE';

export const COMPANY_EDIT_TEMPLATE_QUESTION = 'COMPANY_EDIT_TEMPLATE_QUESTION';

export const CONFIRM_EDIT_PIN = 'CONFIRM_EDIT_PIN';
