//drawing
export const EDIT_DRAWING = 'EDIT_DRAWING';
export const VIEW_ZONES = 'VIEW_ZONES';
export const ADD_DRAWING_ZONE = 'ADD_DRAWING_ZONE';
export const ZONE_DETAILS = 'ZONE_DETAILS';

//generic
export const SUCCESS_MODAL = 'SUCCESS_MODAL';
export const CONFIRM_DELETE = 'CONFIRM_DELETE_MODAL';
export const CONFIRM_ARCHIVE = 'CONFIRM_ARCHIVE_MODAL';
export const CONFIRM_SUBMIT = 'CONFIRM_SUBMIT_MODAL';
export const CONFIRM_DARK_THEME = 'CONFIRM_DARK_THEME_MODAL';

// company
export const PIN_IMAGE = 'PIN_IMAGE';

export const FILTER_FIELDS = 'FILTER_FIELDS';
export const CLIENT_FILTER_FIELDS = 'CLIENT_FILTER_FIELDS';

export const DOCUMENT_RESPONSE_AGREEANCE = 'DOCUMENT_RESPONSE_AGREEANCE';

export const GENERATE_QR_CODES = 'GENERATE_QR_CODES';

//pins
export const SINGLE_PIN_GENERATE_REPORT_SUCCESS = 'SINGLE_PIN_GENERATE_REPORT_SUCCESS';

export const CLIENT_SINGLE_PIN_GENERATE_REPORT_SUCCESS =
    'CLIENT_SINGLE_PIN_GENERATE_REPORT_SUCCESS';

export const SERIES_PIN_TASK_MODAL = 'SERIES_PIN_TASK_MODAL';

//ADMIN
//template builder
export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const EDIT_TEMPLATE = 'EDIT_TEMPLATE';

export const SET_TEMPLATE_IMAGE = 'SET_TEMPLATE_IMAGE';
export const SET_LABEL_FIELDS = 'SET_LABEL_FIELDS';
export const COPY_TEMPLATE = 'COPY_TEMPLATE';

export const RENAME_TEMPLATE_SECTION = 'RENAME_TEMPLATE_SECTION';
export const ADD_TEMPLATE_SECTION = 'ADD_TEMPLATE_SECTION';

export const ADD_TEMPLATE_QUESTION = 'ADD_TEMPLATE_QUESTION';
export const EDIT_TEMPLATE_QUESTION = 'EDIT_TEMPLATE_QUESTION';

export const ADMIN_EDIT_SERVICE = 'ADMIN_EDIT_SERVICE';
export const UPDATE_REPORT_LAYOUT = 'UPDATE_REPORT_LAYOUT';

//ADMIN INVOICES
export const ADMIN_CONFIRM_FREE_INVOICE = 'ADMIN_CONFIRM_FREE_INVOICE';
export const ADMIN_CONFIRM_SET_IS_INVOICE_PAID = 'ADMIN_CONFIRM_SET_IS_INVOICE_PAID';
export const ADMIN_RECORD_PAYMENT = 'ADMIN_CONFIRM_PAYMENT';
export const ADMIN_EDIT_PAYMENT = 'ADMIN_EDIT_PAYMENT';
export const ADMIN_DELETE_PAYMENT = 'ADMIN_DELETE_PAYMENT';
export const ADMIN_DELETE_INVOICE = 'ADMIN_DELETE_INVOICE';
export const ADMIN_RESTORE_INVOICE = 'ADMIN_RESTORE_INVOICE';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_PASSWORD = 'EDIT_USER_PASSWORD';
export const EDIT_USER_EMAIL = 'EDIT_USER_EMAIL';

export const DELETE_COMPANY_PERMISSIONS = 'DELETE_COMPANY_PERMISSIONS';
export const DELETE_COMPANY_USER = 'DELETE COMPANY_USER';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DELETE_ENQUIRY = 'DELETE_ENQUIRY';
export const DELETE_OPERATIVE = 'DELETE OPERATIVE';

export const DELETE_CLIENT_FROM_DRAWING = 'DELETE_CLIENT_FROM_DRAWING';

export const ERROR_MODAL = 'ERROR_MODAL';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';

export const ADD_CARD = 'ADD_CARD';
export const ADD_SERVICE_TO_SUBSCRIPTION = 'ADD_SERVICE_TO_SUBSCRIPTION';
export const BUY_CREDITS = 'BUY_CREDITS';
export const PAY_INVOICE = 'PAY_INVOICE';
export const ADD_CREDITS_TO_DRAWING = 'ADD_CREDITS_TO_DRAWING';
export const ADD_MULTIPLE_SERVICES_TO_SUBSCRIPTION = 'ADD_SERVICE_TO_SUBSCRIPTION';

export const COMPANY_EDIT_TEMPLATE_QUESTION = 'COMPANY_EDIT_TEMPLATE_QUESTION';

export const CONFIRM_EDIT_PIN = 'CONFIRM_EDIT_PIN';

export const ADD_SITE = 'ADD_SITE';
export const ADD_BUILDING = 'ADD_BUILDING';
export const ADD_BUILDINGS = 'ADD_BUILDINGS';
export const ADD_FLOOR = 'ADD_FLOOR';
export const ADD_FLOORS = 'ADD_FLOORS';
export const ADD_DRAWING = 'ADD_DRAWING';
export const ADD_DRAWINGS = 'ADD_DRAWINGS';

export const EDIT_SITE = 'EDIT_SITE';
export const EDIT_BUILDING = 'EDIT_BUILDING';
export const EDIT_FLOOR = 'EDIT_FLOOR';

export const CREATE_COMPANY_ADMIN = 'CREATE_COMPANY_ADMIN';
export const EDIT_COMPANY_ADMIN = 'EDIT_COMPANY_ADMIN';
export const COMPANY_ADMIN_CHANGE_PASSWORD = 'COMPANY_ADMIN_CHANGE_PASSWORD';

export const CREATE_OPERATIVE = 'CREATE_OPERATIVE';
export const EDIT_OPERATIVE = 'EDIT_OPERATIVE';
export const OPERATIVE_CHANGE_PASSWORD = 'OPERATIVE_CHANGE_PASSWORD';

export const LOADING_DATA = 'LOADING_DATA';

export const UNLINK_DEVICE = 'UNLINK_DEVICE';
export const REVOKE_ADMIN_ACCESS = 'REVOKE_ADMIN_ACCESS';
export const RESTRICT_ADMIN_PAYMENTS = 'RESTRICT_ADMIN_PAYMENTS';

export const SELECT_PIN_SCALE = 'SELECT_PIN_SCALE';

export const REMOVE_DRAWINGS_ACCESS = 'REMOVE_DRAWINGS_ACCESS';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const DELETE_DEMO_REQUEST = 'DELETE_DEMO_REQUEST';
export const ADD_DEMO_REQUEST_COMMENT = 'ADD_DEMO_REQUEST_COMMENT';

export const ADD_INVOICE_COMMENT = 'ADD_INVOICE_COMMENT';

//site management (super admin)
export const CONFIRM_MOVE_HIERARCHY_TO_COMPANY = 'CONFIRM_MOVE_HIERARCHY_TO_COMPANY';

export const DELETE_INVOICE = 'DELETE_INVOICE';

export const REQUEST_DELETE_INVOICE = 'REQUEST_DELETE_INVOICE';

export const ADMIN_CREATE_COMPANY_ADMIN = 'ADMIN_CREATE_COMPANY_ADMIN';
export const ADMIN_EDIT_COMPANY_OWNER = 'ADMIN_EDIT_COMPANY_OWNER';

//
export const ADMIN_LATEST_SYNCS = 'ADMIN_LATEST_SYNCS';
export const DOCUMENT_VIEW = 'DOCUMENT_VIEW';

// company admin manufacturers

export const ADMIN_EDIT_COMPANY_ADDRESS = 'ADMIN_EDIT_COMPANY_ADDRESS';
export const EDIT_FREE_CREDIT = 'EDIT_FREE_CREDIT';
export const EDIT_JOB_REF_DROPDOWN = 'EDIT_JOB_REF_DROPDOWN';

export const UPLOAD_USER_GUIDE = 'UPLOAD_USER_GUIDE';

// company admin user management
export const RECOVER_USER = 'RECOVER_USER';
export const REACTIVATE_USER = 'REACTIVATE_USER';
export const DISABLE_USER = 'DISABLE_USER';
export const ENABLE_USER = 'ENABLE_USER';
export const RESEND_INVITE = 'RESEND_INVITE';

//super admin new features
export const ADD_NEW_FEATURE = 'ADD_NEW_FEATURE';
export const EDIT_NEW_FEATURE = 'EDIT_NEW_FEATURE';

// super admin access codes
export const ADD_DEMO_ACCESS_CODES = 'ADD_DEMO_ACCESS_CODES';
export const EDIT_DEMO_ACCESS_CODES = 'EDIT_DEMO_ACCESS_CODES';
export const DISABLE_DEMO_ACCESS_CODES = 'DISABLE_DEMO_ACCESS_CODES';
export const DELETE_DEMO_ACCESS_CODES = 'DELETE_DEMO_ACCESS_CODES';
export const ENTER_DEMO_ACCESS_CODES = 'ENTER_DEMO_ACCESS_CODES';

// recent updates
export const RECENT_UPDATE_MODAL = 'RECENT_UPDATE_MODAL';

export const EDIT_ZONE_MODAL = 'EDIT_ZONE_MODAL';

export const ADD_NEW_BANNER_NOTIFICATION = 'ADD_NEW_BANNER_NOTIFICATION';
export const EDIT_BANNER_NOTIFICATION = 'EDIT_BANNER_NOTIFICATION';

export const DELETE_CONTACT_SUBMISSION = 'DELETE_CONTACT_SUBMISSION';
export const ADD_CONTACT_SUBMISSION_COMMENT = 'ADD_CONTACT_SUBMISSION_COMMENT';
// Front end
export const WHY_USE_OUR_SYSTEM = 'WHY_USE_OUR_SYSTEM';

export const CONFIRM_TWO_FACTOR = 'CONFIRM_TWO_FACTOR';

export const CONFIRM_EMAIL = 'CONFIRM_EMAIL';

export const USER_NEW_DOCUMENT = 'USER_NEW_DOCUMENT';
// pin tasks
export const FETCH_PIN_TASK = 'FETCH_PIN_TASK';
export const CREATE_PIN_TASK = 'CREATE_PIN_TASK';
export const EDIT_PIN_TASK = 'EDIT_PIN_TASK';
export const EDIT_PIN_TASK_SERIES = 'EDIT_PIN_TASK_SERIES';

//timesheets
export const GENERATE_TIMESHEET_REPORT = 'GENERATE_TIMESHEET_REPORT';

//Alerts
export const CREATE_HIERARCHY_ALERT_MODAL = 'CREATE_HIERARCHY_ALERT_MODAL';
export const EDIT_ALERT_MODAL = 'EDIT_ALERT_MODAL';
export const DELETE_ALERT_MODAL = 'DELETE_ALERT_MODAL';
export const MESSAGE_CENTRE_DRAWING_EXPIRY = 'MESSAGE_CENTRE_DRAWING_EXPIRY';

export const EXPANDED_MEDIA = 'EXPANDED_MEDIA';
export const UNCONFIRMED_EMAIL_MODAL = 'UNCONFIRMED_EMAIL_MODAL';

// Document Library
export const UPLOAD_LIBRARY_DOCUMENT = 'UPLOAD_LIBRARY_DOCUMENT';
export const SOFT_DELETE_LIBRARY_DOCUMENT = 'SOFT_DELETE_LIBRARY_DOCUMENT';
export const HARD_DELETE_LIBRARY_DOCUMENT = 'HARD_DELETE_LIBRARY_DOCUMENT';
export const RESTORE_LIBRARY_DOCUMENTS = 'RESTORE_LIBRARY_DOCUMENT';
export const CREATE_LIBRARY_FOLDER = 'CREATE_LIBRARY_FOLDER';
export const EDIT_LIBRARY_ITEMS = 'EDIT_LIBRARY_ITEMS';
export const SELECT_DOCUMENT_LIBRARY_ITEM = 'SELECT_DOCUMENT_LIBRARY_ITEM';

export const CREATE_NEW_OPERATIVE_ALERTS_MODAL = 'CREATE_NEW_OPERATIVE_ALERTS_MODAL';

// job references
export const CREATE_JOB_REFERENCE = 'CREATE_JOB_REFERENCE';
export const EDIT_JOB_REFERENCE = 'EDIT_JOB_REFERENCE';
export const DELETE_JOB_REFERENCE = 'DELETE_JOB_REFERENCE';

export const DRAWING_EXPIRY_MODAL = 'DRAWING_EXPIRY_MODAL';

// pin options
export const CREATE_PIN_OPTIONS_SET_MODAL = 'CREATE_PIN_OPTIONS_SET_MODAL';
export const CREATE_PIN_OPTIONS_VALUE_MODAL = 'CREATE_PIN_OPTIONS_VALUE_MODAL';
export const CREATE_PRELIM_MODAL = 'CREATE_PRELIM_MODAL';
export const CREATE_PIN_OPTION_DOCUMENTS_MODAL = 'CREATE_PIN_OPTION_DOCUMENTS_MODAL';

export const EDIT_PIN_OPTIONS_SET_MODAL = 'EDIT_PIN_OPTIONS_SET_MODAL';
export const EDIT_PIN_OPTIONS_VALUE_MODAL = 'EDIT_PIN_OPTIONS_VALUE_MODAL';
export const EDIT_PRELIM_MODAL = 'EDIT_PRELIM_MODAL';
export const EDIT_PIN_OPTION_DOCUMENTS_MODAL = 'EDIT_PIN_OPTION_DOCUMENTS_MODAL';

export const DELETE_PIN_OPTION_DOCUMENTS_MODAL = 'DELETE_PIN_OPTION_DOCUMENTS_MODAL';

export const CREATE_ADMIN_PIN_OPTIONS_SET_MODAL = 'CREATE_ADMIN_PIN_OPTIONS_SET_MODAL';
export const EDIT_ADMIN_PIN_OPTIONS_SET_MODAL = 'EDIT_ADMIN_PIN_OPTIONS_SET_MODAL';

export const CREATE_ADMIN_PIN_OPTIONS_VALUE_MODAL = 'CREATE_ADMIN_PIN_OPTIONS_VALUE_MODAL';
