const numberNames = {
    basement: -1,
    b: -1,
    zero: 0,
    one: 1,
    first: 1,
    two: 2,
    second: 2,
    three: 3,
    third: 3,
    four: 4,
    five: 5,
    fifth: 5,
    six: 6,
    seven: 7,
    eight: 8,
    nine: 9,
    ninth: 9,
    ten: 10,
    eleven: 11,
    twelve: 12,
    twelvth: 12,
    thirteen: 13,
    fourteen: 14,
    fifteen: 15,
    sixteen: 16,
    seventeen: 17,
    eighteen: 18,
    nineteen: 19,
    twenty: 20,
    twentieth: 20,
    thirty: 30,
    thirtieth: 30,
    fourty: 40,
    fourtieth: 40,
    fifty: 50,
    fiftieth: 50,
    sixty: 60,
    sixtieth: 60,
    seventy: 70,
    seventieth: 70,
    eighty: 80,
    eightieth: 80,
    ninety: 90,
    ninetieth: 90,
    'one hundred': 100,
    'two hundred': 200,
    'three hundred': 300,
    'four hundred': 400,
};

const numeralNames = {
    [numberNames.zero]: 0,
    [numberNames.one]: 1,
    [numberNames.two]: 2,
    [numberNames.three]: 3,
    [numberNames.four]: 4,
    [numberNames.five]: 5,
    [numberNames.six]: 6,
    [numberNames.seven]: 7,
    [numberNames.eight]: 8,
    [numberNames.nine]: 9,
    [numberNames.ten]: 10,
    [numberNames.eleven]: 11,
    [numberNames.twelve]: 12,
    [numberNames.thirteen]: 13,
    [numberNames.fourteen]: 14,
    [numberNames.fifteen]: 15,
    [numberNames.sixteen]: 16,
    [numberNames.seventeen]: 17,
    [numberNames.eighteen]: 18,
    [numberNames.nineteen]: 19,
    [numberNames.twenty]: 20,
    [numberNames.thirty]: 30,
    [numberNames.fourty]: 40,
    [numberNames.fifty]: 50,
    [numberNames.sixty]: 60,
    [numberNames.seventy]: 70,
    [numberNames.eighty]: 80,
    [numberNames.ninety]: 90,
    [numberNames['one hundred']]: 100,
    [numberNames['two hundred']]: 200,
    [numberNames['three hundred']]: 300,
    [numberNames['four hundred']]: 400,
    [numberNames.basement]: -1,
    [numberNames.b]: -1,
};

export default { ...numberNames, ...numeralNames };
