export const PIN_IMAGE = 'PIN_IMAGE';

//ADMIN
//template builder
export const ADD_TEMPLATE_SECTION = 'ADD_TEMPLATE_SECTION';
export const ADD_TEMPLATE_QUESTION = 'ADD_TEMPLATE_QUESTION';

export const RENAME_TEMPLATE_SECTION = 'RENAME_TEMPLATE_SECTION';

export const EDIT_SERVICE = 'EDIT_SERVICE';

export const EDIT_USER_PASSWORD = 'EDIT_USER_PASSWORD';
export const EDIT_USER = 'EDIT_USER';

export const DELETE_ITEM = 'DELETE_ITEM';
