export const companyNavMenuItems = [
    {
        name: 'Dashboard',
        icon: '',
        link: '/company',
        subscriptionRestriction: true,
        paymentRestriction: false,
        userSelectRestriction: true,
    },
    {
        name: 'Sites',
        icon: '',
        link: null,
        subscriptionRestriction: true,
        paymentRestriction: false,
        userSelectRestriction: true,
        subNavItems: [
            {
                name: 'Sites',
                link: '/company/sites',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Requests & Invites',
                link: '/company/tools/transfer-requests',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Invited Access',
                link: '/client/companies',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
        ],
    },
    {
        name: 'Users',
        icon: '',
        link: null,
        subscriptionRestriction: true,
        paymentRestriction: false,
        userSelectRestriction: true,
        subNavItems: [
            {
                name: 'Admins',
                link: '/company/users-management/company-admins',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Operatives',
                link: '/company/users-management/operatives',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Clients',
                link: '/company/users-management/clients',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Timesheets',
                link: '/company/users-management/timesheets',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Pin Tasks',
                link: '/company/users-management/pin-tasks',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
        ],
    },
    {
        name: 'Orders',
        icon: '',
        link: null,
        subscriptionRestriction: false,
        paymentRestriction: true,
        userSelectRestriction: true,
        subNavItems: [
            {
                name: 'Orders',
                link: '/company/invoices',
                subscriptionRestriction: false,
                paymentRestriction: true,
                userSelectRestriction: true,
            },
            {
                name: 'Subscriptions & Credits',
                link: '/company/subscription',
                subscriptionRestriction: false,
                paymentRestriction: true,
                userSelectRestriction: true,
            },
        ],
    },
    {
        name: 'Reports',
        icon: '',
        link: null,
        subscriptionRestriction: true,
        paymentRestriction: false,
        userSelectRestriction: true,
        subNavItems: [
            {
                name: 'My Company Reports',
                link: '/company/reports',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Create Report',
                link: '/company/create-report',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
        ],
    },
    {
        name: 'Settings',
        icon: '',
        link: null,
        subscriptionRestriction: false,
        paymentRestriction: false,
        userSelectRestriction: false,
        subNavItems: [
            {
                name: 'My Profile',
                link: '/company/profile',
                subscriptionRestriction: false,
                paymentRestriction: false,
                userSelectRestriction: false,
            },
            {
                name: 'Company Settings',
                link: '/company/settings',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'My Templates',
                link: '/company/templates',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Job References',
                link: '/company/job-references',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
        ],
    },
    {
        name: 'Tools',
        icon: '',
        link: null,
        subscriptionRestriction: false,
        paymentRestriction: false,
        userSelectRestriction: true,
        subNavItems: [
            {
                name: 'Release Notes',
                link: '/company/release-notes',
                subscriptionRestriction: false,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Activity Log',
                link: '/company/activity-log',
                subscriptionRestriction: false,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Generate QR Codes',
                link: '/company/generate-qr-codes',
                subscriptionRestriction: false,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Company Documents',
                link: '/company/company-documents',
                subscriptionRestriction: false,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Bug Report',
                link: '/company/bug-report',
                subscriptionRestriction: false,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Bolster Approved Companies',
                link: '/company/approved-companies',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Message Centre',
                link: '/company/message-centre',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
        ],
    },
    {
        name: 'Support',
        icon: '',
        link: null,
        subscriptionRestriction: false,
        paymentRestriction: false,
        userSelectRestriction: false,
        subNavItems: [
            {
                name: 'User Guides',
                link: '/company/user-guides',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Terms & Conditions',
                link: '/auth/terms',
                subscriptionRestriction: true,
                paymentRestriction: false,
                userSelectRestriction: true,
            },
            {
                name: 'Select Company',
                link: '/company/company-selection',
                subscriptionRestriction: false,
                paymentRestriction: false,
                userSelectRestriction: false,
            },
        ],
    },
];
