import React from 'react';
import { connect } from 'react-redux';
import CompanyReportsTable from '../presentational/CompanyReportsTable';
import { sortArrayByKeyAndOrder } from 'helpers/generic';
import retryReport from 'actions/superAdmin/companyReports/async/retryReport';
import fetchCompanyReportsQueue from 'actions/superAdmin/companyReports/async/fetchCompanyReportsQueue';
import fetchCompanyReportsQueueFull from 'actions/superAdmin/companyReports/async/fetchCompanyReportsQueueFull';
import showModal from 'actions/shared/generic/modals/sync/showModal';
import { CONFIRM_DELETE, ERROR_MODAL } from 'constants/shared/modalTypes';
import deleteReport from 'actions/superAdmin/companyReports/async/deleteReport';
import hideModal from 'actions/shared/generic/modals/sync/hideModal';

const CompanyReportsTableContainer = ({
    companyReports,
    error,
    isFetching,
    sortString,
    onMobile,
    retryReport,
    fetchCompanyReportsQueue,
    fetchCompanyReportsQueueFull,
    fetchStatus,
    showModal,
    deleteReport,
    hideModal,
}) => {
    return (
        <CompanyReportsTable
            companyReports={_getSortedQueue()}
            error={error}
            isFetching={isFetching}
            headers={[
                'Company',
                'Report Name',
                'Type',
                'Generated By',
                'User Email',
                'Status',
                'Created On',
                'Completed on',
                '',
            ]}
            onMobile={onMobile}
            retryCompanyReport={id => retryCompanyReport(id)}
            fetchStatus={fetchStatus}
            fetchCompanyReportsQueueFull={fetchCompanyReportsQueueFull}
            showDeleteModal={showDeleteModal}
        />
    );
    function _getSortedQueue() {
        const fieldAndSort = sortString.split(' ');

        const fieldName = fieldAndSort[0];
        const sortOrder = fieldAndSort[1];
        if (sortOrder === 'asc') {
            return sortArrayByKeyAndOrder(companyReports, fieldName, true);
        } else {
            return sortArrayByKeyAndOrder(companyReports, fieldName, false);
        }
    }
    function retryCompanyReport(id) {
        retryReport(id).then(fetchCompanyReportsQueue);
    }

    function showDeleteModal(id) {
        showModal(CONFIRM_DELETE, { handleDelete: () => handleDelete(id) });
    }

    async function handleDelete(id) {
        const { success } = await deleteReport(id);
        if (success) {
            hideModal();
        } else {
            showModal(ERROR_MODAL);
        }
    }
};
const mapStateToProps = ({
    superAdmin: {
        companyReportsReducer: {
            companyReports,
            error,
            isFetching,
            sort: { sortString },
            fetchStatus,
        },
    },
    shared: {
        mobileReducer: { onMobile },
    },
}) => ({
    companyReports: Object.values(companyReports),
    error,
    isFetching,
    sortString,
    onMobile,
    fetchStatus,
});
const mapDispatchToProps = {
    fetchCompanyReportsQueue,
    fetchCompanyReportsQueueFull,
    retryReport,
    showModal,
    deleteReport,
    hideModal,
};

export default connect(mapStateToProps, mapDispatchToProps)(CompanyReportsTableContainer);
