export const CLIENT_FETCH_PINS_REQUEST = 'CLIENT_FETCH_PINS_REQUEST';
export const CLIENT_FETCH_PINS_SUCCESS = 'CLIENT_FETCH_PINS_SUCCESS';
export const CLIENT_FETCH_PINS_FAILURE = 'CLIENT_FETCH_PINS_FAILURE';

export const CLIENT_SELECT_PIN_HISTORY = 'CLIENT_SELECT_PIN_HISTORY';

export const CLIENT_FETCH_SINGLE_PIN_REQUEST =
    'CLIENT_FETCH_SINGLE_PIN_REQUEST';
export const CLIENT_FETCH_SINGLE_PIN_SUCCESS =
    'CLIENT_FETCH_SINGLE_PIN_SUCCESS';
export const CLIENT_FETCH_SINGLE_PIN_FAILURE =
    'CLIENT_FETCH_SINGLE_PIN_FAILURE';

export const CLIENT_FETCH_PIN_TEMPLATES_REQUEST =
    'CLIENT_FETCH_PIN_TEMPLATES_REQUEST';
export const CLIENT_FETCH_PIN_TEMPLATES_SUCCESS =
    'CLIENT_FETCH_PIN_TEMPLATES_SUCCESS';
export const CLIENT_FETCH_PIN_TEMPLATES_FAILURE =
    'CLIENT_FETCH_PIN_TEMPLATES_FAILURE';

export const CLIENT_FETCH_PIN_FEED_REQUEST = 'CLIENT_FETCH_PIN_FEED_REQUEST';
export const CLIENT_FETCH_PIN_FEED_SUCCESS = 'CLIENT_FETCH_PIN_FEED_SUCCESS';
export const CLIENT_FETCH_PIN_FEED_FAILURE = 'CLIENT_FETCH_PIN_FEED_FAILURE';

export const CLIENT_FETCH_PIN_STATS_REQUEST = 'CLIENT_FETCH_PIN_STATS_REQUEST';
export const CLIENT_FETCH_PIN_STATS_SUCCESS = 'CLIENT_FETCH_PIN_STATS_SUCCESS';
export const CLIENT_FETCH_PIN_STATS_FAILURE = 'CLIENT_FETCH_PIN_STATS_FAILURE';
