export const CLIENT_FETCH_PIN_STATS_REQUEST = 'CLIENT_FETCH_PIN_STATS_REQUEST';
export const CLIENT_FETCH_PIN_STATS_SUCCESS = 'CLIENT_FETCH_PIN_STATS_SUCCESS';
export const CLIENT_FETCH_PIN_STATS_FAILURE = 'CLIENT_FETCH_PIN_STATS_FAILURE';
