export const CLIENT_FETCH_ALL_TEMPLATES_REQUEST =
    'CLIENT_FETCH_ALL_TEMPLATES_REQUEST';
export const CLIENT_FETCH_ALL_TEMPLATES_SUCCESS =
    'CLIENT_FETCH_ALL_TEMPLATES_SUCCESS';
export const CLIENT_FETCH_ALL_TEMPLATES_FAILURE =
    'CLIENT_FETCH_ALL_TEMPLATES_FAILURE';

    export const CLIENT_FETCH_TEMPLATES_FOR_DRAWING_REQUEST =
    'CLIENT_FETCH_TEMPLATES_FOR_DRAWING_REQUEST';
export const CLIENT_FETCH_TEMPLATES_FOR_DRAWING_SUCCESS =
    'CLIENT_FETCH_TEMPLATES_FOR_DRAWING_SUCCESS';
export const CLIENT_FETCH_TEMPLATES_FOR_DRAWING_FAILURE =
    'CLIENT_FETCH_TEMPLATES_FOR_DRAWING_FAILURE';

