export const CLIENT_FETCH_COMPANIES_REQUEST = 'CLIENT_FETCH_COMPANIES_REQUEST';
export const CLIENT_FETCH_COMPANIES_SUCCESS = 'CLIENT_FETCH_COMPANIES_SUCCESS';
export const CLIENT_FETCH_COMPANIES_FAILURE = 'CLIENT_FETCH_COMPANIES_FAILURE';

export const CLIENT_SELECT_COMPANY = 'CLIENT_SELECT_COMPANY';
