export const CLIENT_FETCH_ALL_DRAWINGS_REQUEST =
    'CLIENT_FETCH_ALL_DRAWINGS_REQUEST';
export const CLIENT_FETCH_ALL_DRAWINGS_SUCCESS =
    'CLIENT_FETCH_ALL_DRAWINGS_SUCCESS';
export const CLIENT_FETCH_ALL_DRAWINGS_FAILURE =
    'CLIENT_FETCH_ALL_DRAWINGS_FAILURE';

export const CLIENT_FETCH_SINGLE_DRAWING_REQUEST =
    'CLIENT_FETCH_SINGLE_DRAWING_REQUEST';
export const CLIENT_FETCH_SINGLE_DRAWING_SUCCESS =
    'CLIENT_FETCH_SINGLE_DRAWING_SUCCESS';
export const CLIENT_FETCH_SINGLE_DRAWING_FAILURE =
    'CLIENT_FETCH_SINGLE_DRAWING_FAILURE';

//  ? do we need this?
// export const CLIENT_FETCH_DRAWING_INSPECTION_LOGS_REQUEST =
//     'CLIENT_FETCH_DRAWING_INSPECTION_LOGS_REQUEST';
// export const CLIENT_FETCH_DRAWING_INSPECTION_LOGS_SUCCESS =
//     'CLIENT_FETCH_DRAWING_INSPECTION_LOGS_SUCCESS';
// export const CLIENT_FETCH_DRAWING_INSPECTION_LOGS_FAILURE =
//     'CLIENT_FETCH_DRAWING_INSPECTION_LOGS_FAILURE';

export const CLIENT_FETCH_DRAWING_TEMPLATES_REQUEST =
    'CLIENT_FETCH_DRAWING_TEMPLATES_REQUEST';
export const CLIENT_FETCH_DRAWING_TEMPLATES_SUCCESS =
    'CLIENT_FETCH_DRAWING_TEMPLATES_SUCCESS';
export const CLIENT_FETCH_DRAWING_TEMPLATES_FAILURE =
    'CLIENT_FETCH_DRAWING_TEMPLATES_FAILURE';

export const CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_REQUEST =
    'CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_REQUEST';
export const CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_SUCCESS =
    'CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_SUCCESS';
export const CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_FAILURE =
    'CLIENT_FETCH_DRAWING_DROPDOWN_OPTIONS_FAILURE';
