export const CLIENT_FETCH_ALL_SITES_REQUEST = 'CLIENT_FETCH_ALL_SITES_REQUEST';
export const CLIENT_FETCH_ALL_SITES_SUCCESS = 'CLIENT_FETCH_ALL_SITES_SUCCESS';
export const CLIENT_FETCH_ALL_SITES_FAILURE = 'CLIENT_FETCH_ALL_SITES_FAILURE';

export const CLIENT_FETCH_SINGLE_SITE_REQUEST =
    'CLIENT_FETCH_SINGLE_SITE_REQUEST';
export const CLIENT_FETCH_SINGLE_SITE_SUCCESS =
    'CLIENT_FETCH_SINGLE_SITE_SUCCESS';
export const CLIENT_FETCH_SINGLE_SITE_FAILURE =
    'CLIENT_FETCH_SINGLE_SITE_FAILURE';
