export const CLIENT_FETCH_SEARCH_RESULTS_REQUEST =
    'CLIENT_FETCH_SEARCH_RESULTS_REQUEST';
export const CLIENT_FETCH_SEARCH_RESULTS_SUCCESS =
    'CLIENT_FETCH_SEARCH_RESULTS_SUCCESS';
export const CLIENT_FETCH_SEARCH_RESULTS_FAILURE =
    'CLIENT_FETCH_SEARCH_RESULTS_FAILURE';
