export const CLIENT_FETCH_OPTION_VALUES_BY_COMPANY_REQUEST =
    'CLIENT_FETCH_OPTION_VALUES_BY_COMPANY_REQUEST';
export const CLIENT_FETCH_OPTION_VALUES_BY_COMPANY_SUCCESS =
    'CLIENT_FETCH_OPTION_VALUES_BY_COMPANY_SUCCESS';
export const CLIENT_FETCH_OPTION_VALUES_BY_COMPANY_FAILURE =
    'CLIENT_FETCH_OPTION_VALUES_BY_COMPANY_FAILURE';
