export const CLIENT_FETCH_PROFILE_REQUEST = 'CLIENT_FETCH_PROFILE_REQUEST';
export const CLIENT_FETCH_PROFILE_SUCCESS = 'CLIENT_FETCH_PROFILE_SUCCESS';
export const CLIENT_FETCH_PROFILE_FAILURE = 'CLIENT_FETCH_PROFILE_FAILURE';

export const CLIENT_EDIT_PROFILE_REQUEST = 'CLIENT_EDIT_PROFILE_REQUEST';
export const CLIENT_EDIT_PROFILE_SUCCESS = 'CLIENT_EDIT_PROFILE_SUCCESS';
export const CLIENT_EDIT_PROFILE_FAILURE = 'CLIENT_EDIT_PROFILE_FAILURE';
