export const CLIENT_FETCH_PIN_OPERATIVES_REQUEST =
    'CLIENT_FETCH_PIN_OPERATIVES_REQUEST';
export const CLIENT_FETCH_PIN_OPERATIVES_SUCCESS =
    'CLIENT_FETCH_PIN_OPERATIVES_SUCCESS';
export const CLIENT_FETCH_PIN_OPERATIVES_FAILURE =
    'CLIENT_FETCH_PIN_OPERATIVES_FAILURE';
