export const CLIENT_FETCH_COMPANIES_SETTINGS_REQUEST =
    'CLIENT_FETCH_COMPANIES_SETTINGS_REQUEST';
export const CLIENT_FETCH_COMPANIES_SETTINGS_SUCCESS =
    'CLIENT_FETCH_COMPANIES_SETTINGS_SUCCESS';
export const CLIENT_FETCH_COMPANIES_SETTINGS_FAILURE =
    'CLIENT_FETCH_COMPANIES_SETTINGS_FAILURE';

export const CLIENT_SELECT_COMPANY = 'CLIENT_SELECT_COMPANY';
