export const CLIENT_UPDATE_REPORT_FILTER = 'CLIENT_UPDATE_REPORT_FILTERS';
export const CLIENT_UPDATE_OPERATIVE_FILTER = 'CLIENT_UPDATE_OPERATIVE_FILTERS';
export const CLIENT_UPDATE_SELECTED_PINS = 'CLIENT_UPDATE_SELECTED_PINS';

export const CLIENT_POST_REPORT_REQUEST = 'CLIENT_POST_REPORT_REQUEST';
export const CLIENT_POST_REPORT_SUCCESS = 'CLIENT_POST_REPORT_SUCCESS';
export const CLIENT_POST_REPORT_NO_PINS = 'CLIENT_POST_REPORT_NO_PINS';
export const CLIENT_POST_REPORT_FAILURE = 'CLIENT_POST_REPORT_FAILURE';

export const CLIENT_POST_CUSTOM_FILTERS_REQUEST =
    'CLIENT_POST_CUSTOM_FILTERS_REQUEST';
export const CLIENT_POST_CUSTOM_FILTERS_SUCCESS =
    'CLIENT_POST_CUSTOM_FILTERS_SUCCESS';
export const CLIENT_POST_CUSTOM_FILTERS_FAILURE =
    'CLIENT_POST_CUSTOM_FILTERS_FAILURE';

export const CLIENT_UPDATE_FILTER_QUESTION_FIELDS =
    'CLIENT_UPDATE_FILTER_QUESTION_FIELDS';
export const CLIENT_UPDATE_FILTER_QUESTION_FIELD =
    'CLIENT_UPDATE_FILTER_QUESTION_FIELD';
export const CLIENT_ADD_FILTER_QUESTION = 'CLIENT_ADD_FILTER_QUESTION';
export const CLIENT_REMOVE_FILTER_QUESTION = 'CLIENT_REMOVE_FILTER_QUESTION';
export const CLIENT_REMOVE_FILTER_QUESTIONS = 'CLIENT_REMOVE_FILTER_QUESTIONS';
export const CLIENT_UPDATE_FILTER_OPTION = 'CLIENT_UPDATE_FILTER_OPTION';
export const CLIENT_RESET_FILTER_OPTIONS = 'CLIENT_RESET_FILTER_OPTIONS';

export const CLIENT_ADD_RECTANGLE = 'CLIENT_ADD_RECTANGLE';
export const CLIENT_REMOVE_RECTANGLE = 'CLIENT_REMOVE_RECTANGLE';
export const CLIENT_REMOVE_ALL_RECTANGLES = 'CLIENT_REMOVE_ALL_RECTANGLES';
export const CLIENT_UPDATE_FURTHER_FILTRATION_OPTION =
    'CLIENT_UPDATE_FURTHER_FILTRATION_OPTION';
export const CLIENT_UPDATE_IS_PIN_EXCLUDED = 'CLIENT_UPDATE_IS_PIN_EXCLUDED';
export const CLIENT_REMOVE_ALL_EXCLUDED_PINS =
    'CLIENT_REMOVE_ALL_EXCLUDED_PINS';
