export const CLIENT_FETCH_ALL_SERVICES_REQUEST =
    'CLIENT_FETCH_ALL_SERVICES_REQUEST';
export const CLIENT_FETCH_ALL_SERVICES_SUCCESS =
    'CLIENT_FETCH_ALL_SERVICES_SUCCESS';
export const CLIENT_FETCH_ALL_SERVICES_FAILURE =
    'CLIENT_FETCH_ALL_SERVICES_FAILURE';

export const CLIENT_FETCH_HISTORIC_SERVICES_REQUEST =
    'CLIENT_FETCH_HISTORIC_SERVICES_REQUEST';
export const CLIENT_FETCH_HISTORIC_SERVICES_SUCCESS =
    'CLIENT_FETCH_HISTORIC_SERVICES_SUCCESS';
export const CLIENT_FETCH_HISTORIC_SERVICES_FAILURE =
    'CLIENT_FETCH_HISTORIC_SERVICES_FAILURE';
