export const CLIENT_FETCH_ALL_FLOORS_REQUEST =
    'CLIENT_FETCH_ALL_FLOORS_REQUEST';
export const CLIENT_FETCH_ALL_FLOORS_SUCCESS =
    'CLIENT_FETCH_ALL_FLOORS_SUCCESS';
export const CLIENT_FETCH_ALL_FLOORS_FAILURE =
    'CLIENT_FETCH_ALL_FLOORS_FAILURE';

export const CLIENT_FETCH_SINGLE_FLOOR_REQUEST =
    'CLIENT_FETCH_SINGLE_FLOOR_REQUEST';
export const CLIENT_FETCH_SINGLE_FLOOR_SUCCESS =
    'CLIENT_FETCH_SINGLE_FLOOR_SUCCESS';
export const CLIENT_FETCH_SINGLE_FLOOR_FAILURE =
    'CLIENT_FETCH_SINGLE_FLOOR_FAILURE';
