export const CLIENT_FETCH_ALL_BUILDINGS_REQUEST =
    'CLIENT_FETCH_ALL_BUILDINGS_REQUEST';
export const CLIENT_FETCH_ALL_BUILDINGS_SUCCESS =
    'CLIENT_FETCH_ALL_BUILDINGS_SUCCESS';
export const CLIENT_FETCH_ALL_BUILDINGS_FAILURE =
    'CLIENT_FETCH_ALL_BUILDINGS_FAILURE';

export const CLIENT_FETCH_SINGLE_BUILDING_REQUEST =
    'CLIENT_FETCH_SINGLE_BUILDING_REQUEST';
export const CLIENT_FETCH_SINGLE_BUILDING_SUCCESS =
    'CLIENT_FETCH_SINGLE_BUILDING_SUCCESS';
export const CLIENT_FETCH_SINGLE_BUILDING_FAILURE =
    'CLIENT_FETCH_SINGLE_BUILDING_FAILURE';
