export const CLIENT_FETCH_COMPANY_REPORTS_REQUEST = 'CLIENT_FETCH_COMPANY_REPORTS_REQUEST';
export const CLIENT_FETCH_COMPANY_REPORTS_SUCCESS = 'CLIENT_FETCH_COMPANY_REPORTS_SUCCESS';
export const CLIENT_FETCH_COMPANY_REPORTS_FAILURE = 'CLIENT_FETCH_COMPANY_REPORTS_FAILURE';

export const CLIENT_FETCH_COMPANY_REPORTS_FULL_REQUEST =
    'CLIENT_FETCH_COMPANY_REPORTS_FULL_REQUEST';
export const CLIENT_FETCH_COMPANY_REPORTS_FULL_SUCCESS =
    'CLIENT_FETCH_COMPANY_REPORTS_FULL_SUCCESS';
export const CLIENT_FETCH_COMPANY_REPORTS_FULL_FAILURE =
    'CLIENT_FETCH_COMPANY_REPORTS_FULL_FAILURE';

export const CLIENT_UPDATE_COMPANY_REPORTS_SORT = 'CLIENT_UPDATE_COMPANY_REPORTS_SORT';
