export const CLIENT_FETCH_COMPANY_USERS_REQUEST =
    'CLIENT_FETCH_COMPANY_USERS_REQUEST';
export const CLIENT_FETCH_COMPANY_USERS_SUCCESS =
    'CLIENT_FETCH_COMPANY_USERS_SUCCESS';
export const CLIENT_FETCH_COMPANY_USERS_FAILURE =
    'CLIENT_FETCH_COMPANY_USERS_FAILURE';
