export const FETCH_ACTIVITY_LOG_REQUEST = 'FETCH_ACTIVITY_LOG_REQUEST';
export const FETCH_ACTIVITY_LOG_SUCCESS = 'FETCH_ACTIVITY_LOG_SUCCESS';
export const FETCH_ACTIVITY_LOG_FAILURE = 'FETCH_ACTIVITY_LOG_FAILURE';

export const FETCH_ACTIVITY_LOG_SETTINGS_REQUEST = 'FETCH_ACTIVITY_LOG_SETTINGS_REQUEST';
export const FETCH_ACTIVITY_LOG_SETTINGS_SUCCESS = 'FETCH_ACTIVITY_LOG_SETTINGS_SUCCESS';
export const FETCH_ACTIVITY_LOG_SETTINGS_FAILURE = 'FETCH_ACTIVITY_LOG_SETTINGS_FAILURE';

export const POST_ACTIVITY_LOG_SETTINGS_REQUEST = 'POST_ACTIVITY_LOG_SETTINGS_REQUEST';
export const POST_ACTIVITY_LOG_SETTINGS_SUCCESS = 'POST_ACTIVITY_LOG_SETTINGS_SUCCESS';
export const POST_ACTIVITY_LOG_SETTINGS_FAILURE = 'POST_ACTIVITY_LOG_SETTINGS_FAILURE';
