export const FETCH_ACTIVITY_LOG_REQUEST = 'FETCH_ACTIVITY_LOG_REQUEST';
export const FETCH_ACTIVITY_LOG_SUCCESS = 'FETCH_ACTIVITY_LOG_SUCCESS';
export const FETCH_ACTIVITY_LOG_FAILURE = 'FETCH_ACTIVITY_LOG_FAILURE';
