export const CREATE_ALERT_REQUEST = 'CREATE_ALERT_REQUEST';
export const CREATE_ALERT_SUCCESS = 'CREATE_ALERT_SUCCESS';
export const CREATE_ALERT_FAILURE = 'CREATE_ALERT_FAILURE';

export const FETCH_HIERARCHY_ALERTS_REQUEST = 'FETCH_HIERARCHY_ALERTS_REQUEST';
export const FETCH_HIERARCHY_ALERTS_SUCCESS = 'FETCH_HIERARCHY_ALERTS_SUCCESS';
export const FETCH_HIERARCHY_ALERTS_FAILURE = 'FETCH_HIERARCHY_ALERTS_FAILURE';

export const FETCH_ALL_ALERTS_REQUEST = 'FETCH_ALL_ALERTS_REQUEST';
export const FETCH_ALL_ALERTS_SUCCESS = 'FETCH_ALL_ALERTS_SUCCESS';
export const FETCH_ALL_ALERTS_FAILURE = 'FETCH_ALL_ALERTS_FAILURE';

export const UPDATE_ALERT_REQUEST = 'UPDATE_ALERT_REQUEST';
export const UPDATE_ALERT_SUCCESS = 'UPDATE_ALERT_SUCCESS';
export const UPDATE_ALERT_FAILURE = 'UPDATE_ALERT_FAILURE';

export const DELETE_ALERT_REQUEST = 'DELETE_ALERT_REQUEST';
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS';
export const DELETE_ALERT_FAILURE = 'DELETE_ALERT_FAILURE';

export const DISMISS_ALERT_REQUEST = 'DISMISS_ALERT_REQUEST';
export const DISMISS_ALERT_SUCCESS = 'DISMISS_ALERT_SUCCESS';
export const DISMISS_ALERT_FAILURE = 'DISMISS_ALERT_FAILURE';

export const DISMISS_ALL_ALERTS_REQUEST = 'DISMISS_ALL_ALERTS_REQUEST';
export const DISMISS_ALL_ALERTS_SUCCESS = 'DISMISS_ALL_ALERTS_SUCCESS';
export const DISMISS_ALL_ALERTS_FAILURE = 'DISMISS_ALL_ALERTS_FAILURE';
