export const FETCH_LATEST_APP_VERSION_REQUEST = 'FETCH_LATEST_APP_VERSION_REQUEST';
export const FETCH_LATEST_APP_VERSION_SUCCESS = 'FETCH_LATEST_APP_VERSION_SUCCESS';
export const FETCH_LATEST_APP_VERSION_FAILURE = 'FETCH_LATEST_APP_VERSION_FAILURE';