export const FETCH_ALL_APPROVED_COMPANIES_REQUEST =
    'FETCH_ALL_APPROVED_COMPANIES_REQUEST';
export const FETCH_ALL_APPROVED_COMPANIES_SUCCESS =
    'FETCH_ALL_APPROVED_COMPANIES_SUCCESS';
export const FETCH_ALL_APPROVED_COMPANIES_FAILURE =
    'FETCH_ALL_APPROVED_COMPANIES_FAILURE';

export const UPDATE_APPROVED_COMPANIES_FILTERS =
    'UPDATE_APPROVED_COMPANIES_FILTERS';
