export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_EMAIL_CONFIRMATION_REQUIRED = 'POST_LOGIN_EMAIL_CONFIRMATION_REQUIRED';
export const POST_LOGIN_TWO_FACTOR_REQUIRED = 'POST_LOGIN_TWO_FACTOR_REQUIRED';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const REISSUE_TOKEN_REQUEST = 'REISSUE_TOKEN_REQUEST';
export const REISSUE_TOKEN_FAILURE = 'REISSUE_TOKEN_FAILURE';
export const REISSUE_TOKEN_SUCCESS = 'REISSUE_TOKEN_SUCCESS';

export const POST_REGISTER_REQUEST = 'POST_REGISTER_REQUEST';
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS';
export const POST_REGISTER_FAILURE = 'POST_REGISTER_FAILURE';

export const POST_SELECT_COMPANY_REQUEST = 'POST_SELECT_COMPANY_REQUEST';
export const POST_SELECT_COMPANY_SUCCESS = 'POST_SELECT_COMPANY_SUCCESS';
export const POST_SELECT_COMPANY_FAILURE = 'POST_SELECT_COMPANY_FAILURE';

export const POST_REGISTER_STEP_VALIDATION_REQUEST = 'POST_REGISTER_STEP_VALIDATION_REQUEST';
export const POST_REGISTER_STEP_VALIDATION_SUCCESS = 'POST_REGISTER_STEP_VALIDATION_SUCCESS';
export const POST_REGISTER_STEP_VALIDATION_FAILURE = 'POST_REGISTER_STEP_VALIDATION_FAILURE';

export const POST_FORGOT_PASSWORD_REQUEST = 'POST_FORGOT_PASSWORD_REQUEST';
export const POST_FORGOT_PASSWORD_SUCCESS = 'POST_FORGOT_PASSWORD_SUCCESS';
export const POST_FORGOT_PASSWORD_FAILURE = 'POST_FORGOT_PASSWORD_FAILURE';

export const POST_EMAIL_CONFIRMATION_REQUEST = 'POST_EMAIL_CONFIRMATION_REQUEST';
export const POST_EMAIL_CONFIRMATION_SUCCESS = 'POST_EMAIL_CONFIRMATION_SUCCESS';
export const POST_EMAIL_CONFIRMATION_FAILURE = 'POST_EMAIL_CONFIRMATION_FAILURE';

export const POST_RESEND_EMAIL_CONFIRMATION_REQUEST = 'POST_RESEND_EMAIL_CONFIRMATION_REQUEST';
export const POST_RESEND_EMAIL_CONFIRMATION_SUCCESS = 'POST_RESEND_EMAIL_CONFIRMATION_SUCCESS';
export const POST_RESEND_EMAIL_CONFIRMATION_FAILURE = 'POST_RESEND_EMAIL_CONFIRMATION_FAILURE';

export const LOGOUT = 'LOGOUT';

export const FETCH_AUTH_AREA_TEXT_REQUEST = 'FETCH_AUTH_AREA_TEXT_REQUEST';
export const FETCH_AUTH_AREA_TEXT_SUCCESS = 'FETCH_AUTH_AREA_TEXT_SUCCESS';
export const FETCH_AUTH_AREA_TEXT_FAILURE = 'FETCH_AUTH_AREA_TEXT_FAILURE';

export const POST_SETUP_TWO_FACTOR_REQUEST = 'POST_SETUP_TWO_FACTOR_REQUEST';
export const POST_SETUP_TWO_FACTOR_SUCCESS = 'POST_SETUP_TWO_FACTOR_SUCCESS';
export const POST_SETUP_TWO_FACTOR_FAILURE = 'POST_SETUP_TWO_FACTOR_FAILURE';

export const POST_CONFIRM_SETUP_TWO_FACTOR_REQUEST = 'POST_CONFIRM_SETUP_TWO_FACTOR_REQUEST';
export const POST_CONFIRM_SETUP_TWO_FACTOR_SUCCESS = 'POST_CONFIRM_SETUP_TWO_FACTOR_SUCCESS';
export const POST_CONFIRM_SETUP_TWO_FACTOR_FAILURE = 'POST_CONFIRM_SETUP_TWO_FACTOR_FAILURE';

export const POST_DISABLE_TWO_FACTOR_REQUEST = 'POST_DISABLE_TWO_FACTOR_REQUEST';
export const POST_DISABLE_TWO_FACTOR_SUCCESS = 'POST_DISABLE_TWO_FACTOR_SUCCESS';
export const POST_DISABLE_TWO_FACTOR_FAILURE = 'POST_DISABLE_TWO_FACTOR_FAILURE';

export const POST_CONFIRM_DISABLE_TWO_FACTOR_REQUEST = 'POST_CONFIRM_DISABLE_TWO_FACTOR_REQUEST';
export const POST_CONFIRM_DISABLE_TWO_FACTOR_SUCCESS = 'POST_CONFIRM_DISABLE_TWO_FACTOR_SUCCESS';
export const POST_CONFIRM_DISABLE_TWO_FACTOR_FAILURE = 'POST_CONFIRM_DISABLE_TWO_FACTOR_FAILURE';
