export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const REISSUE_TOKEN_REQUEST = 'REISSUE_TOKEN_REQUEST';
export const REISSUE_TOKEN_FAILURE = 'REISSUE_TOKEN_FAILURE';
export const REISSUE_TOKEN_SUCCESS = 'REISSUE_TOKEN_SUCCESS';

export const POST_REGISTER_REQUEST = 'POST_REGISTER_REQUEST';
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS';
export const POST_REGISTER_FAILURE = 'POST_REGISTER_FAILURE';

export const POST_FORGOT_PASSWORD_REQUEST = 'POST_FORGOT_PASSWORD_REQUEST';
export const POST_FORGOT_PASSWORD_SUCCESS = 'POST_FORGOT_PASSWORD_SUCCESS';
export const POST_FORGOT_PASSWORD_FAILURE = 'POST_FORGOT_PASSWORD_FAILURE';

export const LOGOUT = 'LOGOUT';

export const FETCH_AUTH_AREA_TEXT_REQUEST = 'FETCH_AUTH_AREA_TEXT_REQUEST';
export const FETCH_AUTH_AREA_TEXT_SUCCESS = 'FETCH_AUTH_AREA_TEXT_SUCCESS';
export const FETCH_AUTH_AREA_TEXT_FAILURE = 'FETCH_AUTH_AREA_TEXT_FAILURE';
