export const FETCH_BUG_REPORTS_REQUEST = 'FETCH_BUG_REPORTS_REQUEST';
export const FETCH_BUG_REPORTS_SUCCESS = 'FETCH_BUG_REPORTS_SUCCESS';
export const FETCH_BUG_REPORTS_FAILURE = 'FETCH_BUG_REPORTS_FAILURE';

export const FETCH_BUG_REPORT_REQUEST = 'FETCH_BUG_REPORT_REQUEST';
export const FETCH_BUG_REPORT_SUCCESS = 'FETCH_BUG_REPORT_SUCCESS';
export const FETCH_BUG_REPORT_FAILURE = 'FETCH_BUG_REPORT_FAILURE';

export const DELETE_BUG_REPORT_REQUEST = 'DELETE_BUG_REPORT_REQUEST';
export const DELETE_BUG_REPORT_SUCCESS = 'DELETE_BUG_REPORT_SUCCESS';
export const DELETE_BUG_REPORT_FAILURE = 'DELETE_BUG_REPORT_FAILURE';

export const CREATE_BUG_REPORT_REQUEST = 'CREATE_BUG_REPORT_REQUEST';
export const CREATE_BUG_REPORT_SUCCESS = 'CREATE_BUG_REPORT_SUCCESS';
export const CREATE_BUG_REPORT_FAILURE = 'CREATE_BUG_REPORT_FAILURE';

export const MARK_BUG_REPORT_REQUEST = 'MARK_BUG_REPORT_REQUEST';
export const MARK_BUG_REPORT_SUCCESS = 'MARK_BUG_REPORT_SUCCESS';
export const MARK_BUG_REPORT_FAILURE = 'MARK_BUG_REPORT_FAILURE';
