export const FETCH_BUG_REPORTS_REQUEST = 'FETCH_BUG_REPORTS_REQUEST';
export const FETCH_BUG_REPORTS_SUCCESS = 'FETCH_BUG_REPORTS_SUCCESS';
export const FETCH_BUG_REPORTS_FAILURE = 'FETCH_BUG_REPORTS_FAILURE';

export const FETCH_BUG_REPORT_REQUEST = 'FETCH_BUG_REPORT_REQUEST';
export const FETCH_BUG_REPORT_SUCCESS = 'FETCH_BUG_REPORT_SUCCESS';
export const FETCH_BUG_REPORT_FAILURE = 'FETCH_BUG_REPORT_FAILURE';
