export const UPDATE_BUILDINGS_SEARCH_TERM = 'UPDATE_BUILDINGS_SEARCH_TERM';
export const SET_BUILDINGS_FILTER_STATUS = 'SET_BUILDINGS_FILTER_STATUS';

export const FETCH_ALL_BUILDINGS_REQUEST = 'FETCH_ALL_BUILDINGS_REQUEST';
export const FETCH_ALL_BUILDINGS_SUCCESS = 'FETCH_ALL_BUILDINGS_SUCCESS';
export const FETCH_ALL_BUILDINGS_FAILURE = 'FETCH_ALL_BUILDINGS_FAILURE';

export const FETCH_SINGLE_BUILDING_REQUEST = 'FETCH_SINGLE_BUILDING_REQUEST';
export const FETCH_SINGLE_BUILDING_SUCCESS = 'FETCH_SINGLE_BUILDING_SUCCESS';
export const FETCH_SINGLE_BUILDING_FAILURE = 'FETCH_SINGLE_BUILDING_FAILURE';

export const CREATE_BUILDING_REQUEST = 'CREATE_BUILDING_REQUEST';
export const CREATE_BUILDING_SUCCESS = 'CREATE_BUILDING_SUCCESS';
export const CREATE_BUILDING_FAILURE = 'CREATE_BUILDING_FAILURE';
