export const UPDATE_BUILDINGS_SEARCH_TERM = 'UPDATE_BUILDINGS_SEARCH_TERM';
export const SET_BUILDINGS_FILTER_STATUS = 'SET_BUILDINGS_FILTER_STATUS';

export const FETCH_ALL_BUILDINGS_REQUEST = 'FETCH_ALL_BUILDINGS_REQUEST';
export const FETCH_ALL_BUILDINGS_SUCCESS = 'FETCH_ALL_BUILDINGS_SUCCESS';
export const FETCH_ALL_BUILDINGS_FAILURE = 'FETCH_ALL_BUILDINGS_FAILURE';
export const POST_BUILDINGS_SORT = 'POST_BUILDINGS_SORT';

export const REORDER_BUILDING = 'REORDER_BUILDING';

export const FETCH_SINGLE_BUILDING_REQUEST = 'FETCH_SINGLE_BUILDING_REQUEST';
export const FETCH_SINGLE_BUILDING_SUCCESS = 'FETCH_SINGLE_BUILDING_SUCCESS';
export const FETCH_SINGLE_BUILDING_FAILURE = 'FETCH_SINGLE_BUILDING_FAILURE';

export const CREATE_BUILDING_REQUEST = 'CREATE_BUILDING_REQUEST';
export const CREATE_BUILDING_SUCCESS = 'CREATE_BUILDING_SUCCESS';
export const CREATE_BUILDING_FAILURE = 'CREATE_BUILDING_FAILURE';

export const CREATE_BUILDINGS_REQUEST = 'CREATE_BUILDINGS_REQUEST';
export const CREATE_BUILDINGS_SUCCESS = 'CREATE_BUILDINGS_SUCCESS';
export const CREATE_BUILDINGS_FAILURE = 'CREATE_BUILDINGS_FAILURE';

export const EDIT_BUILDING_REQUEST = 'EDIT_BUILDING_REQUEST';
export const EDIT_BUILDING_SUCCESS = 'EDIT_BUILDING_SUCCESS';
export const EDIT_BUILDING_FAILURE = 'EDIT_BUILDING_FAILURE';

export const DELETE_BUILDING_REQUEST = 'DELETE_BUILDING_REQUEST';
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS';
export const DELETE_BUILDING_FAILURE = 'DELETE_BUILDING_FAILURE';

export const ARCHIVE_BUILDING_REQUEST = 'ARCHIVE_BUILDING_REQUEST';
export const ARCHIVE_BUILDING_SUCCESS = 'ARCHIVE_BUILDING_SUCCESS';
export const ARCHIVE_BUILDING_FAILURE = 'ARCHIVE_BUILDING_FAILURE';
