export const FETCH_ALL_CARDS_REQUEST = 'FETCH_ALL_CARDS_REQUEST';
export const FETCH_ALL_CARDS_FAILURE = 'FETCH_ALL_CARDS_FAILURE';
export const FETCH_ALL_CARDS_SUCCESS = 'FETCH_ALL_CARDS_SUCCESS';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';

export const SET_PRIMARY_CARD_REQUEST = 'SET_PRIMARY_CARD_REQUEST';
export const SET_PRIMARY_CARD_FAILURE = 'SET_PRIMARY_CARD_FAILURE';
export const SET_PRIMARY_CARD_SUCCESS = 'SET_PRIMARY_CARD_SUCCESS';
