export const INVITE_CLIENT_REQUEST = 'INVITE_CLIENT_REQUEST';
export const INVITE_CLIENT_SUCCESS = 'INVITE_CLIENT_SUCCESS';
export const INVITE_CLIENT_FAILURE = 'INVITE_CLIENT_FAILURE';

export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';

export const FETCH_CLIENTS_FOR_DRAWING_REQUEST =
    'FETCH_CLIENTS_FOR_DRAWING_REQUEST';
export const FETCH_CLIENTS_FOR_DRAWING_SUCCESS =
    'FETCH_CLIENTS_FOR_DRAWING_SUCCESS';
export const FETCH_CLIENTS_FOR_DRAWING_FAILURE =
    'FETCH_CLIENTS_FOR_DRAWING_FAILURE';

export const EDIT_CLIENT_FOR_DRAWING_REQUEST =
    'EDIT_CLIENT_FOR_DRAWING_REQUEST';
export const EDIT_CLIENT_FOR_DRAWING_SUCCESS =
    'EDIT_CLIENT_FOR_DRAWING_SUCCESS';
export const EDIT_CLIENT_FOR_DRAWING_FAILURE =
    'EDIT_CLIENT_FOR_DRAWING_FAILURE';

export const DELETE_CLIENT_FROM_DRAWING_REQUEST =
    'DELETE_CLIENT_FROM_DRAWING_REQUEST';
export const DELETE_CLIENT_FROM_DRAWING_SUCCESS =
    'DELETE_CLIENT_FROM_DRAWING_SUCCESS';
export const DELETE_CLIENT_FROM_DRAWING_FAILURE =
    'DELETE_CLIENT_FROM_DRAWING_FAILURE';
