export const INVITE_CLIENT_REQUEST = 'INVITE_CLIENT_REQUEST';
export const INVITE_CLIENT_SUCCESS = 'INVITE_CLIENT_SUCCESS';
export const INVITE_CLIENT_FAILURE = 'INVITE_CLIENT_FAILURE';

export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';

export const ADD_CLIENT_USER_REQUEST = 'ADD_CLIENT_USER_REQUEST';
export const ADD_CLIENT_USER_SUCCESS = 'ADD_CLIENT_USER_SUCCESS';
export const ADD_CLIENT_USER_FAILURE = 'ADD_CLIENT_USER_FAILURE';

export const ADD_MANY_CLIENTS_REQUEST = 'ADD_MANY_CLIENTS_REQUEST';
export const ADD_MANY_CLIENTS_SUCCESS = 'ADD_MANY_CLIENTS_SUCCESS';
export const ADD_MANY_CLIENTS_FAILURE = 'ADD_MANY_CLIENTS_FAILURE';

export const FETCH_CLIENTS_FOR_DRAWING_REQUEST = 'FETCH_CLIENTS_FOR_DRAWING_REQUEST';
export const FETCH_CLIENTS_FOR_DRAWING_SUCCESS = 'FETCH_CLIENTS_FOR_DRAWING_SUCCESS';
export const FETCH_CLIENTS_FOR_DRAWING_FAILURE = 'FETCH_CLIENTS_FOR_DRAWING_FAILURE';

export const EDIT_CLIENT_REQUEST = 'EDIT_CLIENT_REQUEST';
export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS';
export const EDIT_CLIENT_FAILURE = 'EDIT_CLIENT_FAILURE';

export const EDIT_CLIENT_FOR_DRAWING_REQUEST = 'EDIT_CLIENT_FOR_DRAWING_REQUEST';
export const EDIT_CLIENT_FOR_DRAWING_SUCCESS = 'EDIT_CLIENT_FOR_DRAWING_SUCCESS';
export const EDIT_CLIENT_FOR_DRAWING_FAILURE = 'EDIT_CLIENT_FOR_DRAWING_FAILURE';

export const DELETE_CLIENT_FROM_DRAWING_REQUEST = 'DELETE_CLIENT_FROM_DRAWING_REQUEST';
export const DELETE_CLIENT_FROM_DRAWING_SUCCESS = 'DELETE_CLIENT_FROM_DRAWING_SUCCESS';
export const DELETE_CLIENT_FROM_DRAWING_FAILURE = 'DELETE_CLIENT_FROM_DRAWING_FAILURE';

export const DELETE_CLIENT_USER_REQUEST = 'DELETE_CLIENT_USER_REQUEST';
export const DELETE_CLIENT_USER_SUCCESS = 'DELETE_CLIENT_USER_SUCCESS';
export const DELETE_CLIENT_USER_FAILURE = 'DELETE_CLIENT_USER_FAILURE';

export const DISABLE_CLIENT_USER_REQUEST = 'DISABLE_CLIENT_USER_REQUEST';
export const DISABLE_CLIENT_USER_SUCCESS = 'DISABLE_CLIENT_USER_SUCCESS';
export const DISABLE_CLIENT_USER_FAILURE = 'DISABLE_CLIENT_USER_FAILURE';

export const FETCH_CLIENTS_FOR_FLOOR_REQUEST = 'FETCH_CLIENTS_FOR_FLOOR_REQUEST';
export const FETCH_CLIENTS_FOR_FLOOR_SUCCESS = 'FETCH_CLIENTS_FOR_FLOOR_SUCCESS';
export const FETCH_CLIENTS_FOR_FLOOR_FAILURE = 'FETCH_CLIENTS_FOR_FLOOR_FAILURE';
