export const FETCH_COMPANY_SETTINGS_REQUEST = 'FETCH_COMPANY_SETTINGS_REQUEST';
export const FETCH_COMPANY_SETTINGS_SUCCESS = 'FETCH_COMPANY_SETTINGS_SUCCESS';
export const FETCH_COMPANY_SETTINGS_FAILURE = 'FETCH_COMPANY_SETTINGS_FAILURE';

export const EDIT_COMPANY_SETTINGS_REQUEST = 'EDIT_COMPANY_SETTINGS_REQUEST';
export const EDIT_COMPANY_SETTINGS_SUCCESS = 'EDIT_COMPANY_SETTINGS_SUCCESS';
export const EDIT_COMPANY_SETTINGS_FAILURE = 'EDIT_COMPANY_SETTINGS_FAILURE';
