export const FETCH_COMPANY_REPORTS_REQUEST = 'FETCH_COMPANY_REPORTS_REQUEST';
export const FETCH_COMPANY_REPORTS_SUCCESS = 'FETCH_COMPANY_REPORTS_SUCCESS';
export const FETCH_COMPANY_REPORTS_FAILURE = 'FETCH_COMPANY_REPORTS_FAILURE';

export const UPDATE_COMPANY_REPORTS_SORT = 'UPDATE_COMPANY_REPORTS_SORT';
