export const FETCH_SINGLE_BANNER_NOTIFICATIONS_REQUEST =
    'FETCH_SINGLE_BANNER_NOTIFICATIONS_REQUEST';
export const FETCH_SINGLE_BANNER_NOTIFICATIONS_SUCCESS =
    'FETCH_SINGLE_BANNER_NOTIFICATIONS_SUCCESS';
export const FETCH_SINGLE_BANNER_NOTIFICATIONS_FAILURE =
    'FETCH_SINGLE_BANNER_NOTIFICATIONS_FAILURE';

export const UPDATE_BANNER_NOTIFICATIONS_REQUEST = 'UPDATE_BANNER_NOTIFICATIONS_REQUEST';
export const UPDATE_BANNER_NOTIFICATIONS_SUCCESS = 'UPDATE_BANNER_NOTIFICATIONS_SUCCESS';
export const UPDATE_BANNER_NOTIFICATIONS_FAILURE = 'UPDATE_BANNER_NOTIFICATIONS_FAILURE';
