export const FETCH_PIN_OPTION_MANUFACTURERS_REQUEST = 'FETCH_PIN_OPTION_MANUFACTURERS_REQUEST';
export const FETCH_PIN_OPTION_MANUFACTURERS_SUCCESS = 'FETCH_PIN_OPTION_MANUFACTURERS_SUCCESS';
export const FETCH_PIN_OPTION_MANUFACTURERS_FAILURE = 'FETCH_PIN_OPTION_MANUFACTURERS_FAILURE';

export const FETCH_SINGLE_MANUFACTURER_REQUEST = 'FETCH_SINGLE_MANUFACTURER_REQUEST';
export const FETCH_SINGLE_MANUFACTURER_SUCCESS = 'FETCH_SINGLE_MANUFACTURER_SUCCESS';
export const FETCH_SINGLE_MANUFACTURER_FAILURE = 'FETCH_SINGLE_MANUFACTURER_FAILURE';

export const CREATE_MANUFACTURER_REQUEST = 'CREATE_MANUFACTURER_REQUEST';
export const CREATE_MANUFACTURER_SUCCESS = 'CREATE_MANUFACTURER_SUCCESS';
export const CREATE_MANUFACTURER_FAILURE = 'CREATE_MANUFACTURER_FAILURE';

export const EDIT_MANUFACTURER_REQUEST = 'EDIT_MANUFACTURER_REQUEST';
export const EDIT_MANUFACTURER_SUCCESS = 'EDIT_MANUFACTURER_SUCCESS';
export const EDIT_MANUFACTURER_FAILURE = 'EDIT_MANUFACTURER_FAILURE';

export const TOGGLE_MANUFACTURER_REQUEST = 'TOGGLE_MANUFACTURER_REQUEST';
export const TOGGLE_MANUFACTURER_SUCCESS = 'TOGGLE_MANUFACTURER_SUCCESS';
export const TOGGLE_MANUFACTURER_FAILURE = 'TOGGLE_MANUFACTURER_FAILURE';

export const FETCH_OPTION_VALUES_BY_MANUFACTURER_REQUEST =
    'FETCH_OPTION_VALUES_BY_MANUFACTURER_REQUEST';
export const FETCH_OPTION_VALUES_BY_MANUFACTURER_SUCCESS =
    'FETCH_OPTION_VALUES_BY_MANUFACTURER_SUCCESS';
export const FETCH_OPTION_VALUES_BY_MANUFACTURER_FAILURE =
    'FETCH_OPTION_VALUES_BY_MANUFACTURER_FAILURE';

export const TOGGLE_MANUFACTURER_OPTION_VALUE_REQUEST = 'TOGGLE_MANUFACTURER_OPTION_VALUE_REQUEST';
export const TOGGLE_MANUFACTURER_OPTION_VALUE_SUCCESS = 'TOGGLE_MANUFACTURER_OPTION_VALUE_SUCCESS';
export const TOGGLE_MANUFACTURER_OPTION_VALUE_FAILURE = 'TOGGLE_MANUFACTURER_OPTION_VALUE_FAILURE';

export const CREATE_OPTION_VALUE_REQUEST = 'CREATE_OPTION_VALUE_REQUEST';
export const CREATE_OPTION_VALUE_SUCCESS = 'CREATE_OPTION_VALUE_SUCCESS';
export const CREATE_OPTION_VALUE_FAILURE = 'CREATE_OPTION_VALUE_FAILURE';

export const EDIT_OPTION_VALUE_REQUEST = 'EDIT_OPTION_VALUE_REQUEST';
export const EDIT_OPTION_VALUE_SUCCESS = 'EDIT_OPTION_VALUE_SUCCESS';
export const EDIT_OPTION_VALUE_FAILURE = 'EDIT_OPTION_VALUE_FAILURE';

export const FETCH_DOCUMENTS_BY_OPTION_VALUE_REQUEST = 'FETCH_DOCUMENTS_BY_OPTION_VALUE_REQUEST';
export const FETCH_DOCUMENTS_BY_OPTION_VALUE_SUCCESS = 'FETCH_DOCUMENTS_BY_OPTION_VALUE_SUCCESS';
export const FETCH_DOCUMENTS_BY_OPTION_VALUE_FAILURE = 'FETCH_DOCUMENTS_BY_OPTION_VALUE_FAILURE';

export const CREATE_DOCUMENT_FOR_OPTION_VALUE_REQUEST = 'CREATE_DOCUMENT_FOR_OPTION_VALUE_REQUEST';
export const CREATE_DOCUMENT_FOR_OPTION_VALUE_SUCCESS = 'CREATE_DOCUMENT_FOR_OPTION_VALUE_SUCCESS';
export const CREATE_DOCUMENT_FOR_OPTION_VALUE_FAILURE = 'CREATE_DOCUMENT_FOR_OPTION_VALUE_FAILURE';

export const EDIT_OPTION_VALUE_DOCUMENT_REQUEST = 'EDIT_OPTION_VALUE_DOCUMENT_REQUEST';
export const EDIT_OPTION_VALUE_DOCUMENT_SUCCESS = 'EDIT_OPTION_VALUE_DOCUMENT_SUCCESS';
export const EDIT_OPTION_VALUE_DOCUMENT_FAILURE = 'EDIT_OPTION_VALUE_DOCUMENT_FAILURE';

export const CREATE_NEW_OPTION_VALUE_DOCUMENT_VERSION_REQUEST =
    'CREATE_NEW_OPTION_VALUE_DOCUMENT_VERSION_REQUEST';
export const CREATE_NEW_OPTION_VALUE_DOCUMENT_VERSION_SUCCESS =
    'CREATE_NEW_OPTION_VALUE_DOCUMENT_VERSION_SUCCESS';
export const CREATE_NEW_OPTION_VALUE_DOCUMENT_VERSION_FAILURE =
    'CREATE_NEW_OPTION_VALUE_DOCUMENT_VERSION_FAILURE';

export const DELETE_OPTION_VALUE_DOCUMENT_VERSION_REQUEST =
    'DELETE_OPTION_VALUE_DOCUMENT_VERSION_REQUEST';
export const DELETE_OPTION_VALUE_DOCUMENT_VERSION_SUCCESS =
    'DELETE_OPTION_VALUE_DOCUMENT_VERSION_SUCCESS';
export const DELETE_OPTION_VALUE_DOCUMENT_VERSION_FAILURE =
    'DELETE_OPTION_VALUE_DOCUMENT_VERSION_FAILURE';

export const FETCH_ALL_OPTION_VALUES_REQUEST = 'FETCH_ALL_OPTION_VALUES_REQUEST';
export const FETCH_ALL_OPTION_VALUES_SUCCESS = 'FETCH_ALL_OPTION_VALUES_SUCCESS';
export const FETCH_ALL_OPTION_VALUES_FAILURE = 'FETCH_ALL_OPTION_VALUES_FAILURE';
