export const FETCH_ALL_COMPANIES_REQUEST = 'FETCH_ALL_COMPANIES_REQUEST';
export const FETCH_ALL_COMPANIES_SUCCESS = 'FETCH_ALL_COMPANIES_SUCCESS';
export const FETCH_ALL_COMPANIES_FAILURE = 'FETCH_ALL_COMPANIES_FAILURE';

export const ADMIN_FETCH_SITES_FOR_COMPANY_REQUEST =
    'ADMIN_FETCH_SITES_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_SITES_FOR_COMPANY_SUCCESS =
    'ADMIN_FETCH_SITES_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_SITES_FOR_COMPANY_FAILURE =
    'ADMIN_FETCH_SITES_FOR_COMPANY_FAILURE';

export const ADMIN_FETCH_BUILDINGS_FOR_COMPANY_REQUEST =
    'ADMIN_FETCH_BUILDINGS_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_BUILDINGS_FOR_COMPANY_SUCCESS =
    'ADMIN_FETCH_BUILDINGS_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_BUILDINGS_FOR_COMPANY_FAILURE =
    'ADMIN_FETCH_BUILDINGS_FOR_COMPANY_FAILURE';

export const ADMIN_FETCH_FLOORS_FOR_COMPANY_REQUEST =
    'ADMIN_FETCH_FLOORS_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_FLOORS_FOR_COMPANY_SUCCESS =
    'ADMIN_FETCH_FLOORS_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_FLOORS_FOR_COMPANY_FAILURE =
    'ADMIN_FETCH_FLOORS_FOR_COMPANY_FAILURE';

export const ADMIN_FETCH_DRAWINGS_FOR_COMPANY_REQUEST =
    'ADMIN_FETCH_DRAWINGS_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_DRAWINGS_FOR_COMPANY_SUCCESS =
    'ADMIN_FETCH_DRAWINGS_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_DRAWINGS_FOR_COMPANY_FAILURE =
    'ADMIN_FETCH_DRAWINGS_FOR_COMPANY_FAILURE';

export const UPDATE_COMPANIES_FILTERS = 'UPDATE_COMPANIES_FILTERS';
