export const FETCH_ALL_COMPANIES_REQUEST = 'FETCH_ALL_COMPANIES_REQUEST';
export const FETCH_ALL_COMPANIES_SUCCESS = 'FETCH_ALL_COMPANIES_SUCCESS';
export const FETCH_ALL_COMPANIES_FAILURE = 'FETCH_ALL_COMPANIES_FAILURE';

export const ADMIN_FETCH_SITES_FOR_COMPANY_REQUEST = 'ADMIN_FETCH_SITES_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_SITES_FOR_COMPANY_SUCCESS = 'ADMIN_FETCH_SITES_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_SITES_FOR_COMPANY_FAILURE = 'ADMIN_FETCH_SITES_FOR_COMPANY_FAILURE';

export const ADMIN_FETCH_BUILDINGS_FOR_COMPANY_REQUEST =
    'ADMIN_FETCH_BUILDINGS_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_BUILDINGS_FOR_COMPANY_SUCCESS =
    'ADMIN_FETCH_BUILDINGS_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_BUILDINGS_FOR_COMPANY_FAILURE =
    'ADMIN_FETCH_BUILDINGS_FOR_COMPANY_FAILURE';

export const ADMIN_FETCH_FLOORS_FOR_COMPANY_REQUEST = 'ADMIN_FETCH_FLOORS_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_FLOORS_FOR_COMPANY_SUCCESS = 'ADMIN_FETCH_FLOORS_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_FLOORS_FOR_COMPANY_FAILURE = 'ADMIN_FETCH_FLOORS_FOR_COMPANY_FAILURE';

export const ADMIN_FETCH_DRAWINGS_FOR_COMPANY_REQUEST = 'ADMIN_FETCH_DRAWINGS_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_DRAWINGS_FOR_COMPANY_SUCCESS = 'ADMIN_FETCH_DRAWINGS_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_DRAWINGS_FOR_COMPANY_FAILURE = 'ADMIN_FETCH_DRAWINGS_FOR_COMPANY_FAILURE';

export const FETCH_COMPANY_TEMPLATES_REQUEST = 'FETCH_COMPANY_TEMPLATES_REQUEST';
export const FETCH_COMPANY_TEMPLATES_SUCCESS = 'FETCH_COMPANY_TEMPLATES_SUCCESS';
export const FETCH_COMPANY_TEMPLATES_FAILURE = 'FETCH_COMPANY_TEMPLATES_FAILURE';

export const UPDATE_COMPANIES_FILTERS = 'UPDATE_COMPANIES_FILTERS';

export const SA_TOGGLE_COMPANY_ON_CLIENT_LIST_REQUEST = 'SA_TOGGLE_COMPANY_ON_CLIENT_LIST_REQUEST';
export const SA_TOGGLE_COMPANY_ON_CLIENT_LIST_SUCCESS = 'SA_TOGGLE_COMPANY_ON_CLIENT_LIST_SUCCESS';
export const SA_TOGGLE_COMPANY_ON_CLIENT_LIST_FAILURE = 'SA_TOGGLE_COMPANY_ON_CLIENT_LIST_FAILURE';

export const ADMIN_EDIT_COMPANY_ADDRESS_REQUEST = 'ADMIN_EDIT_COMPANY_ADDRESS_REQUEST';
export const ADMIN_EDIT_COMPANY_ADDRESS_SUCCESS = 'ADMIN_EDIT_COMPANY_ADDRESS_SUCCESS';
export const ADMIN_EDIT_COMPANY_ADDRESS_FAILURE = 'ADMIN_EDIT_COMPANY_ADDRESS_FAILURE';

export const ADMIN_EDIT_DRAWING_EXIPIRATION_DATE_REQUEST =
    'ADMIN_EDIT_DRAWING_EXIPIRATION_DATE_REQUEST';
export const ADMIN_EDIT_DRAWING_EXIPIRATION_DATE_SUCCESS =
    'ADMIN_EDIT_DRAWING_EXIPIRATION_DATE_SUCCESS';
export const ADMIN_EDIT_DRAWING_EXIPIRATION_DATE_FAILURE =
    'ADMIN_EDIT_DRAWING_EXIPIRATION_DATE_FAILURE';
