export const FETCH_COMPANY_REPORTS_REQUEST = 'FETCH_COMPANY_REPORTS_REQUEST';
export const FETCH_COMPANY_REPORTS_SUCCESS = 'FETCH_COMPANY_REPORTS_SUCCESS';
export const FETCH_COMPANY_REPORTS_FAILURE = 'FETCH_COMPANY_REPORTS_FAILURE';

export const FETCH_COMPANY_REPORTS_FULL_REQUEST = 'FETCH_COMPANY_REPORTS_FULL_REQUEST';
export const FETCH_COMPANY_REPORTS_FULL_SUCCESS = 'FETCH_COMPANY_REPORTS_FULL_SUCCESS';
export const FETCH_COMPANY_REPORTS_FULL_FAILURE = 'FETCH_COMPANY_REPORTS_FULL_FAILURE';

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAILURE = 'DELETE_REPORT_FAILURE';

export const ADMIN_FETCH_COMPANY_REPORTS_REQUEST = 'ADMIN_FETCH_COMPANY_REPORTS_REQUEST';
export const ADMIN_FETCH_COMPANY_REPORTS_SUCCESS = 'ADMIN_FETCH_COMPANY_REPORTS_SUCCESS';
export const ADMIN_FETCH_COMPANY_REPORTS_FAILURE = 'ADMIN_FETCH_COMPANY_REPORTS_FAILURE';

export const ADMIN_FETCH_COMPANY_REPORTS_FULL_REQUEST = 'ADMIN_FETCH_COMPANY_REPORTS_FULL_REQUEST';
export const ADMIN_FETCH_COMPANY_REPORTS_FULL_SUCCESS = 'ADMIN_FETCH_COMPANY_REPORTS_FULL_SUCCESS';
export const ADMIN_FETCH_COMPANY_REPORTS_FULL_FAILURE = 'ADMIN_FETCH_COMPANY_REPORTS_FULL_FAILURE';
export const ADMIN_UPDATE_COMPANY_REPORTS_SORT = 'ADMIN_UPDATE_COMPANY_REPORTS_SORT';

export const UPDATE_COMPANY_REPORTS_SORT = 'UPDATE_COMPANY_REPORTS_SORT';

export const ADMIN_RETRY_REPORT_REQUEST = 'ADMIN_RETRY_REPORT_REQUEST';
export const ADMIN_RETRY_REPORT_SUCCESS = 'ADMIN_RETRY_REPORT_SUCCESS';
export const ADMIN_RETRY_REPORT_FAILURE = 'ADMIN_RETRY_REPORT_FAILURE';

