export const FETCH_ALL_CONTACT_SUBMISSIONS_REQUEST = 'FETCH_ALL_CONTACT_SUBMISSIONS_REQUEST';
export const FETCH_ALL_CONTACT_SUBMISSIONS_SUCCESS = 'FETCH_ALL_CONTACT_SUBMISSIONS_SUCCESS';
export const FETCH_ALL_CONTACT_SUBMISSIONS_FAILURE = 'FETCH_ALL_CONTACT_SUBMISSIONS_FAILURE';

export const DELETE_CONTACT_SUBMISSION_REQUEST = 'DELETE_CONTACT_SUBMISSION_REQUEST';
export const DELETE_CONTACT_SUBMISSION_SUCCESS = 'DELETE_CONTACT_SUBMISSION_SUCCESS';
export const DELETE_CONTACT_SUBMISSION_FAILURE = 'DELETE_CONTACT_SUBMISSION_FAILURE';

export const FETCH_SINGLE_CONTACT_SUBMISSION_REQUEST = 'FETCH_SINGLE_CONTACT_SUBMISSION_REQUEST';
export const FETCH_SINGLE_CONTACT_SUBMISSION_SUCCESS = 'FETCH_SINGLE_CONTACT_SUBMISSION_SUCCESS';
export const FETCH_SINGLE_CONTACT_SUBMISSION_FAILURE = 'FETCH_SINGLE_CONTACT_SUBMISSION_FAILURE';

export const MARK_CONTACT_SUBMISSION_REQUEST = 'MARK_CONTACT_SUBMISSION_REQUEST';
export const MARK_CONTACT_SUBMISSION_SUCCESS = 'MARK_CONTACT_SUBMISSION_SUCCESS';
export const MARK_CONTACT_SUBMISSION_FAILURE = 'MARK_CONTACT_SUBMISSION_FAILURE';
