export const FETCH_COSTING_AND_ESTIMATING_DATA_REQUEST =
    'FETCH_COSTING_AND_ESTIMATING_DATA_REQUEST';
export const FETCH_COSTING_AND_ESTIMATING_DATA_SUCCESS =
    'FETCH_COSTING_AND_ESTIMATING_DATA_SUCCESS';
export const FETCH_COSTING_AND_ESTIMATING_DATA_FAILURE =
    'FETCH_COSTING_AND_ESTIMATING_DATA_FAILURE';

export const FETCH_COSTING_AND_ESTIMATING_CART_REQUEST =
    'FETCH_COSTING_AND_ESTIMATING_CART_REQUEST';
export const FETCH_COSTING_AND_ESTIMATING_CART_SUCCESS =
    'FETCH_COSTING_AND_ESTIMATING_CART_SUCCESS';
export const FETCH_COSTING_AND_ESTIMATING_CART_FAILURE =
    'FETCH_COSTING_AND_ESTIMATING_CART_FAILURE';

// Prelims

export const CREATE_COSTING_AND_ESTIMATING_PRELIM_REQUEST =
    'CREATE_COSTING_AND_ESTIMATING_CART_REQUEST';
export const CREATE_COSTING_AND_ESTIMATING_PRELIM_SUCCESS =
    'CREATE_COSTING_AND_ESTIMATING_CART_SUCCESS';
export const CREATE_COSTING_AND_ESTIMATING_PRELIM_FAILURE =
    'CREATE_COSTING_AND_ESTIMATING_CART_FAILURE';

export const LINK_PRELIM_REQUEST = 'LINK_PRELIM_REQUEST';
export const LINK_PRELIM_SUCCESS = 'LINK_PRELIM_SUCCESS';
export const LINK_PRELIM_FAILURE = 'LINK_PRELIM_FAILURE';

export const EDIT_LINK_PRELIM_REQUEST = 'EDIT_LINK_PRELIM_REQUEST';
export const EDIT_LINK_PRELIM_SUCCESS = 'EDIT_LINK_PRELIM_SUCCESS';
export const EDIT_LINK_PRELIM_FAILURE = 'EDIT_LINK_PRELIM_FAILURE';

export const DELETE_LINK_PRELIM_REQUEST = 'DELETE_LINK_PRELIM_REQUEST';
export const DELETE_LINK_PRELIM_SUCCESS = 'DELETE_LINK_PRELIM_SUCCESS';
export const DELETE_LINK_PRELIM_FAILURE = 'DELETE_LINK_PRELIM_FAILURE';

export const DELETE_COSTING_AND_ESTIMATING_PRELIM_REQUEST =
    'DELETE_COSTING_AND_ESTIMATING_PRELIM_REQUEST';
export const DELETE_COSTING_AND_ESTIMATING_PRELIM_SUCCESS =
    'DELETE_COSTING_AND_ESTIMATING_PRELIM_SUCCESS';
export const DELETE_COSTING_AND_ESTIMATING_PRELIM_FAILURE =
    'DELETE_COSTING_AND_ESTIMATING_PRELIM_FAILURE';
