export const FETCH_COSTING_AND_ESTIMATING_DATA_REQUEST =
    'FETCH_COSTING_AND_ESTIMATING_DATA_REQUEST';
export const FETCH_COSTING_AND_ESTIMATING_DATA_SUCCESS =
    'FETCH_COSTING_AND_ESTIMATING_DATA_SUCCESS';
export const FETCH_COSTING_AND_ESTIMATING_DATA_FAILURE =
    'FETCH_COSTING_AND_ESTIMATING_DATA_FAILURE';

export const FETCH_COSTING_AND_ESTIMATING_CART_REQUEST =
    'FETCH_COSTING_AND_ESTIMATING_CART_REQUEST';
export const FETCH_COSTING_AND_ESTIMATING_CART_SUCCESS =
    'FETCH_COSTING_AND_ESTIMATING_CART_SUCCESS';
export const FETCH_COSTING_AND_ESTIMATING_CART_FAILURE =
    'FETCH_COSTING_AND_ESTIMATING_CART_FAILURE';
