export const FETCH_CREDIT_LOGS_REQUEST = 'FETCH_CREDIT_LOGS_REQUEST';
export const FETCH_CREDIT_LOGS_SUCCESS = 'FETCH_CREDIT_LOGS_SUCCESS';
export const FETCH_CREDIT_LOGS_FAILURE = 'FETCH_CREDIT_LOGS_FAILURE';
