export const FETCH_CREDITS_REQUEST = 'FETCH_CREDITS_REQUEST';
export const FETCH_CREDITS_SUCCESS = 'FETCH_CREDITS_SUCCESS';
export const FETCH_CREDITS_FAILURE = 'FETCH_CREDITS_FAILURE';

export const CREATE_CREDITS_REQUEST = 'CREATE_CREDITS_REQUEST';
export const CREATE_CREDITS_SUCCESS = 'CREATE_CREDITS_SUCCESS';
export const CREATE_CREDITS_FAILURE = 'CREATE_CREDITS_FAILURE';

export const FETCH_COST_OF_CREDITS_REQUEST = 'FETCH_COST_OF_CREDITS_REQUEST';
export const FETCH_COST_OF_CREDITS_SUCCESS = 'FETCH_COST_OF_CREDITS_SUCCESS';
export const FETCH_COST_OF_CREDITS_FAILURE = 'FETCH_COST_OF_CREDITS_FAILURE';

export const ADD_CREDITS_TO_DRAWING_REQUEST = 'ADD_CREDITS_TO_DRAWING_REQUEST';
export const ADD_CREDITS_TO_DRAWING_SUCCESS = 'ADD_CREDITS_TO_DRAWING_SUCCESS';
export const ADD_CREDITS_TO_DRAWING_FAILURE = 'ADD_CREDITS_TO_DRAWING_FAILURE';
