export const FETCH_LIVE_HISTORIES_REQUEST = 'FETCH_LIVE_HISTORIES_REQUEST';
export const FETCH_LIVE_HISTORIES_SUCCESS = 'FETCH_LIVE_HISTORIES_SUCCESS';
export const FETCH_LIVE_HISTORIES_FAILURE = 'FETCH_LIVE_HISTORIES_FAILURE';

export const FETCH_HISTORY_FEED_REQUEST = 'FETCH_HISTORY_FEED_REQUEST';
export const FETCH_HISTORY_FEED_SUCCESS = 'FETCH_HISTORY_FEED_SUCCESS';
export const FETCH_HISTORY_FEED_FAILURE = 'FETCH_HISTORY_FEED_FAILURE';

export const UPDATE_DASHBOARD_SETTING = 'UPDATE_DASHBOARD_SETTING';

export const FETCH_DASH_STATS_REQUEST = 'FETCH_DASH_STATS_REQUEST';
export const FETCH_DASH_STATS_SUCCESS = 'FETCH_DASH_STATS_SUCCESS';
export const FETCH_DASH_STATS_FAILURE = 'FETCH_DASH_STATS_FAILURE';

export const FETCH_DASH_PIN_STATUS_STATS_REQUEST =
    'FETCH_DASH_PIN_STATUS_STATS_REQUEST';
export const FETCH_DASH_PIN_STATUS_STATS_SUCCESS =
    'FETCH_DASH_PIN_STATUS_STATS_SUCCESS';
export const FETCH_DASH_PIN_STATUS_STATS_FAILURE =
    'FETCH_DASH_PIN_STATUS_STATS_FAILURE';

export const UPDATE_DASH_STATS_FILTERS = 'UPDATE_DASH_STATS_FILTERS';
