export const FETCH_RECENTLY_DELETED_REQUEST = 'FETCH_RECENTLY_DELETED_REQUEST';
export const FETCH_RECENTLY_DELETED_SUCCESS = 'FETCH_RECENTLY_DELETED_SUCCESS';
export const FETCH_RECENTLY_DELETED_FAILURE = 'FETCH_RECENTLY_DELETED_FAILURE';

export const RESTORE_RECENTLY_DELETED_REQUEST = 'RESTORE_RECENTLY_DELETED_REQUEST';
export const RESTORE_RECENTLY_DELETED_SUCCESS = 'RESTORE_RECENTLY_DELETED_SUCCESS';
export const RESTORE_RECENTLY_DELETED_FAILURE = 'RESTORE_RECENTLY_DELETED_FAILURE';
