export const FETCH_DELETED_DRAWINGS_REQUEST = 'FETCH_DELETED_DRAWINGS_REQUEST';
export const FETCH_DELETED_DRAWINGS_SUCCESS = 'FETCH_DELETED_DRAWINGS_SUCCESS';
export const FETCH_DELETED_DRAWINGS_FAILURE = 'FETCH_DELETED_DRAWINGS_FAILURE';

export const FETCH_DELETED_PIN_HISTORIES_REQUEST = 'FETCH_DELETED_PIN_HISTORIES_REQUEST';
export const FETCH_DELETED_PIN_HISTORIES_SUCCESS = 'FETCH_DELETED_PIN_HISTORIES_SUCCESS';
export const FETCH_DELETED_PIN_HISTORIES_FAILURE = 'FETCH_DELETED_PIN_HISTORIES_FAILURE';

export const RESTORE_DRAWING_REQUEST = 'RESTORE_DRAWING_REQUEST';
export const RESTORE_DRAWING_SUCCESS = 'RESTORE_DRAWING_SUCCESS';
export const RESTORE_DRAWING_FAILURE = 'RESTORE_DRAWING_FAILURE';

export const RESTORE_PIN_HISTORY_REQUEST = 'RESTORE_PIN_HISTORY_REQUEST';
export const RESTORE_PIN_HISTORY_SUCCESS = 'RESTORE_PIN_HISTORY_SUCCESS';
export const RESTORE_PIN_HISTORY_FAILURE = 'RESTORE_PIN_HISTORY_FAILURE';
