export const FETCH_ALL_DEMO_ACCESS_CODES_REQUEST = 'FETCH_ALL_DEMO_ACCESS_CODES_REQUEST';
export const FETCH_ALL_DEMO_ACCESS_CODES_SUCCESS = 'FETCH_ALL_DEMO_ACCESS_CODES_SUCCESS';
export const FETCH_ALL_DEMO_ACCESS_CODES_FAILURE = 'FETCH_ALL_DEMO_ACCESS_CODES_FAILURE';

export const UPDATE_DEMO_ACCESS_CODES_REQUEST = 'UPDATE_DEMO_ACCESS_CODES_REQUEST';
export const UPDATE_DEMO_ACCESS_CODES_SUCCESS = 'UPDATE_DEMO_ACCESS_CODES_SUCCESS';
export const UPDATE_DEMO_ACCESS_CODES_FAILURE = 'UPDATE_DEMO_ACCESS_CODES_FAILURE';

export const POST_DEMO_ACCESS_CODES_REQUEST = 'POST_DEMO_ACCESS_CODES_REQUEST';
export const POST_DEMO_ACCESS_CODES_SUCCESS = 'POST_DEMO_ACCESS_CODES_SUCCESS';
export const POST_DEMO_ACCESS_CODES_FAILURE = 'POST_DEMO_ACCESS_CODES_FAILURE';

export const DELETE_DEMO_ACCESS_CODES_REQUEST = 'DELETE_DEMO_ACCESS_CODES_REQUEST';
export const DELETE_DEMO_ACCESS_CODES_SUCCESS = 'DELETE_DEMO_ACCESS_CODES_SUCCESS';
export const DELETE_DEMO_ACCESS_CODES_FAILURE = 'DELETE_DEMO_ACCESS_CODES_FAILURE';

export const DISABLE_DEMO_ACCESS_CODES_REQUEST = 'DISABLE_DEMO_ACCESS_CODES_REQUEST';
export const DISABLE_DEMO_ACCESS_CODES_SUCCESS = 'DISABLE_DEMO_ACCESS_CODES_SUCCESS';
export const DISABLE_DEMO_ACCESS_CODES_FAILURE = 'DISABLE_DEMO_ACCESS_CODES_FAILURE';

export const ENABLE_DEMO_ACCESS_CODES_REQUEST = 'ENABLE_DEMO_ACCESS_CODES_REQUEST';
export const ENABLE_DEMO_ACCESS_CODES_SUCCESS = 'ENABLE_DEMO_ACCESS_CODES_SUCCESS';
export const ENABLE_DEMO_ACCESS_CODES_FAILURE = 'ENABLE_DEMO_ACCESS_CODES_FAILURE';

export const POST_DEMO_FULL_SITE_REQUEST = 'POST_DEMO_FULL_SITE_REQUEST';
export const POST_DEMO_FULL_SITE_SUCCESS = 'POST_DEMO_FULL_SITE_SUCCESS';
export const POST_DEMO_FULL_SITE_FAILURE = 'POST_DEMO_FULL_SITE_FAILURE';
