export const FETCH_ALL_DEMO_REQUESTS_REQUEST =
    'FETCH_ALL_DEMO_REQUESTS_REQUEST';
export const FETCH_ALL_DEMO_REQUESTS_SUCCESS =
    'FETCH_ALL_DEMO_REQUESTS_SUCCESS';
export const FETCH_ALL_DEMO_REQUESTS_FAILURE =
    'FETCH_ALL_DEMO_REQUESTS_FAILURE';

export const DELETE_DEMO_REQUEST_REQUEST = 'DELETE_DEMO_REQUEST_REQUEST';
export const DELETE_DEMO_REQUEST_SUCCESS = 'DELETE_DEMO_REQUEST_SUCCESS';
export const DELETE_DEMO_REQUEST_FAILURE = 'DELETE_DEMO_REQUEST_FAILURE';
