export const FETCH_DOCUMENTS_REQUEST = 'FETCH_DOCUMENTS_REQUEST';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';

export const FETCH_SINGLE_DOCUMENT_REQUEST = 'FETCH_SINGLE_DOCUMENT_REQUEST';
export const FETCH_SINGLE_DOCUMENT_SUCCESS = 'FETCH_SINGLE_DOCUMENT_SUCCESS';
export const FETCH_SINGLE_DOCUMENT_FAILURE = 'FETCH_SINGLE_DOCUMENT_FAILURE';

export const CREATE_DOCUMENT_REQUEST = 'CREATE_DOCUMENT_REQUEST';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_FAILURE = 'CREATE_DOCUMENT_FAILURE';

export const EDIT_DOCUMENT_REQUEST = 'EDIT_DOCUMENT_REQUEST';
export const EDIT_DOCUMENT_SUCCESS = 'EDIT_DOCUMENT_SUCCESS';
export const EDIT_DOCUMENT_FAILURE = 'EDIT_DOCUMENT_FAILURE';

export const DELETE_DOCUMENT_REQUEST = 'DELETE_DOCUMENT_REQUEST';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'DELETE_DOCUMENT_FAILURE';

export const FETCH_DOCUMENT_RESPONSES_REQUEST =
    'FETCH_DOCUMENT_RESPONSES_REQUEST';
export const FETCH_DOCUMENT_RESPONSES_SUCCESS =
    'FETCH_DOCUMENT_RESPONSES_SUCCESS';
export const FETCH_DOCUMENT_RESPONSES_FAILURE =
    'FETCH_DOCUMENT_RESPONSES_FAILURE';
