export const SEARCH_ALL_LIBRARY_DOCUMENTS_REQUEST = 'SEARCH_ALL_LIBRARY_DOCUMENTS_REQUEST';
export const SEARCH_ALL_LIBRARY_DOCUMENTS_SUCCESS = 'SEARCH_ALL_LIBRARY_DOCUMENTS_SUCCESS';
export const SEARCH_ALL_LIBRARY_DOCUMENTS_FAILURE = 'SEARCH_ALL_LIBRARY_DOCUMENTS_FAILURE';

export const FETCH_DOCUMENT_LIBRARY_FILES_FOR_COMPANY_REQUEST =
    'FETCH_DOCUMENT_LIBRARY_FILES_FOR_COMPANY_REQUEST';
export const FETCH_DOCUMENT_LIBRARY_FILES_FOR_COMPANY_SUCCESS =
    'FETCH_DOCUMENT_LIBRARY_FILES_FOR_COMPANY_SUCCESS';
export const FETCH_DOCUMENT_LIBRARY_FILES_FOR_COMPANY_FAILURE =
    'FETCH_DOCUMENT_LIBRARY_FILES_FOR_COMPANY_FAILURE';

export const FETCH_SINGLE_LIBRARY_DOCUMENT_REQUEST = 'FETCH_SINGLE_LIBRARY_DOCUMENT_REQUEST';
export const FETCH_SINGLE_LIBRARY_DOCUMENT_SUCCESS = 'FETCH_SINGLE_LIBRARY_DOCUMENT_SUCCESS';
export const FETCH_SINGLE_LIBRARY_DOCUMENT_FAILURE = 'FETCH_SINGLE_LIBRARY_DOCUMENT_FAILURE';

export const MOVE_LIBRARY_DOCUMENT_REQUEST = 'MOVE_LIBRARY_DOCUMENT_REQUEST';
export const MOVE_LIBRARY_DOCUMENT_SUCCESS = 'MOVE_LIBRARY_DOCUMENT_SUCCESS';
export const MOVE_LIBRARY_DOCUMENT_FAILURE = 'MOVE_LIBRARY_DOCUMENT_FAILURE';

export const SOFT_DELETE_LIBRARY_DOCUMENT_REQUEST = 'SOFT_DELETE_LIBRARY_DOCUMENT_REQUEST';
export const SOFT_DELETE_LIBRARY_DOCUMENT_SUCCESS = 'SOFT_DELETE_LIBRARY_DOCUMENT_SUCCESS';
export const SOFT_DELETE_LIBRARY_DOCUMENT_FAILURE = 'SOFT_DELETE_LIBRARY_DOCUMENT_FAILURE';

export const HARD_DELETE_LIBRARY_DOCUMENT_REQUEST = 'HARD_DELETE_LIBRARY_DOCUMENT_REQUEST';
export const HARD_DELETE_LIBRARY_DOCUMENT_SUCCESS = 'HARD_DELETE_LIBRARY_DOCUMENT_SUCCESS';
export const HARD_DELETE_LIBRARY_DOCUMENT_FAILURE = 'HARD_DELETE_LIBRARY_DOCUMENT_FAILURE';

export const CREATE_LIBRARY_DOCUMENT_FOLDER_REQUEST = 'CREATE_LIBRARY_DOCUMENT_FOLDER_REQUEST';
export const CREATE_LIBRARY_DOCUMENT_FOLDER_SUCCESS = 'CREATE_LIBRARY_DOCUMENT_FOLDER_SUCCESS';
export const CREATE_LIBRARY_DOCUMENT_FOLDER_FAILURE = 'CREATE_LIBRARY_DOCUMENT_FOLDER_FAILURE';

export const SWITCH_DOCUMENT_LIBRARY_VIEW = 'SWITCH_DOCUMENT_LIBRARY_VIEW';

export const SWITCH_DOCUMENT_LIBRARY_PAGE_SIZE = 'SWITCH_DOCUMENT_LIBRARY_PAGE_SIZE';
export const SWITCH_DOCUMENT_LIBRARY_PAGE = 'SWITCH_DOCUMENT_LIBRARY_PAGE';
export const ADD_DOCUMENT_LIBRARY_ITEM = 'ADD_DOCUMENT_LIBRARY_ITEM';

export const SWITCH_DOCUMENT_LIBRARY_FILTER = 'SWITCH_DOCUMENT_LIBRARY_FILTER';

export const SWITCH_DOCUMENT_LIBRARY_SEARCH_TERM = 'SWITCH_DOCUMENT_LIBRARY_SEARCH_TERM';
