export const FETCH_ALL_LIBRARY_DOCUMENTS_REQUEST = 'FETCH_ALL_LIBRARY_DOCUMENTS_REQUEST';
export const FETCH_ALL_LIBRARY_DOCUMENTS_SUCCESS = 'FETCH_ALL_LIBRARY_DOCUMENTS_SUCCESS';
export const FETCH_ALL_LIBRARY_DOCUMENTS_FAILURE = 'FETCH_ALL_LIBRARY_DOCUMENTS_FAILURE';

export const FETCH_SINGLE_LIBRARY_DOCUMENT_REQUEST = 'FETCH_SINGLE_LIBRARY_DOCUMENT_REQUEST';
export const FETCH_SINGLE_LIBRARY_DOCUMENT_SUCCESS = 'FETCH_SINGLE_LIBRARY_DOCUMENT_SUCCESS';
export const FETCH_SINGLE_LIBRARY_DOCUMENT_FAILURE = 'FETCH_SINGLE_LIBRARY_DOCUMENT_FAILURE';

export const MOVE_LIBRARY_DOCUMENT_REQUEST = 'MOVE_LIBRARY_DOCUMENT_REQUEST';
export const MOVE_LIBRARY_DOCUMENT_SUCCESS = 'MOVE_LIBRARY_DOCUMENT_SUCCESS';
export const MOVE_LIBRARY_DOCUMENT_FAILURE = 'MOVE_LIBRARY_DOCUMENT_FAILURE';

export const SOFT_DELETE_LIBRARY_DOCUMENT_REQUEST = 'SOFT_DELETE_LIBRARY_DOCUMENT_REQUEST';
export const SOFT_DELETE_LIBRARY_DOCUMENT_SUCCESS = 'SOFT_DELETE_LIBRARY_DOCUMENT_SUCCESS';
export const SOFT_DELETE_LIBRARY_DOCUMENT_FAILURE = 'SOFT_DELETE_LIBRARY_DOCUMENT_FAILURE';

export const HARD_DELETE_LIBRARY_DOCUMENT_REQUEST = 'HARD_DELETE_LIBRARY_DOCUMENT_REQUEST';
export const HARD_DELETE_LIBRARY_DOCUMENT_SUCCESS = 'HARD_DELETE_LIBRARY_DOCUMENT_SUCCESS';
export const HARD_DELETE_LIBRARY_DOCUMENT_FAILURE = 'HARD_DELETE_LIBRARY_DOCUMENT_FAILURE';

export const CREATE_LIBRARY_DOCUMENT_REQUEST = 'CREATE_LIBRARY_DOCUMENT_REQUEST';
export const CREATE_LIBRARY_DOCUMENT_SUCCESS = 'CREATE_LIBRARY_DOCUMENT_SUCCESS';
export const CREATE_LIBRARY_DOCUMENT_FAILURE = 'CREATE_LIBRARY_DOCUMENT_FAILURE';

export const SWITCH_DOCUMENT_LIBRARY_VIEW = 'SWITCH_DOCUMENT_LIBRARY_VIEW';

export const SWITCH_DOCUMENT_LIBRARY_PAGE_SIZE = 'SWITCH_DOCUMENT_LIBRARY_PAGE_SIZE';
export const SWITCH_DOCUMENT_LIBRARY_PAGE = 'SWITCH_DOCUMENT_LIBRARY_PAGE';
