export const FETCH_ALL_DRAWINGS_REQUEST = 'FETCH_ALL_DRAWINGS_REQUEST';
export const FETCH_ALL_DRAWINGS_SUCCESS = 'FETCH_ALL_DRAWINGS_SUCCESS';
export const FETCH_ALL_DRAWINGS_FAILURE = 'FETCH_ALL_DRAWINGS_FAILURE';

export const FETCH_DRAWING_INSPECTION_LOGS_REQUEST =
    'FETCH_DRAWING_INSPECTION_LOGS_REQUEST';
export const FETCH_DRAWING_INSPECTION_LOGS_SUCCESS =
    'FETCH_DRAWING_INSPECTION_LOGS_SUCCESS';
export const FETCH_DRAWING_INSPECTION_LOGS_FAILURE =
    'FETCH_DRAWING_INSPECTION_LOGS_FAILURE';
