export const UPDATE_ADD_PIN_ANSWER = 'UPDATE_ADD_PIN_ANSWER';
export const UPDATE_ADD_PIN_STATUS = 'UPDATE_ADD_PIN_STATUS';
export const RESET_PIN_ANSWERS = 'RESET_PIN_ANSWERS';

export const UPDATE_PIN_COORDINATES = 'UPDATE_PIN_COORDINATES';

export const FETCH_ALL_DRAWINGS_REQUEST = 'FETCH_ALL_DRAWINGS_REQUEST';
export const FETCH_ALL_DRAWINGS_SUCCESS = 'FETCH_ALL_DRAWINGS_SUCCESS';
export const FETCH_ALL_DRAWINGS_FAILURE = 'FETCH_ALL_DRAWINGS_FAILURE';

export const FETCH_SINGLE_DRAWING_REQUEST = 'FETCH_SINGLE_DRAWING_REQUEST';
export const FETCH_SINGLE_DRAWING_SUCCESS = 'FETCH_SINGLE_DRAWING_SUCCESS';
export const FETCH_SINGLE_DRAWING_FAILURE = 'FETCH_SINGLE_DRAWING_FAILURE';

export const CREATE_DRAWING_REQUEST = 'CREATE_DRAWING_REQUEST';
export const CREATE_DRAWING_SUCCESS = 'CREATE_DRAWING_SUCCESS';
export const CREATE_DRAWING_FAILURE = 'CREATE_DRAWING_FAILURE';

export const DELETE_DRAWING_REQUEST = 'DELETE_DRAWING_REQUEST';
export const DELETE_DRAWING_SUCCESS = 'DELETE_DRAWING_SUCCESS';
export const DELETE_DRAWING_FAILURE = 'DELETE_DRAWING_FAILURE';

export const ARCHIVE_DRAWING_REQUEST = 'ARCHIVE_DRAWING_REQUEST';
export const ARCHIVE_DRAWING_SUCCESS = 'ARCHIVE_DRAWING_SUCCESS';
export const ARCHIVE_DRAWING_FAILURE = 'ARCHIVE_DRAWING_FAILURE';

export const UPDATE_FLOOR_PLAN_REQUEST = 'UPDATE_FLOOR_PLAN_REQUEST';
export const UPDATE_FLOOR_PLAN_SUCCESS = 'UPDATE_FLOOR_PLAN_SUCCESS';
export const UPDATE_FLOOR_PLAN_FAILURE = 'UPDATE_FLOOR_PLAN_FAILURE';

export const FETCH_DRAWING_INSPECTION_LOGS_REQUEST =
    'FETCH_DRAWING_INSPECTION_LOGS_REQUEST';
export const FETCH_DRAWING_INSPECTION_LOGS_SUCCESS =
    'FETCH_DRAWING_INSPECTION_LOGS_SUCCESS';
export const FETCH_DRAWING_INSPECTION_LOGS_FAILURE =
    'FETCH_DRAWING_INSPECTION_LOGS_FAILURE';

export const FETCH_DRAWING_TEMPLATES_REQUEST =
    'FETCH_DRAWING_TEMPLATES_REQUEST';
export const FETCH_DRAWING_TEMPLATES_SUCCESS =
    'FETCH_DRAWING_TEMPLATES_SUCCESS';
export const FETCH_DRAWING_TEMPLATES_FAILURE =
    'FETCH_DRAWING_TEMPLATES_FAILURE';

export const FETCH_DRAWING_DROPDOWN_OPTIONS_REQUEST =
    'FETCH_DRAWING_DROPDOWN_OPTIONS_REQUEST';
export const FETCH_DRAWING_DROPDOWN_OPTIONS_SUCCESS =
    'FETCH_DRAWING_DROPDOWN_OPTIONS_SUCCESS';
export const FETCH_DRAWING_DROPDOWN_OPTIONS_FAILURE =
    'FETCH_DRAWING_DROPDOWN_OPTIONS_FAILURE';
