export const FETCH_ALL_DROPDOWN_OPTIONS_REQUEST =
    'FETCH_ALL_DROPDOWN_OPTIONS_REQUEST';
export const FETCH_ALL_DROPDOWN_OPTIONS_SUCCESS =
    'FETCH_ALL_DROPDOWN_OPTIONS_SUCCESS';
export const FETCH_ALL_DROPDOWN_OPTIONS_FAILURE =
    'FETCH_ALL_DROPDOWN_OPTIONS_FAILURE';

export const CREATE_DROPDOWN_OPTION_REQUEST = 'CREATE_DROPDOWN_OPTION_REQUEST';
export const CREATE_DROPDOWN_OPTION_SUCCESS = 'CREATE_DROPDOWN_OPTION_SUCCESS';
export const CREATE_DROPDOWN_OPTION_FAILURE = 'CREATE_DROPDOWN_OPTION_FAILURE';
