export const FETCH_ALL_DROPDOWN_OPTIONS_REQUEST =
    'FETCH_ALL_DROPDOWN_OPTIONS_REQUEST';
export const FETCH_ALL_DROPDOWN_OPTIONS_SUCCESS =
    'FETCH_ALL_DROPDOWN_OPTIONS_SUCCESS';
export const FETCH_ALL_DROPDOWN_OPTIONS_FAILURE =
    'FETCH_ALL_DROPDOWN_OPTIONS_FAILURE';
