export const FETCH_ALL_DROPDOWN_OPTIONS_REQUEST = 'FETCH_ALL_DROPDOWN_OPTIONS_REQUEST';
export const FETCH_ALL_DROPDOWN_OPTIONS_SUCCESS = 'FETCH_ALL_DROPDOWN_OPTIONS_SUCCESS';
export const FETCH_ALL_DROPDOWN_OPTIONS_FAILURE = 'FETCH_ALL_DROPDOWN_OPTIONS_FAILURE';

export const CREATE_DROPDOWN_OPTION_REQUEST = 'CREATE_DROPDOWN_OPTION_REQUEST';
export const CREATE_DROPDOWN_OPTION_SUCCESS = 'CREATE_DROPDOWN_OPTION_SUCCESS';
export const CREATE_DROPDOWN_OPTION_FAILURE = 'CREATE_DROPDOWN_OPTION_FAILURE';

export const EDIT_DROPDOWN_OPTION_REQUEST = 'EDIT_DROPDOWN_OPTION_REQUEST';
export const EDIT_DROPDOWN_OPTION_SUCCESS = 'EDIT_DROPDOWN_OPTION_SUCCESS';
export const EDIT_DROPDOWN_OPTION_FAILURE = 'EDIT_DROPDOWN_OPTION_FAILURE';

export const DELETE_DROPDOWN_OPTION_REQUEST = 'DELETE_DROPDOWN_OPTION_REQUEST';
export const DELETE_DROPDOWN_OPTION_SUCCESS = 'DELETE_DROPDOWN_OPTION_SUCCESS';
export const DELETE_DROPDOWN_OPTION_FAILURE = 'DELETE_DROPDOWN_OPTION_FAILURE';

export const TOGGLE_DROPDOWN_OPTION_REQUEST = 'TOGGLE_DROPDOWN_OPTION_REQUEST';
export const TOGGLE_DROPDOWN_OPTION_SUCCESS = 'TOGGLE_DROPDOWN_OPTION_SUCCESS';
export const TOGGLE_DROPDOWN_OPTION_FAILURE = 'TOGGLE_DROPDOWN_OPTION_FAILURE';

export const REORDER_DROPDOWN_OPTIONS = 'REORDER_DROPDOWN_OPTIONS';
export const POST_DROPDOWN_OPTIONS_SORT = 'POST_DROPDOWN_OPTIONS_SORT';

export const REORDER_MANUFACTURERS = 'REORDER_MANUFACTURERS';
export const POST_MANUFACTURERS_SORT = 'POST_MANUFACTURERS_SORT';

export const REORDER_MANUFACTURER_OPTION_VALUES = 'REORDER_MANUFACTURER_OPTION_VALUES';
export const POST_MANUFACTURER_OPTION_VALUES_SORT = 'POST_MANUFACTURER_OPTION_VALUES_SORT';

export const FETCH_SINGLE_SITE_DROPDOWN_OPTIONS_REQUEST =
    'FETCH_SINGLE_SITE_DROPDOWN_OPTIONS_REQUEST';
export const FETCH_SINGLE_SITE_DROPDOWN_OPTIONS_SUCCESS =
    'FETCH_SINGLE_SITE_DROPDOWN_OPTIONS_SUCCESS';
export const FETCH_SINGLE_SITE_DROPDOWN_OPTIONS_FAILURE =
    'FETCH_SINGLE_SITE_DROPDOWN_OPTIONS_FAILURE';
