export const FETCH_ALL_ENQUIRIES_REQUEST = 'FETCH_ALL_ENQUIRIES_REQUEST';
export const FETCH_ALL_ENQUIRIES_SUCCESS = 'FETCH_ALL_ENQUIRIES_SUCCESS';
export const FETCH_ALL_ENQUIRIES_FAILURE = 'FETCH_ALL_ENQUIRIES_FAILURE';

export const DELETE_ENQUIRY_REQUEST = 'DELETE_ENQUIRY_REQUEST';
export const DELETE_ENQUIRY_SUCCESS = 'DELETE_ENQUIRY_SUCCESS';
export const DELETE_ENQUIRY_FAILURE = 'DELETE_ENQUIRY_FAILURE';
