export const FETCH_ALL_ENQUIRIES_REQUEST = 'FETCH_ALL_ENQUIRIES_REQUEST';
export const FETCH_ALL_ENQUIRIES_SUCCESS = 'FETCH_ALL_ENQUIRIES_SUCCESS';
export const FETCH_ALL_ENQUIRIES_FAILURE = 'FETCH_ALL_ENQUIRIES_FAILURE';
