export const SHOW_FAQs_BUTTON = 'SHOW_FAQs_BUTTON';

export const FETCH_ALL_FAQS_REQUEST = 'FETCH_ALL_FAQS_REQUEST';
export const FETCH_ALL_FAQS_SUCCESS = 'FETCH_ALL_FAQS_SUCCESS';
export const FETCH_ALL_FAQS_FAILURE = 'FETCH_ALL_FAQS_FAILURE';

export const FETCH_SINGLE_FAQS_REQUEST = 'FETCH_SINGLE_FAQS_REQUEST';
export const FETCH_SINGLE_FAQS_SUCCESS = 'FETCH_SINGLE_FAQS_SUCCESS';
export const FETCH_SINGLE_FAQS_FAILURE = 'FETCH_SINGLE_FAQS_FAILURE';

export const CREATE_FAQS_REQUEST = 'CREATE_FAQS_REQUEST';
export const CREATE_FAQS_SUCCESS = 'CREATE_FAQS_SUCCESS';
export const CREATE_FAQS_FAILURE = 'CREATE_FAQS_FAILURE';
