export const FETCH_ALL_FLOORS_REQUEST = 'FETCH_ALL_FLOORS_REQUEST';
export const FETCH_ALL_FLOORS_SUCCESS = 'FETCH_ALL_FLOORS_SUCCESS';
export const FETCH_ALL_FLOORS_FAILURE = 'FETCH_ALL_FLOORS_FAILURE';
