export const FETCH_ALL_FLOORS_REQUEST = 'FETCH_ALL_FLOORS_REQUEST';
export const FETCH_ALL_FLOORS_SUCCESS = 'FETCH_ALL_FLOORS_SUCCESS';
export const FETCH_ALL_FLOORS_FAILURE = 'FETCH_ALL_FLOORS_FAILURE';

export const CREATE_FLOOR_REQUEST = 'CREATE_FLOOR_REQUEST';
export const CREATE_FLOOR_SUCCESS = 'CREATE_FLOOR_SUCCESS';
export const CREATE_FLOOR_FAILURE = 'CREATE_FLOOR_FAILURE';
