export const FETCH_ALL_FLOORS_REQUEST = 'FETCH_ALL_FLOORS_REQUEST';
export const FETCH_ALL_FLOORS_SUCCESS = 'FETCH_ALL_FLOORS_SUCCESS';
export const FETCH_ALL_FLOORS_FAILURE = 'FETCH_ALL_FLOORS_FAILURE';

export const REORDER_FLOORS = 'REORDER_FLOORS';
export const POST_FLOORS_SORT = 'POST_FLOORS_SORT';
export const POST_DRAWINGS_SORT = 'POST_DRAWINGS_SORT';

export const CREATE_FLOOR_REQUEST = 'CREATE_FLOOR_REQUEST';
export const CREATE_FLOOR_SUCCESS = 'CREATE_FLOOR_SUCCESS';
export const CREATE_FLOOR_FAILURE = 'CREATE_FLOOR_FAILURE';

export const CREATE_FLOORS_REQUEST = 'CREATE_FLOORS_REQUEST';
export const CREATE_FLOORS_SUCCESS = 'CREATE_FLOORS_SUCCESS';
export const CREATE_FLOORS_FAILURE = 'CREATE_FLOORS_FAILURE';

export const FETCH_SINGLE_FLOOR_REQUEST = 'FETCH_SINGLE_FLOOR_REQUEST';
export const FETCH_SINGLE_FLOOR_SUCCESS = 'FETCH_SINGLE_FLOOR_SUCCESS';
export const FETCH_SINGLE_FLOOR_FAILURE = 'FETCH_SINGLE_FLOOR_FAILURE';

export const EDIT_FLOOR_REQUEST = 'EDIT_FLOOR_REQUEST';
export const EDIT_FLOOR_SUCCESS = 'EDIT_FLOOR_SUCCESS';
export const EDIT_FLOOR_FAILURE = 'EDIT_FLOOR_FAILURE';

export const DELETE_FLOOR_REQUEST = 'DELETE_FLOOR_REQUEST';
export const DELETE_FLOOR_SUCCESS = 'DELETE_FLOOR_SUCCESS';
export const DELETE_FLOOR_FAILURE = 'DELETE_FLOOR_FAILURE';

export const ARCHIVE_FLOOR_REQUEST = 'ARCHIVE_FLOOR_REQUEST';
export const ARCHIVE_FLOOR_SUCCESS = 'ARCHIVE_FLOOR_SUCCESS';
export const ARCHIVE_FLOOR_FAILURE = 'ARCHIVE_FLOOR_FAILURE';
