export const ADMIN_UPLOAD_TRUSTED_BY_REQUEST = 'ADMIN_UPLOAD_TRUSTED_BY_REQUEST';
export const ADMIN_UPLOAD_TRUSTED_BY_SUCCESS = 'ADMIN_UPLOAD_TRUSTED_BY_SUCCESS';
export const ADMIN_UPLOAD_TRUSTED_BY_FAILURE = 'ADMIN_UPLOAD_TRUSTED_BY_FAILURE';

export const ADMIN_DELETE_TRUSTED_BY_SUCCESS = 'ADMIN_DELETE_TRUSTED_BY_SUCCESS';
export const ADMIN_DELETE_TRUSTED_BY_REQUEST = 'ADMIN_DELETE_TRUSTED_BY_REQUEST';
export const ADMIN_DELETE_TRUSTED_BY_FAILURE = 'ADMIN_DELETE_TRUSTED_BY_FAILURE';

export const ADMIN_FETCH_TRUSTED_BY_REQUEST = 'ADMIN_FETCH_TRUSTED_BY_REQUEST';
export const ADMIN_FETCH_TRUSTED_BY_SUCCESS = 'ADMIN_FETCH_TRUSTED_BY_SUCCESS';
export const ADMIN_FETCH_TRUSTED_BY_FAILURE = 'ADMIN_FETCH_TRUSTED_BY_FAILURE';

export const FETCH_TRUSTED_BY_REQUEST = 'FETCH_TRUSTED_BY_REQUEST';
export const FETCH_TRUSTED_BY_SUCCESS = 'FETCH_TRUSTED_BY_SUCCESS';
export const FETCH_TRUSTED_BY_FAILURE = 'FETCH_TRUSTED_BY_FAILURE';
