export const ADMIN_FETCH_FRONTEND_TEXT_REQUEST = 'ADMIN_FETCH_FRONTEND_TEXT_REQUEST';
export const ADMIN_FETCH_FRONTEND_TEXT_SUCCESS = 'ADMIN_FETCH_FRONTEND_TEXT_SUCCESS';
export const ADMIN_FETCH_FRONTEND_TEXT_FAILURE = 'ADMIN_FETCH_FRONTEND_TEXT_FAILURE';

export const ADMIN_UPDATE_FRONTEND_TEXT_REQUEST = 'ADMIN_UPDATE_FRONTEND_TEXT_REQUEST';
export const ADMIN_UPDATE_FRONTEND_TEXT_SUCCESS = 'ADMIN_UPDATE_FRONTEND_TEXT_SUCCESS';
export const ADMIN_UPDATE_FRONTEND_TEXT_FAILURE = 'ADMIN_UPDATE_FRONTEND_TEXT_FAILURE';
