export const FETCH_GENERATION_QUEUE_REQUEST = 'FETCH_GENERATION_QUEUE_REQUEST';
export const FETCH_GENERATION_QUEUE_SUCCESS = 'FETCH_GENERATION_QUEUE_SUCCESS';
export const FETCH_GENERATION_QUEUE_FAILURE = 'FETCH_GENERATION_QUEUE_FAILURE';
