export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';

export const SET_TABS = 'SET_TABS';
export const SELECT_TAB = 'SELECT_TAB';

export const ADD_FIELD_ERROR = 'ADD_FIELD_ERROR';
export const REMOVE_FIELD_ERROR = 'REMOVE_FIELD_ERROR';
export const CLEAR_FIELD_ERRORS = 'CLEAR_FIELD_ERRORS';
export const SHOW_FIELD_ERRORS = 'SHOW_FIELD_ERRORS';
export const OVERWRITE_FIELD_ERRORS = 'OVERWRITE_FIELD_ERRORS';
