export const FETCH_ALL_HEADQUARTERS_COMPANIES_REQUEST =
    'FETCH_ALL_HEADQUARTERS_COMPANIES_REQUEST';
export const FETCH_ALL_HEADQUARTERS_COMPANIES_FAILURE =
    'FETCH_ALL_HEADQUARTERS_COMPANIES_FAILURE';
export const FETCH_ALL_HEADQUARTERS_COMPANIES_SUCCESS =
    'FETCH_ALL_HEADQUARTERS_COMPANIES_SUCCESS';
