export const FETCH_ALL_HEADQUARTERS_COMPANIES_REQUEST =
    'FETCH_ALL_HEADQUARTERS_COMPANIES_REQUEST';
export const FETCH_ALL_HEADQUARTERS_COMPANIES_FAILURE =
    'FETCH_ALL_HEADQUARTERS_COMPANIES_FAILURE';
export const FETCH_ALL_HEADQUARTERS_COMPANIES_SUCCESS =
    'FETCH_ALL_HEADQUARTERS_COMPANIES_SUCCESS';

export const CREATE_HEADQUARTERS_COMPANY_REQUEST =
    'CREATE_HEADQUARTERS_COMPANY_REQUEST';
export const CREATE_HEADQUARTERS_COMPANY_FAILURE =
    'CREATE_HEADQUARTERS_COMPANY_FAILURE';
export const CREATE_HEADQUARTERS_COMPANY_SUCCESS =
    'CREATE_HEADQUARTERS_COMPANY_SUCCESS';
