export const FETCH_ALL_INVOICES_REQUEST = 'FETCH_ALL_INVOICES_REQUEST';
export const FETCH_ALL_INVOICES_SUCCESS = 'FETCH_ALL_INVOICES_SUCCESS';
export const FETCH_ALL_INVOICES_FAILURE = 'FETCH_ALL_INVOICES_FAILURE';

export const FETCH_ALL_INVOICE_ITEMS_REQUEST =
    'FETCH_ALL_INVOICE_ITEMS_REQUEST';
export const FETCH_ALL_INVOICE_ITEMS_SUCCESS =
    'FETCH_ALL_INVOICE_ITEMS_SUCCESS';
export const FETCH_ALL_INVOICE_ITEMS_FAILURE =
    'FETCH_ALL_INVOICE_ITEMS_FAILURE';

export const FETCH_SINGLE_INVOICE_REQUEST = 'FETCH_SINGLE_INVOICE_REQUEST';
export const FETCH_SINGLE_INVOICE_SUCCESS = 'FETCH_SINGLE_INVOICE_SUCCESS';
export const FETCH_SINGLE_INVOICE_FAILURE = 'FETCH_SINGLE_INVOICE_FAILURE';

export const FETCH_SINGLE_INVOICE_ITEMS_REQUEST =
    'FETCH_SINGLE_INVOICE_ITEMS_REQUEST';
export const FETCH_SINGLE_INVOICE_ITEMS_SUCCESS =
    'FETCH_SINGLE_INVOICE_ITEMS_SUCCESS';
export const FETCH_SINGLE_INVOICE_ITEMS_FAILURE =
    'FETCH_SINGLE_INVOICE_ITEMS_FAILURE';

export const PAY_INVOICE_REQUEST = 'PAY_INVOICE_REQUEST';
export const PAY_INVOICE_SUCCESS = 'PAY_INVOICE_SUCCESS';
export const PAY_INVOICE_FAILURE = 'PAY_INVOICE_FAILURE';

export const ADMIN_FETCH_COMPANY_INVOICES_REQUEST =
    'ADMIN_FETCH_COMPANY_INVOICES_REQUEST';
export const ADMIN_FETCH_COMPANY_INVOICES_SUCCESS =
    'ADMIN_FETCH_COMPANY_INVOICES_SUCCESS';
export const ADMIN_FETCH_COMPANY_INVOICES_FAILURE =
    'ADMIN_FETCH_COMPANY_INVOICES_FAILURE';
