export const FETCH_ALL_INVOICES_REQUEST = 'FETCH_ALL_INVOICES_REQUEST';
export const FETCH_ALL_INVOICES_SUCCESS = 'FETCH_ALL_INVOICES_SUCCESS';
export const FETCH_ALL_INVOICES_FAILURE = 'FETCH_ALL_INVOICES_FAILURE';

export const FETCH_ALL_INVOICE_ITEMS_REQUEST =
    'FETCH_ALL_INVOICE_ITEMS_REQUEST';
export const FETCH_ALL_INVOICE_ITEMS_SUCCESS =
    'FETCH_ALL_INVOICE_ITEMS_SUCCESS';
export const FETCH_ALL_INVOICE_ITEMS_FAILURE =
    'FETCH_ALL_INVOICE_ITEMS_FAILURE';
