export const FETCH_JOB_REFERENCES_REQUEST = 'FETCH_JOB_REFERENCES_REQUEST';
export const FETCH_JOB_REFERENCES_SUCCESS = 'FETCH_JOB_REFERENCES_SUCCESS';
export const FETCH_JOB_REFERENCES_FAILURE = 'FETCH_JOB_REFERENCES_FAILURE';

export const CREATE_JOB_REFERENCE_REQUEST = 'CREATE_JOB_REFERENCE_REQUEST';
export const CREATE_JOB_REFERENCE_SUCCESS = 'CREATE_JOB_REFERENCE_SUCCESS';
export const CREATE_JOB_REFERENCE_FAILURE = 'CREATE_JOB_REFERENCE_FAILURE';

export const EDIT_JOB_REFERENCE_REQUEST = 'EDIT_JOB_REFERENCE_REQUEST';
export const EDIT_JOB_REFERENCE_SUCCESS = 'EDIT_JOB_REFERENCE_SUCCESS';
export const EDIT_JOB_REFERENCE_FAILURE = 'EDIT_JOB_REFERENCE_FAILURE';

export const DELETE_JOB_REFERENCE_REQUEST = 'DELETE_JOB_REFERENCE_REQUEST';
export const DELETE_JOB_REFERENCE_SUCCESS = 'DELETE_JOB_REFERENCE_SUCCESS';
export const DELETE_JOB_REFERENCE_FAILURE = 'DELETE_JOB_REFERENCE_FAILURE';
