export const FETCH_JOB_REFERENCES_REQUEST = 'FETCH_JOB_REFERENCES_REQUEST';
export const FETCH_JOB_REFERENCES_SUCCESS = 'FETCH_JOB_REFERENCES_SUCCESS';
export const FETCH_JOB_REFERENCES_FAILURE = 'FETCH_JOB_REFERENCES_FAILURE';

export const CREATE_JOB_REFERENCE_REQUEST = 'CREATE_JOB_REFERENCE_REQUEST';
export const CREATE_JOB_REFERENCE_SUCCESS = 'CREATE_JOB_REFERENCE_SUCCESS';
export const CREATE_JOB_REFERENCE_FAILURE = 'CREATE_JOB_REFERENCE_FAILURE';

export const EDIT_JOB_REFERENCE_REQUEST = 'EDIT_JOB_REFERENCE_REQUEST';
export const EDIT_JOB_REFERENCE_SUCCESS = 'EDIT_JOB_REFERENCE_SUCCESS';
export const EDIT_JOB_REFERENCE_FAILURE = 'EDIT_JOB_REFERENCE_FAILURE';

export const ENABLE_JOB_REFERENCE_REQUEST = 'ENABLE_JOB_REFERENCE_REQUEST';
export const ENABLE_JOB_REFERENCE_SUCCESS = 'ENABLE_JOB_REFERENCE_SUCCESS';
export const ENABLE_JOB_REFERENCE_FAILURE = 'ENABLE_JOB_REFERENCE_FAILURE';

export const DISABLE_JOB_REFERENCE_REQUEST = 'DISABLE_JOB_REFERENCE_REQUEST';
export const DISABLE_JOB_REFERENCE_SUCCESS = 'DISABLE_JOB_REFERENCE_SUCCESS';
export const DISABLE_JOB_REFERENCE_FAILURE = 'DISABLE_JOB_REFERENCE_FAILURE';
