export const COMPANY_FETCH_TERMS_REQUEST = 'COMPANY_FETCH_TERMS_REQUEST';
export const COMPANY_FETCH_TERMS_SUCCESS = 'COMPANY_FETCH_TERMS_SUCCESS';
export const COMPANY_FETCH_TERMS_FAILURE = 'COMPANY_FETCH_TERMS_FAILURE';

export const COMPANY_AGREE_TO_TERMS_REQUEST = 'COMPANY_AGREE_TO_TERMS_REQUEST';
export const COMPANY_AGREE_TO_TERMS_SUCCESS = 'COMPANY_AGREE_TO_TERMS_SUCCESS';
export const COMPANY_AGREE_TO_TERMS_FAILURE = 'COMPANY_AGREE_TO_TERMS_FAILURE';
