export const COMPANY_FETCH_TERMS_REQUEST = 'COMPANY_FETCH_TERMS_REQUEST';
export const COMPANY_FETCH_TERMS_SUCCESS = 'COMPANY_FETCH_TERMS_SUCCESS';
export const COMPANY_FETCH_TERMS_FAILURE = 'COMPANY_FETCH_TERMS_FAILURE';
export const FETCH_ALL_LEGAL_DOCUMENTS_REQUEST = 'FETCH_ALL_LEGAL_DOCUMENTS_REQUEST';
export const FETCH_ALL_LEGAL_DOCUMENTS_SUCCESS = 'FETCH_ALL_LEGAL_DOCUMENTS_SUCCESS';
export const FETCH_ALL_LEGAL_DOCUMENTS_FAILURE = 'FETCH_ALL_LEGAL_DOCUMENTS_FAILURE';

export const SHARED_FETCH_TERMS_REQUEST = 'SHARED_FETCH_TERMS_REQUEST';
export const SHARED_FETCH_TERMS_SUCCESS = 'SHARED_FETCH_TERMS_SUCCESS';
export const SHARED_FETCH_TERMS_FAILURE = 'SHARED_FETCH_TERMS_FAILURE';

export const COMPANY_AGREE_TO_TERMS_REQUEST = 'COMPANY_AGREE_TO_TERMS_REQUEST';
export const COMPANY_AGREE_TO_TERMS_SUCCESS = 'COMPANY_AGREE_TO_TERMS_SUCCESS';
export const COMPANY_AGREE_TO_TERMS_FAILURE = 'COMPANY_AGREE_TO_TERMS_FAILURE';

export const UPDATE_TERMS_CANCEL_COUNT_REQUEST = 'UPDATE_TERMS_CANCEL_COUNT_REQUEST';
export const UPDATE_TERMS_CANCEL_COUNT_SUCCESS = 'UPDATE_TERMS_CANCEL_COUNT_SUCCESS';
export const UPDATE_TERMS_CANCEL_COUNT_FAILURE = 'UPDATE_TERMS_CANCEL_COUNT_FAILURE';

export const UPDATE_LEGAL_DOCUMENT_REQUEST = 'UPDATE_LEGAL_DOCUMENT_REQUEST';
export const UPDATE_LEGAL_DOCUMENT_SUCCESS = 'UPDATE_LEGAL_DOCUMENT_SUCCESS';
export const UPDATE_LEGAL_DOCUMENT_FAILURE = 'UPDATE_LEGAL_DOCUMENT_FAILURE';
