export const ADMIN_MERGE_DRAWING_REQUEST = 'ADMIN_MERGE_DRAWING_REQUEST';
export const ADMIN_MERGE_DRAWING_SUCCESS = 'ADMIN_MERGE_DRAWING_SUCCESS';
export const ADMIN_MERGE_DRAWING_FAILURE = 'ADMIN_MERGE_DRAWING_FAILURE';
