// SYSTEM MESSAGES
export const FETCH_SYSTEM_MESSAGES_REQUEST = 'FETCH_SYSTEM_MESSAGES_REQUEST';
export const FETCH_SYSTEM_MESSAGES_SUCCESS = 'FETCH_SYSTEM_MESSAGES_SUCCESS';
export const FETCH_SYSTEM_MESSAGES_FAILURE = 'FETCH_SYSTEM_MESSAGES_FAILURE';

export const DISMISS_SYSTEM_MESSAGES_REQUEST = 'DISMISS_SYSTEM_MESSAGES_REQUEST';
export const DISMISS_SYSTEM_MESSAGES_SUCCESS = 'DISMISS_SYSTEM_MESSAGES_SUCCESS';
export const DISMISS_SYSTEM_MESSAGES_FAILURE = 'DISMISS_SYSTEM_MESSAGES_FAILURE';

export const POST_SYSTEM_MESSAGES_REQUEST = 'POST_SYSTEM_MESSAGES_REQUEST';
export const POST_SYSTEM_MESSAGES_SUCCESS = 'POST_SYSTEM_MESSAGES_SUCCESS';
export const POST_SYSTEM_MESSAGES_FAILURE = 'POST_SYSTEM_MESSAGES_FAILURE';

//SINGLE SYSTEM MESSAGE
export const POST_SYSTEM_MESSAGE_REQUEST = 'POST_SYSTEM_MESSAGE_REQUEST';
export const POST_SYSTEM_MESSAGE_SUCCESS = 'POST_SYSTEM_MESSAGE_SUCCESS';
export const POST_SYSTEM_MESSAGE_FAILURE = 'POST_SYSTEM_MESSAGE_FAILURE';

export const DISMISS_SYSTEM_MESSAGE_REQUEST = 'DISMISS_SYSTEM_MESSAGE_REQUEST';
export const DISMISS_SYSTEM_MESSAGE_SUCCESS = 'DISMISS_SYSTEM_MESSAGE_SUCCESS';
export const DISMISS_SYSTEM_MESSAGE_FAILURE = 'DISMISS_SYSTEM_MESSAGE_FAILURE';

// COMPANY ALERTS
export const FETCH_COMPANY_ALERTS_REQUEST = 'FETCH_COMPANY_ALERTS_REQUEST';
export const FETCH_COMPANY_ALERTS_SUCCESS = 'FETCH_COMPANY_ALERTS_SUCCESS';
export const FETCH_COMPANY_ALERTS_FAILURE = 'FETCH_COMPANY_ALERTS_FAILURE';

export const POST_COMPANY_ALERTS_REQUEST = 'POST_COMPANY_ALERTS_REQUEST';
export const POST_COMPANY_ALERTS_SUCCESS = 'POST_COMPANY_ALERTS_SUCCESS';
export const POST_COMPANY_ALERTS_FAILURE = 'POST_COMPANY_ALERTS_FAILURE';

export const DISMISS_COMPANY_ALERTS_REQUEST = 'DISMISS_COMPANY_ALERTS_REQUEST';
export const DISMISS_COMPANY_ALERTS_SUCCESS = 'DISMISS_COMPANY_ALERTS_SUCCESS';
export const DISMISS_COMPANY_ALERTS_FAILURE = 'DISMISS_COMPANY_ALERTS_FAILURE';

//SINGLE COMPANY ALERT
export const POST_COMPANY_ALERT_REQUEST = 'POST_COMPANY_ALERT_REQUEST';
export const POST_COMPANY_ALERT_SUCCESS = 'POST_COMPANY_ALERT_SUCCESS';
export const POST_COMPANY_ALERT_FAILURE = 'POST_COMPANY_ALERT_FAILURE';

export const DISMISS_COMPANY_ALERT_REQUEST = 'DISMISS_COMPANY_ALERT_REQUEST';
export const DISMISS_COMPANY_ALERT_SUCCESS = 'DISMISS_COMPANY_ALERT_SUCCESS';
export const DISMISS_COMPANY_ALERT_FAILURE = 'DISMISS_COMPANY_ALERT_FAILURE';

//OPERATIVE ALERTS
export const FETCH_OPERATIVE_ALERTS_REQUEST = 'FETCH_OPERATIVE_ALERTS_REQUEST';
export const FETCH_OPERATIVE_ALERTS_SUCCESS = 'FETCH_OPERATIVE_ALERTS_SUCCESS';
export const FETCH_OPERATIVE_ALERTS_FAILURE = 'FETCH_OPERATIVE_ALERTS_FAILURE';

export const POST_OPERATIVE_ALERTS_REQUEST = 'POST_OPERATIVE_ALERTS_REQUEST';
export const POST_OPERATIVE_ALERTS_SUCCESS = 'POST_OPERATIVE_ALERTS_SUCCESS';
export const POST_OPERATIVE_ALERTS_FAILURE = 'POST_OPERATIVE_ALERTS_FAILURE';

export const DISMISS_OPERATIVE_ALERTS_REQUEST = 'DISMISS_OPERATIVE_ALERTS_REQUEST';
export const DISMISS_OPERATIVE_ALERTS_SUCCESS = 'DISMISS_OPERATIVE_ALERTS_SUCCESS';
export const DISMISS_OPERATIVE_ALERTS_FAILURE = 'DISMISS_OPERATIVE_ALERTS_FAILURE';

//SINGLE OPERATIVE ALERT
export const POST_OPERATIVE_ALERT_REQUEST = 'POST_OPERATIVE_ALERT_REQUEST';
export const POST_OPERATIVE_ALERT_SUCCESS = 'POST_OPERATIVE_ALERT_SUCCESS';
export const POST_OPERATIVE_ALERT_FAILURE = 'POST_OPERATIVE_ALERT_FAILURE';

export const DISMISS_OPERATIVE_ALERT_REQUEST = 'DISMISS_OPERATIVE_ALERT_REQUEST';
export const DISMISS_OPERATIVE_ALERT_SUCCESS = 'DISMISS_OPERATIVE_ALERT_SUCCESS';
export const DISMISS_OPERATIVE_ALERT_FAILURE = 'DISMISS_OPERATIVE_ALERT_FAILURE';

//DRAWING EXPIRY
export const FETCH_DRAWING_EXPIRY_MESSAGES_REQUEST = 'FETCH_DRAWING_EXPIRY_MESSAGES_REQUEST';
export const FETCH_DRAWING_EXPIRY_MESSAGES_SUCCESS = 'FETCH_DRAWING_EXPIRY_MESSAGES_SUCCESS';
export const FETCH_DRAWING_EXPIRY_MESSAGES_FAILURE = 'FETCH_DRAWING_EXPIRY_MESSAGES_FAILURE';

export const POST_DRAWING_EXPIRY_MESSAGES_REQUEST = 'POST_DRAWING_EXPIRY_MESSAGES_REQUEST';
export const POST_DRAWING_EXPIRY_MESSAGES_SUCCESS = 'POST_DRAWING_EXPIRY_MESSAGES_SUCCESS';
export const POST_DRAWING_EXPIRY_MESSAGES_FAILURE = 'POST_DRAWING_EXPIRY_MESSAGES_FAILURE';

export const DISMISS_DRAWING_EXPIRY_MESSAGES_REQUEST = 'DISMISS_DRAWING_EXPIRY_MESSAGES_REQUEST';
export const DISMISS_DRAWING_EXPIRY_MESSAGES_SUCCESS = 'DISMISS_DRAWING_EXPIRY_MESSAGES_SUCCESS';
export const DISMISS_DRAWING_EXPIRY_MESSAGES_FAILURE = 'DISMISS_DRAWING_EXPIRY_MESSAGES_FAILURE';

//SINGLE OPERATIVE ALERT
export const POST_DRAWING_EXPIRY_MESSAGE_REQUEST = 'POST_DRAWING_EXPIRY_MESSAGE_REQUEST';
export const POST_DRAWING_EXPIRY_MESSAGE_SUCCESS = 'POST_DRAWING_EXPIRY_MESSAGE_SUCCESS';
export const POST_DRAWING_EXPIRY_MESSAGE_FAILURE = 'POST_DRAWING_EXPIRY_MESSAGE_FAILURE';

export const DISMISS_DRAWING_EXPIRY_MESSAGE_REQUEST = 'DISMISS_DRAWING_EXPIRY_MESSAGE_REQUEST';
export const DISMISS_DRAWING_EXPIRY_MESSAGE_SUCCESS = 'DISMISS_DRAWING_EXPIRY_MESSAGE_SUCCESS';
export const DISMISS_DRAWING_EXPIRY_MESSAGE_FAILURE = 'DISMISS_DRAWING_EXPIRY_MESSAGE_FAILURE';

//SELECTED TABS
export const SELECT_MESSAGE_CENTRE_TAB = 'SELECT_MESSAGE_CENTRE_TAB';
