// SYSTEM MESSAGES
export const FETCH_SYSTEM_MESSAGES_REQUEST = 'FETCH_SYSTEM_MESSAGES_REQUEST';
export const FETCH_SYSTEM_MESSAGES_SUCCESS = 'FETCH_SYSTEM_MESSAGES_SUCCESS';
export const FETCH_SYSTEM_MESSAGES_FAILURE = 'FETCH_SYSTEM_MESSAGES_FAILURE';

export const DISMISS_SYSTEM_MESSAGES_REQUEST = 'DISMISS_SYSTEM_MESSAGES_REQUEST';
export const DISMISS_SYSTEM_MESSAGES_SUCCESS = 'DISMISS_SYSTEM_MESSAGES_SUCCESS';
export const DISMISS_SYSTEM_MESSAGES_FAILURE = 'DISMISS_SYSTEM_MESSAGES_FAILURE';

// COMPANY ALERTS
export const FETCH_COMPANY_ALERTS_REQUEST = 'FETCH_COMPANY_ALERTS_REQUEST';
export const FETCH_COMPANY_ALERTS_SUCCESS = 'FETCH_COMPANY_ALERTS_SUCCESS';
export const FETCH_COMPANY_ALERTS_FAILURE = 'FETCH_COMPANY_ALERTS_FAILURE';

export const POST_COMPANY_ALERTS_REQUEST = 'POST_COMPANY_ALERTS_REQUEST';
export const POST_COMPANY_ALERTS_SUCCESS = 'POST_COMPANY_ALERTS_SUCCESS';
export const POST_COMPANY_ALERTS_FAILURE = 'POST_COMPANY_ALERTS_FAILURE';

export const DISMISS_COMPANY_ALERTS_REQUEST = 'DISMISS_COMPANY_ALERTS_REQUEST';
export const DISMISS_COMPANY_ALERTS_SUCCESS = 'DISMISS_COMPANY_ALERTS_SUCCESS';
export const DISMISS_COMPANY_ALERTS_FAILURE = 'DISMISS_COMPANY_ALERTS_FAILURE';

//SINGLE COMPANY ALERT
export const POST_COMPANY_ALERT_REQUEST = 'POST_COMPANY_ALERT_REQUEST';
export const POST_COMPANY_ALERT_SUCCESS = 'POST_COMPANY_ALERT_SUCCESS';
export const POST_COMPANY_ALERT_FAILURE = 'POST_COMPANY_ALERT_FAILURE';

export const DISMISS_COMPANY_ALERT_REQUEST = 'DISMISS_COMPANY_ALERT_REQUEST';
export const DISMISS_COMPANY_ALERT_SUCCESS = 'DISMISS_COMPANY_ALERT_SUCCESS';
export const DISMISS_COMPANY_ALERT_FAILURE = 'DISMISS_COMPANY_ALERT_FAILURE';
