export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';

export const FETCH_MESSAGES_BASIC_REQUEST = 'FETCH_MESSAGES_BASIC_REQUEST';
export const FETCH_MESSAGES_BASIC_SUCCESS = 'FETCH_MESSAGES_BASIC_SUCCESS';
export const FETCH_MESSAGES_BASIC_FAILURE = 'FETCH_MESSAGES_BASIC_FAILURE';

export const DISMISS_ALERT_REQUEST = 'DISMISS_ALERT_REQUEST';
export const DISMISS_ALERT_SUCCESS = 'DISMISS_ALERT_SUCCESS';
export const DISMISS_ALERT_FAILURE = 'DISMISS_ALERT_FAILURE';

export const DISMISS_ALERTS_REQUEST = 'DISMISS_ALERTS_REQUEST';
export const DISMISS_ALERTS_SUCCESS = 'DISMISS_ALERTS_SUCCESS';
export const DISMISS_ALERTS_FAILURE = 'DISMISS_ALERTS_FAILURE';

export const POST_ALERT_REQUEST = 'POST_ALERT_REQUEST';
export const POST_ALERT_SUCCESS = 'POST_ALERT_SUCCESS';
export const POST_ALERT_FAILURE = 'POST_ALERT_FAILURE';

export const POST_ALERTS_REQUEST = 'POST_ALERTS_REQUEST';
export const POST_ALERTS_SUCCESS = 'POST_ALERTS_SUCCESS';
export const POST_ALERTS_FAILURE = 'POST_ALERTS_FAILURE';
