export const FETCH_ALL_OPERATIVE_ALERTS_REQUEST =
    'FETCH_ALL_OPERATIVE_ALERTS_REQUEST';
export const FETCH_ALL_OPERATIVE_ALERTS_SUCCESS =
    'FETCH_ALL_OPERATIVE_ALERTS_SUCCESS';
export const FETCH_ALL_OPERATIVE_ALERTS_FAILURE =
    'FETCH_ALL_OPERATIVE_ALERTS_FAILURE';
export const FETCH_OPERATIVE_ALERT_DELIVERIES_REQUEST =
    'FETCH_OPERATIVE_ALERT_DELIVERIES_REQUEST';
export const FETCH_OPERATIVE_ALERT_DELIVERIES_SUCCESS =
    'FETCH_OPERATIVE_ALERT_DELIVERIES_SUCCESS';
export const FETCH_OPERATIVE_ALERT_DELIVERIES_FAILURE =
    'FETCH_OPERATIVE_ALERT_DELIVERIES_FAILURE';

export const CREATE_OPERATIVE_ALERT_REQUEST = 'CREATE_OPERATIVE_ALERT_REQUEST';
export const CREATE_OPERATIVE_ALERT_SUCCESS = 'CREATE_OPERATIVE_ALERT_SUCCESS';
export const CREATE_OPERATIVE_ALERT_FAILURE = 'CREATE_OPERATIVE_ALERT_FAILURE';
