export const FETCH_OPERATIVES_REQUEST = 'FETCH_OPERATIVES_REQUEST';
export const FETCH_OPERATIVES_SUCCESS = 'FETCH_OPERATIVES_SUCCESS';
export const FETCH_OPERATIVES_FAILURE = 'FETCH_OPERATIVES_FAILURE';

export const ADD_OPERATIVE_REQUEST = 'ADD_OPERATIVE_REQUEST';
export const ADD_OPERATIVE_SUCCESS = 'ADD_OPERATIVE_SUCCESS';
export const ADD_OPERATIVE_FAILURE = 'ADD_OPERATIVE_FAILURE';

export const DELETE_OPERATIVE_REQUEST = 'DELETE_OPERATIVE_REQUEST';
export const DELETE_OPERATIVE_SUCCESS = 'DELETE_OPERATIVE_SUCCESS';
export const DELETE_OPERATIVE_FAILURE = 'DELETE_OPERATIVE_FAILURE';
