export const FETCH_OPERATIVES_REQUEST = 'FETCH_OPERATIVES_REQUEST';
export const FETCH_OPERATIVES_SUCCESS = 'FETCH_OPERATIVES_SUCCESS';
export const FETCH_OPERATIVES_FAILURE = 'FETCH_OPERATIVES_FAILURE';
