export const FETCH_PAY_RATES_REQUEST = 'FETCH_PAY_RATES_REQUEST';
export const FETCH_PAY_RATES_SUCCESS = 'FETCH_PAY_RATES_SUCCESS';
export const FETCH_PAY_RATES_FAILURE = 'FETCH_PAY_RATES_FAILURE';

export const POST_COMPANY_PAY_RATES_REQUEST = 'POST_COMPANY_PAY_RATES_REQUEST';
export const POST_COMPANY_PAY_RATES_SUCCESS = 'POST_COMPANY_PAY_RATES_SUCCESS';
export const POST_COMPANY_PAY_RATES_FAILURE = 'POST_COMPANY_PAY_RATES_FAILURE';

export const POST_ASSIGN_PAY_RATES_REQUEST = 'POST_ASSIGN_PAY_RATES_REQUEST';
export const POST_ASSIGN_PAY_RATES_SUCCESS = 'POST_ASSIGN_PAY_RATES_SUCCESS';
export const POST_ASSIGN_PAY_RATES_FAILURE = 'POST_ASSIGN_PAY_RATES_FAILURE';
