export const FETCH_PENDING_INVITES_REQUEST = 'FETCH_PENDING_INVITES_REQUEST';
export const FETCH_PENDING_INVITES_SUCCESS = 'FETCH_PENDING_INVITES_SUCCESS';
export const FETCH_PENDING_INVITES_FAILURE = 'FETCH_PENDING_INVITES_FAILURE';

export const ACCEPT_PENDING_INVITE_REQUEST = 'ACCEPT_PENDING_INVITE_REQUEST';
export const ACCEPT_PENDING_INVITE_SUCCESS = 'ACCEPT_PENDING_INVITE_SUCCESS';
export const ACCEPT_PENDING_INVITE_FAILURE = 'ACCEPT_PENDING_INVITE_FAILURE';

export const FETCH_OUTGOING_INVITES_REQUEST = 'FETCH_OUTGOING_INVITES_REQUEST';
export const FETCH_OUTGOING_INVITES_SUCCESS = 'FETCH_OUTGOING_INVITES_SUCCESS';
export const FETCH_OUTGOING_INVITES_FAILURE = 'FETCH_OUTGOING_INVITES_FAILURE';
