export const FETCH_PENDING_INVITES_REQUEST = 'FETCH_PENDING_INVITES_REQUEST';
export const FETCH_PENDING_INVITES_SUCCESS = 'FETCH_PENDING_INVITES_SUCCESS';
export const FETCH_PENDING_INVITES_FAILURE = 'FETCH_PENDING_INVITES_FAILURE';

export const RESPOND_TO_PENDING_INVITE_REQUEST =
    'RESPOND_TO_PENDING_INVITE_REQUEST';
export const RESPOND_TO_PENDING_INVITE_SUCCESS =
    'RESPOND_TO_PENDING_INVITE_SUCCESS';
export const RESPOND_TO_PENDING_INVITE_FAILURE =
    'RESPOND_TO_PENDING_INVITE_FAILURE';

export const FETCH_OUTGOING_INVITES_REQUEST = 'FETCH_OUTGOING_INVITES_REQUEST';
export const FETCH_OUTGOING_INVITES_SUCCESS = 'FETCH_OUTGOING_INVITES_SUCCESS';
export const FETCH_OUTGOING_INVITES_FAILURE = 'FETCH_OUTGOING_INVITES_FAILURE';

export const DELETE_OUTGOING_INVITE_REQUEST = 'DELETE_OUTGOING_INVITE_REQUEST';
export const DELETE_OUTGOING_INVITE_SUCCESS = 'DELETE_OUTGOING_INVITE_SUCCESS';
export const DELETE_OUTGOING_INVITE_FAILURE = 'DELETE_OUTGOING_INVITE_FAILURE';
