export const FETCH_PENDING_INVITES_REQUEST = 'FETCH_PENDING_INVITES_REQUEST';
export const FETCH_PENDING_INVITES_SUCCESS = 'FETCH_PENDING_INVITES_SUCCESS';
export const FETCH_PENDING_INVITES_FAILURE = 'FETCH_PENDING_INVITES_FAILURE';

export const FETCH_OUTGOING_INVITES_REQUEST = 'FETCH_OUTGOING_INVITES_REQUEST';
export const FETCH_OUTGOING_INVITES_SUCCESS = 'FETCH_OUTGOING_INVITES_SUCCESS';
export const FETCH_OUTGOING_INVITES_FAILURE = 'FETCH_OUTGOING_INVITES_FAILURE';
