export const FETCH_PIN_OPTION_DOCUMENTS_REQUEST = 'FETCH_PIN_OPTION_DOCUMENTS_REQUEST';
export const FETCH_PIN_OPTION_DOCUMENTS_SUCCESS = 'FETCH_PIN_OPTION_DOCUMENTS_SUCCESS';
export const FETCH_PIN_OPTION_DOCUMENTS_FAILURE = 'FETCH_PIN_OPTION_DOCUMENTS_FAILURE';

export const CREATE_PIN_OPTION_DOCUMENT_REQUEST = 'CREATE_PIN_OPTION_DOCUMENT_REQUEST';
export const CREATE_PIN_OPTION_DOCUMENT_SUCCESS = 'CREATE_PIN_OPTION_DOCUMENT_SUCCESS';
export const CREATE_PIN_OPTION_DOCUMENT_FAILURE = 'CREATE_PIN_OPTION_DOCUMENT_FAILURE';

export const EDIT_PIN_OPTION_DOCUMENT_REQUEST = 'EDIT_PIN_OPTION_DOCUMENT_REQUEST';
export const EDIT_PIN_OPTION_DOCUMENT_SUCCESS = 'EDIT_PIN_OPTION_DOCUMENT_SUCCESS';
export const EDIT_PIN_OPTION_DOCUMENT_FAILURE = 'EDIT_PIN_OPTION_DOCUMENT_FAILURE';

export const DELETE_PIN_OPTION_DOCUMENT_REQUEST = 'DELETE_PIN_OPTION_DOCUMENT_REQUEST';
export const DELETE_PIN_OPTION_DOCUMENT_SUCCESS = 'DELETE_PIN_OPTION_DOCUMENT_SUCCESS';
export const DELETE_PIN_OPTION_DOCUMENT_FAILURE = 'DELETE_PIN_OPTION_DOCUMENT_FAILURE';
