export const FETCH_PIN_OPTION_TYPES_REQUEST = 'FETCH_PIN_OPTION_TYPES_REQUEST';
export const FETCH_PIN_OPTION_TYPES_SUCCESS = 'FETCH_PIN_OPTION_TYPES_SUCCESS';
export const FETCH_PIN_OPTION_TYPES_FAILURE = 'FETCH_PIN_OPTION_TYPES_FAILURE';

export const FETCH_PIN_OPTION_SETS_REQUEST = 'FETCH_PIN_OPTION_SETS_REQUEST';
export const FETCH_PIN_OPTION_SETS_SUCCESS = 'FETCH_PIN_OPTION_SETS_SUCCESS';
export const FETCH_PIN_OPTION_SETS_FAILURE = 'FETCH_PIN_OPTION_SETS_FAILURE';

export const FETCH_PIN_OPTION_VERSIONS_REQUEST = 'FETCH_PIN_OPTION_VERSIONS_REQUEST';
export const FETCH_PIN_OPTION_VERSIONS_SUCCESS = 'FETCH_PIN_OPTION_VERSIONS_SUCCESS';
export const FETCH_PIN_OPTION_VERSIONS_FAILURE = 'FETCH_PIN_OPTION_VERSIONS_FAILURE';

export const FETCH_PIN_OPTIONS_REQUEST = 'FETCH_PIN_OPTIONS_REQUEST';
export const FETCH_PIN_OPTIONS_SUCCESS = 'FETCH_PIN_OPTIONS_SUCCESS';
export const FETCH_PIN_OPTIONS_FAILURE = 'FETCH_PIN_OPTIONS_FAILURE';
