export const FETCH_PIN_OPTION_TYPES_REQUEST = 'FETCH_PIN_OPTION_TYPES_REQUEST';
export const FETCH_PIN_OPTION_TYPES_SUCCESS = 'FETCH_PIN_OPTION_TYPES_SUCCESS';
export const FETCH_PIN_OPTION_TYPES_FAILURE = 'FETCH_PIN_OPTION_TYPES_FAILURE';

export const FETCH_PIN_OPTION_SETS_REQUEST = 'FETCH_PIN_OPTION_SETS_REQUEST';
export const FETCH_PIN_OPTION_SETS_SUCCESS = 'FETCH_PIN_OPTION_SETS_SUCCESS';
export const FETCH_PIN_OPTION_SETS_FAILURE = 'FETCH_PIN_OPTION_SETS_FAILURE';

export const FETCH_PIN_OPTION_VERSIONS_REQUEST = 'FETCH_PIN_OPTION_VERSIONS_REQUEST';
export const FETCH_PIN_OPTION_VERSIONS_SUCCESS = 'FETCH_PIN_OPTION_VERSIONS_SUCCESS';
export const FETCH_PIN_OPTION_VERSIONS_FAILURE = 'FETCH_PIN_OPTION_VERSIONS_FAILURE';

export const FETCH_PIN_OPTIONS_REQUEST = 'FETCH_PIN_OPTIONS_REQUEST';
export const FETCH_PIN_OPTIONS_SUCCESS = 'FETCH_PIN_OPTIONS_SUCCESS';
export const FETCH_PIN_OPTIONS_FAILURE = 'FETCH_PIN_OPTIONS_FAILURE';

export const CREATE_PIN_OPTION_SET_REQUEST = 'CREATE_PIN_OPTION_SET_REQUEST';
export const CREATE_PIN_OPTION_SET_SUCCESS = 'CREATE_PIN_OPTION_SET_SUCCESS';
export const CREATE_PIN_OPTION_SET_FAILURE = 'CREATE_PIN_OPTION_SET_FAILURE';

export const EDIT_PIN_OPTION_SET_REQUEST = 'EDIT_PIN_OPTION_SET_REQUEST';
export const EDIT_PIN_OPTION_SET_SUCCESS = 'EDIT_PIN_OPTION_SET_SUCCESS';
export const EDIT_PIN_OPTION_SET_FAILURE = 'EDIT_PIN_OPTION_SET_FAILURE';

export const ENABLE_PIN_OPTION_SET_REQUEST = 'ENABLE_PIN_OPTION_SET_REQUEST';
export const ENABLE_PIN_OPTION_SET_SUCCESS = 'ENABLE_PIN_OPTION_SET_SUCCESS';
export const ENABLE_PIN_OPTION_SET_FAILURE = 'ENABLE_PIN_OPTION_SET_FAILURE';

export const DISABLE_PIN_OPTION_SET_REQUEST = 'DISABLE_PIN_OPTION_SET_REQUEST';
export const DISABLE_PIN_OPTION_SET_SUCCESS = 'DISABLE_PIN_OPTION_SET_SUCCESS';
export const DISABLE_PIN_OPTION_SET_FAILURE = 'DISABLE_PIN_OPTION_SET_FAILURE';

export const CREATE_PIN_OPTION_VALUE_REQUEST = 'CREATE_PIN_OPTION_VALUE_REQUEST';
export const CREATE_PIN_OPTION_VALUE_SUCCESS = 'CREATE_PIN_OPTION_VALUE_SUCCESS';
export const CREATE_PIN_OPTION_VALUE_FAILURE = 'CREATE_PIN_OPTION_VALUE_FAILURE';

export const EDIT_PIN_OPTION_VALUE_REQUEST = 'EDIT_PIN_OPTION_VALUE_REQUEST';
export const EDIT_PIN_OPTION_VALUE_SUCCESS = 'EDIT_PIN_OPTION_VALUE_SUCCESS';
export const EDIT_PIN_OPTION_VALUE_FAILURE = 'EDIT_PIN_OPTION_VALUE_FAILURE';

export const ENABLE_PIN_OPTION_VALUE_REQUEST = 'ENABLE_PIN_OPTION_VALUE_REQUEST';
export const ENABLE_PIN_OPTION_VALUE_SUCCESS = 'ENABLE_PIN_OPTION_VALUE_SUCCESS';
export const ENABLE_PIN_OPTION_VALUE_FAILURE = 'ENABLE_PIN_OPTION_VALUE_FAILURE';

export const DISABLE_PIN_OPTION_VALUE_REQUEST = 'DISABLE_PIN_OPTION_VALUE_REQUEST';
export const DISABLE_PIN_OPTION_VALUE_SUCCESS = 'DISABLE_PIN_OPTION_VALUE_SUCCESS';
export const DISABLE_PIN_OPTION_VALUE_FAILURE = 'DISABLE_PIN_OPTION_VALUE_FAILURE';

export const REORDER_PIN_OPTION_VALUES = 'REORDER_PIN_OPTION_VALUES';

export const SET_PIN_OPTIONS_TYPES_SELECTED_TAB_ID = 'SET_PIN_OPTIONS_TYPES_SELECTED_TAB_ID';

export const SET_OPTION_SET_AS_DEFAULT_REQUEST = 'SET_OPTION_SET_AS_DEFAULT_REQUEST';
export const SET_OPTION_SET_AS_DEFAULT_SUCCESS = 'SET_OPTION_SET_AS_DEFAULT_SUCCESS';
export const SET_OPTION_SET_AS_DEFAULT_FAILURE = 'SET_OPTION_SET_AS_DEFAULT_FAILURE';

//Super admin
export const SET_ADMIN_PIN_OPTIONS_TYPES_SELECTED_TAB_ID =
    'SET_ADMIN_PIN_OPTIONS_TYPES_SELECTED_TAB_ID';

export const FETCH_ADMIN_PIN_OPTION_TYPES_REQUEST = 'FETCH_ADMIN_PIN_OPTION_TYPES_REQUEST';
export const FETCH_ADMIN_PIN_OPTION_TYPES_SUCCESS = 'FETCH_ADMIN_PIN_OPTION_TYPES_SUCCESS';
export const FETCH_ADMIN_PIN_OPTION_TYPES_FAILURE = 'FETCH_ADMIN_PIN_OPTION_TYPES_FAILURE';

export const FETCH_ADMIN_PIN_OPTION_SETS_REQUEST = 'FETCH_ADMIN_PIN_OPTION_SETS_REQUEST';
export const FETCH_ADMIN_PIN_OPTION_SETS_SUCCESS = 'FETCH_ADMIN_PIN_OPTION_SETS_SUCCESS';
export const FETCH_ADMIN_PIN_OPTION_SETS_FAILURE = 'FETCH_ADMIN_PIN_OPTION_SETS_FAILURE';

export const FETCH_ADMIN_PIN_OPTIONS_REQUEST = 'FETCH_ADMIN_PIN_OPTIONS_REQUEST';
export const FETCH_ADMIN_PIN_OPTIONS_SUCCESS = 'FETCH_ADMIN_PIN_OPTIONS_SUCCESS';
export const FETCH_ADMIN_PIN_OPTIONS_FAILURE = 'FETCH_ADMIN_PIN_OPTIONS_FAILURE';

export const FETCH_ADMIN_PIN_OPTION_VERSIONS_REQUEST = 'FETCH_ADMIN_PIN_OPTION_VERSIONS_REQUEST';
export const FETCH_ADMIN_PIN_OPTION_VERSIONS_SUCCESS = 'FETCH_ADMIN_PIN_OPTION_VERSIONS_SUCCESS';
export const FETCH_ADMIN_PIN_OPTION_VERSIONS_FAILURE = 'FETCH_ADMIN_PIN_OPTION_VERSIONS_FAILURE';

export const ENABLE_ADMIN_PIN_OPTION_VALUE_REQUEST = 'ENABLE_ADMIN_PIN_OPTION_VALUE_REQUEST';
export const ENABLE_ADMIN_PIN_OPTION_VALUE_SUCCESS = 'ENABLE_ADMIN_PIN_OPTION_VALUE_SUCCESS';
export const ENABLE_ADMIN_PIN_OPTION_VALUE_FAILURE = 'ENABLE_ADMIN_PIN_OPTION_VALUE_FAILURE';

export const DISABLE_ADMIN_PIN_OPTION_VALUE_REQUEST = 'DISABLE_ADMIN_PIN_OPTION_VALUE_REQUEST';
export const DISABLE_ADMIN_PIN_OPTION_VALUE_SUCCESS = 'DISABLE_ADMIN_PIN_OPTION_VALUE_SUCCESS';
export const DISABLE_ADMIN_PIN_OPTION_VALUE_FAILURE = 'DISABLE_ADMIN_PIN_OPTION_VALUE_FAILURE';

export const CREATE_ADMIN_PIN_OPTION_SET_REQUEST = 'CREATE_ADMIN_PIN_OPTION_SET_REQUEST';
export const CREATE_ADMIN_PIN_OPTION_SET_SUCCESS = 'CREATE_ADMIN_PIN_OPTION_SET_SUCCESS';
export const CREATE_ADMIN_PIN_OPTION_SET_FAILURE = 'CREATE_ADMIN_PIN_OPTION_SET_FAILURE';
