export const FETCH_PINS_REQUEST = 'FETCH_PINS_REQUEST';
export const FETCH_PINS_SUCCESS = 'FETCH_PINS_SUCCESS';
export const FETCH_PINS_FAILURE = 'FETCH_PINS_FAILURE';

export const SELECT_PIN_HISTORY = 'SELECT_PIN_HISTORY';

export const FETCH_SINGLE_PIN_REQUEST = 'FETCH_SINGLE_PIN_REQUEST';
export const FETCH_SINGLE_PIN_SUCCESS = 'FETCH_SINGLE_PIN_SUCCESS';
export const FETCH_SINGLE_PIN_FAILURE = 'FETCH_SINGLE_PIN_FAILURE';

export const FETCH_PIN_HISTORIES_REQUEST = 'FETCH_PIN_HISTORIES_REQUEST';
export const FETCH_PIN_HISTORIES_SUCCESS = 'FETCH_PIN_HISTORIES_SUCCESS';
export const FETCH_PIN_HISTORIES_FAILURE = 'FETCH_PIN_HISTORIES_FAILURE';

export const FETCH_CUSTOM_FIELDS_REQUEST = 'FETCH_CUSTOM_FIELDS_REQUEST';
export const FETCH_CUSTOM_FIELDS_SUCCESS = 'FETCH_CUSTOM_FIELDS_SUCCESS';
export const FETCH_CUSTOM_FIELDS_FAILURE = 'FETCH_CUSTOM_FIELDS_FAILURE';
