export const FETCH_PINS_REQUEST = 'FETCH_PINS_REQUEST';
export const FETCH_PINS_SUCCESS = 'FETCH_PINS_SUCCESS';
export const FETCH_PINS_FAILURE = 'FETCH_PINS_FAILURE';

export const SELECT_PIN_HISTORY = 'SELECT_PIN_HISTORY';

export const FETCH_SINGLE_PIN_REQUEST = 'FETCH_SINGLE_PIN_REQUEST';
export const FETCH_SINGLE_PIN_SUCCESS = 'FETCH_SINGLE_PIN_SUCCESS';
export const FETCH_SINGLE_PIN_FAILURE = 'FETCH_SINGLE_PIN_FAILURE';

export const FETCH_PIN_TEMPLATES_REQUEST = 'FETCH_PIN_TEMPLATES_REQUEST';
export const FETCH_PIN_TEMPLATES_SUCCESS = 'FETCH_PIN_TEMPLATES_SUCCESS';
export const FETCH_PIN_TEMPLATES_FAILURE = 'FETCH_PIN_TEMPLATES_FAILURE';

export const CREATE_PIN_REQUEST = 'CREATE_PIN_REQUEST';
export const CREATE_PIN_SUCCESS = 'CREATE_PIN_SUCCESS';
export const CREATE_PIN_FAILURE = 'CREATE_PIN_FAILURE';

export const EDIT_PIN_LOCATION_REQUEST = 'EDIT_PIN_LOCATION_REQUEST';
export const EDIT_PIN_LOCATION_SUCCESS = 'EDIT_PIN_LOCATION_SUCCESS';
export const EDIT_PIN_LOCATION_FAILURE = 'EDIT_PIN_LOCATION_FAILURE';

export const EDIT_PIN_HISTORY_REQUEST = 'EDIT_PIN_HISTORY_REQUEST';
export const EDIT_PIN_HISTORY_SUCCESS = 'EDIT_PIN_HISTORY_SUCCESS';
export const EDIT_PIN_HISTORY_FAILURE = 'EDIT_PIN_HISTORY_FAILURE';

export const DELETE_PIN_HISTORY_REQUEST = 'DELETE_PIN_HISTORY_REQUEST';
export const DELETE_PIN_HISTORY_SUCCESS = 'DELETE_PIN_HISTORY_SUCCESS';
export const DELETE_PIN_HISTORY_FAILURE = 'DELETE_PIN_HISTORY_FAILURE';
