export const FETCH_PINS_REQUEST = 'FETCH_PINS_REQUEST';
export const FETCH_PINS_SUCCESS = 'FETCH_PINS_SUCCESS';
export const FETCH_PINS_FAILURE = 'FETCH_PINS_FAILURE';

export const SELECT_PIN_HISTORY = 'SELECT_PIN_HISTORY';

export const FETCH_SINGLE_PIN_REQUEST = 'FETCH_SINGLE_PIN_REQUEST';
export const FETCH_SINGLE_PIN_SUCCESS = 'FETCH_SINGLE_PIN_SUCCESS';
export const FETCH_SINGLE_PIN_FAILURE = 'FETCH_SINGLE_PIN_FAILURE';

export const FETCH_PIN_TEMPLATES_REQUEST = 'FETCH_PIN_TEMPLATES_REQUEST';
export const FETCH_PIN_TEMPLATES_SUCCESS = 'FETCH_PIN_TEMPLATES_SUCCESS';
export const FETCH_PIN_TEMPLATES_FAILURE = 'FETCH_PIN_TEMPLATES_FAILURE';

export const CREATE_PIN_REQUEST = 'CREATE_PIN_REQUEST';
export const CREATE_PIN_SUCCESS = 'CREATE_PIN_SUCCESS';
export const CREATE_PIN_FAILURE = 'CREATE_PIN_FAILURE';

export const EDIT_PIN_LOCATION_REQUEST = 'EDIT_PIN_LOCATION_REQUEST';
export const EDIT_PIN_LOCATION_SUCCESS = 'EDIT_PIN_LOCATION_SUCCESS';
export const EDIT_PIN_LOCATION_FAILURE = 'EDIT_PIN_LOCATION_FAILURE';

export const EDIT_PIN_HISTORY_REQUEST = 'EDIT_PIN_HISTORY_REQUEST';
export const EDIT_PIN_HISTORY_SUCCESS = 'EDIT_PIN_HISTORY_SUCCESS';
export const EDIT_PIN_HISTORY_FAILURE = 'EDIT_PIN_HISTORY_FAILURE';

export const DELETE_PIN_HISTORY_REQUEST = 'DELETE_PIN_HISTORY_REQUEST';
export const DELETE_PIN_HISTORY_SUCCESS = 'DELETE_PIN_HISTORY_SUCCESS';
export const DELETE_PIN_HISTORY_FAILURE = 'DELETE_PIN_HISTORY_FAILURE';

export const DELETE_ALL_PIN_HISTORY_REQUEST = 'DELETE_ALL_PIN_HISTORY_REQUEST';
export const DELETE_ALL_PIN_HISTORY_SUCCESS = 'DELETE_ALL_PIN_HISTORY_SUCCESS';
export const DELETE_ALL_PIN_HISTORY_FAILURE = 'DELETE_ALL_PIN_HISTORY_FAILURE';

export const FETCH_PIN_FEED_REQUEST = 'FETCH_PIN_FEED_REQUEST';
export const FETCH_PIN_FEED_SUCCESS = 'FETCH_PIN_FEED_SUCCESS';
export const FETCH_PIN_FEED_FAILURE = 'FETCH_PIN_FEED_FAILURE';

export const FETCH_USER_PIN_FEEDS_REQUEST = 'FETCH_USER_PIN_FEEDS_REQUEST';
export const FETCH_USER_PIN_FEEDS_SUCCESS = 'FETCH_USER_PIN_FEEDS_SUCCESS';
export const FETCH_USER_PIN_FEEDS_FAILURE = 'FETCH_USER_PIN_FEEDS_FAILURE';

export const SINGLE_PIN_GENERATE_REPORT_REQUEST = 'SINGLE_PIN_GENERATE_REPORT_REQUEST';
export const SINGLE_PIN_GENERATE_REPORT_SUCCESS = 'SINGLE_PIN_GENERATE_REPORT_SUCCESS';
export const SINGLE_PIN_GENERATE_REPORT_FAILURE = 'SINGLE_PIN_GENERATE_REPORT_FAILURE';

export const FETCH_PINS_BY_SHARE_LINK_REQUEST = 'FETCH_PINS_BY_SHARE_LINK_REQUEST';
export const FETCH_PINS_BY_SHARE_LINK_SUCCESS = 'FETCH_PINS_BY_SHARE_LINK_SUCCESS';
export const FETCH_PINS_BY_SHARE_LINK_FAILURE = 'FETCH_PINS_BY_SHARE_LINK_FAILURE';

export const FETCH_ALL_PINS_FOR_DRAWING_REQUEST = 'FETCH_ALL_PINS_FOR_DRAWING_REQUEST';
export const FETCH_ALL_PINS_FOR_DRAWING_SUCCESS = 'FETCH_ALL_PINS_FOR_DRAWING_SUCCESS';
export const FETCH_ALL_PINS_FOR_DRAWING_FAILURE = 'FETCH_ALL_PINS_FOR_DRAWING_FAILURE';

// SUPER ADMIN
export const ADMIN_FETCH_PINS_FOR_COMPANY_REQUEST = 'ADMIN_FETCH_PINS_FOR_COMPANY_REQUEST';
export const ADMIN_FETCH_PINS_FOR_COMPANY_SUCCESS = 'ADMIN_FETCH_PINS_FOR_COMPANY_SUCCESS';
export const ADMIN_FETCH_PINS_FOR_COMPANY_FAILURE = 'ADMIN_FETCH_PINS_FOR_COMPANY_FAILURE';

export const FETCH_PINS_FOR_REPORT_REQUEST = 'FETCH_PINS_FOR_REPORT_REQUEST';
export const FETCH_PINS_FOR_REPORT_SUCCESS = 'FETCH_PINS_FOR_REPORT_SUCCESS';
export const FETCH_PINS_FOR_REPORT_FAILURE = 'FETCH_PINS_FOR_REPORT_FAILURE';

export const TOGGLE_PIN_VIEW_MODE = 'TOGGLE_PIN_VIEW_MODE';
