export const FETCH_PIN_TASKS_REQUEST = 'FETCH_PIN_TASKS_REQUEST';
export const FETCH_PIN_TASKS_SUCCESS = 'FETCH_PIN_TASKS_SUCCESS';
export const FETCH_PIN_TASKS_FAILURE = 'FETCH_PIN_TASKS_FAILURE';

export const FETCH_PIN_TASK_REQUEST = 'FETCH_PIN_TASK_REQUEST';
export const FETCH_PIN_TASK_SUCCESS = 'FETCH_PIN_TASK_SUCCESS';
export const FETCH_PIN_TASK_FAILURE = 'FETCH_PIN_TASK_FAILURE';

export const CREATE_PIN_TASKS_REQUEST = 'CREATE_PIN_TASKS_REQUEST';
export const CREATE_PIN_TASKS_SUCCESS = 'CREATE_PIN_TASKS_SUCCESS';
export const CREATE_PIN_TASKS_FAILURE = 'CREATE_PIN_TASKS_FAILURE';

export const EDIT_PIN_TASK_REQUEST = 'EDIT_PIN_TASK_REQUEST';
export const EDIT_PIN_TASK_SUCCESS = 'EDIT_PIN_TASK_SUCCESS';
export const EDIT_PIN_TASK_FAILURE = 'EDIT_PIN_TASK_FAILURE';

export const DELETE_PIN_TASK_REQUEST = 'DELETE_PIN_TASK_REQUEST';
export const DELETE_PIN_TASK_SUCCESS = 'DELETE_PIN_TASK_SUCCESS';
export const DELETE_PIN_TASK_FAILURE = 'DELETE_PIN_TASK_FAILURE';

export const FETCH_PIN_TASK_SERIES_MULTIPLE_REQUEST = 'FETCH_PIN_TASK_SERIES_MULTIPLE_REQUEST';
export const FETCH_PIN_TASK_SERIES_MULTIPLE_SUCCESS = 'FETCH_PIN_TASK_SERIES_MULTIPLE_SUCCESS';
export const FETCH_PIN_TASK_SERIES_MULTIPLE_FAILURE = 'FETCH_PIN_TASK_SERIES_MULTIPLE_FAILURE';

export const FETCH_PIN_TASK_SERIES_REQUEST = 'FETCH_PIN_TASK_SERIES_REQUEST';
export const FETCH_PIN_TASK_SERIES_SUCCESS = 'FETCH_PIN_TASK_SERIES_SUCCESS';
export const FETCH_PIN_TASK_SERIES_FAILURE = 'FETCH_PIN_TASK_SERIES_FAILURE';

export const EDIT_PIN_TASK_SERIES_REQUEST = 'EDIT_PIN_TASK_SERIES_REQUEST';
export const EDIT_PIN_TASK_SERIES_SUCCESS = 'EDIT_PIN_TASK_SERIES_SUCCESS';
export const EDIT_PIN_TASK_SERIES_FAILURE = 'EDIT_PIN_TASK_SERIES_FAILURE';

export const DELETE_PIN_TASK_SERIES_REQUEST = 'DELETE_PIN_TASK_SERIES_REQUEST';
export const DELETE_PIN_TASK_SERIES_SUCCESS = 'DELETE_PIN_TASK_SERIES_SUCCESS';
export const DELETE_PIN_TASK_SERIES_FAILURE = 'DELETE_PIN_TASK_SERIES_FAILURE';

export const SET_PIN_RECURRENCE_FILTERS = 'SET_PIN_RECURRENCE_FILTERS';
