export const FETCH_ALL_PRELIMS_REQUEST = 'FETCH_ALL_PRELIMS_REQUEST';
export const FETCH_ALL_PRELIMS_SUCCESS = 'FETCH_ALL_PRELIMS_SUCCESS';
export const FETCH_ALL_PRELIMS_FAILURE = 'FETCH_ALL_PRELIMS_FAILURE';
