export const FETCH_ALL_PRELIMS_REQUEST = 'FETCH_ALL_PRELIMS_REQUEST';
export const FETCH_ALL_PRELIMS_SUCCESS = 'FETCH_ALL_PRELIMS_SUCCESS';
export const FETCH_ALL_PRELIMS_FAILURE = 'FETCH_ALL_PRELIMS_FAILURE';

export const CREATE_PRELIM_REQUEST = 'CREATE_PIN_TASKS_REQUEST';
export const CREATE_PRELIM_SUCCESS = 'CREATE_PIN_TASKS_SUCCESS';
export const CREATE_PRELIM_FAILURE = 'CREATE_PIN_TASKS_FAILURE';
