export const CREATE_PRELIM_REQUEST = 'CREATE_PRELIM_REQUEST';
export const CREATE_PRELIM_SUCCESS = 'CREATE_PRELIM_SUCCESS';
export const CREATE_PRELIM_FAILURE = 'CREATE_PRELIM_FAILURE';

export const CREATE_HIERARCHY_PRELIM_REQUEST = 'CREATE_HIERARCHY_PRELIM_REQUEST';
export const CREATE_HIERARCHY_PRELIM_SUCCESS = 'CREATE_HIERARCHY_PRELIM_SUCCESS';
export const CREATE_HIERARCHY_PRELIM_FAILURE = 'CREATE_HIERARCHY_PRELIM_FAILURE';

export const CREATE_COSTING_AND_ESTIMATING_PRELIM_REQUEST =
    'CREATE_COSTING_AND_ESTIMATING_CART_REQUEST';
export const CREATE_COSTING_AND_ESTIMATING_PRELIM_SUCCESS =
    'CREATE_COSTING_AND_ESTIMATING_CART_SUCCESS';
export const CREATE_COSTING_AND_ESTIMATING_PRELIM_FAILURE =
    'CREATE_COSTING_AND_ESTIMATING_CART_FAILURE';

export const LINK_PRELIM_REQUEST = 'LINK_PRELIM_REQUEST';
export const LINK_PRELIM_SUCCESS = 'LINK_PRELIM_SUCCESS';
export const LINK_PRELIM_FAILURE = 'LINK_PRELIM_FAILURE';

export const FETCH_ALL_PRELIMS_REQUEST = 'FETCH_ALL_PRELIMS_REQUEST';
export const FETCH_ALL_PRELIMS_SUCCESS = 'FETCH_ALL_PRELIMS_SUCCESS';
export const FETCH_ALL_PRELIMS_FAILURE = 'FETCH_ALL_PRELIMS_FAILURE';

export const FETCH_PRELIM_REQUEST = 'FETCH_PRELIM_REQUEST';
export const FETCH_PRELIM_SUCCESS = 'FETCH_PRELIM_SUCCESS';
export const FETCH_PRELIM_FAILURE = 'FETCH_PRELIM_FAILURE';

export const EDIT_PRELIM_REQUEST = 'EDIT_PRELIM_REQUEST';
export const EDIT_PRELIM_SUCCESS = 'EDIT_PRELIM_SUCCESS';
export const EDIT_PRELIM_FAILURE = 'EDIT_PRELIM_FAILURE';

export const EDIT_LINK_PRELIM_REQUEST = 'EDIT_LINK_PRELIM_REQUEST';
export const EDIT_LINK_PRELIM_SUCCESS = 'EDIT_LINK_PRELIM_SUCCESS';
export const EDIT_LINK_PRELIM_FAILURE = 'EDIT_LINK_PRELIM_FAILURE';

export const DELETE_PRELIM_REQUEST = 'DELETE_PRELIM_REQUEST';
export const DELETE_PRELIM_SUCCESS = 'DELETE_PRELIM_SUCCESS';
export const DELETE_PRELIM_FAILURE = 'DELETE_PRELIM_FAILURE';

export const DELETE_PRELIM_LINK_REQUEST = 'DELETE_PRELIM_LINK_REQUEST';
export const DELETE_PRELIM_LINK_SUCCESS = 'DELETE_PRELIM_LINK_SUCCESS';
export const DELETE_PRELIM_LINK_FAILURE = 'DELETE_PRELIM_LINK_FAILURE';

export const DELETE_COSTING_AND_ESTIMATING_PRELIM_REQUEST =
    'DELETE_COSTING_AND_ESTIMATING_PRELIM_REQUEST';
export const DELETE_COSTING_AND_ESTIMATING_PRELIM_SUCCESS =
    'DELETE_COSTING_AND_ESTIMATING_PRELIM_SUCCESS';
export const DELETE_COSTING_AND_ESTIMATING_PRELIM_FAILURE =
    'DELETE_COSTING_AND_ESTIMATING_PRELIM_FAILURE';

export const DELETE_CUSTOM_PRELIM_FAILURE = 'DELETE_CUSTOM_PRELIM_FAILURE';
export const DELETE_CUSTOM_PRELIM_REQUEST = 'DELETE_CUSTOM_PRELIM_REQUEST';
export const DELETE_CUSTOM_PRELIM_SUCCESS = 'DELETE_CUSTOM_PRELIM_SUCCESS';
