export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const CHANGE_PROFILE_PASSWORD_REQUEST =
    'CHANGE_PROFILE_PASSWORD_REQUEST';
export const CHANGE_PROFILE_PASSWORD_SUCCESS =
    'CHANGE_PROFILE_PASSWORD_SUCCESS';
export const CHANGE_PROFILE_PASSWORD_FAILURE =
    'CHANGE_PROFILE_PASSWORD_FAILURE';
