export const GENERATE_QR_CODES_REQUEST = 'GENERATE_QR_CODES_REQUEST';
export const GENERATE_QR_CODES_SUCCESS = 'GENERATE_QR_CODES_SUCCESS';
export const GENERATE_QR_CODES_FAILURE = 'GENERATE_QR_CODES_FAILURE';