export const FETCH_RECENT_UPDATES_REQUEST = 'FETCH_RECENT_UPDATES_REQUEST';
export const FETCH_RECENT_UPDATES_SUCCESS = 'FETCH_RECENT_UPDATES_SUCCESS';
export const FETCH_RECENT_UPDATES_FAILURE = 'FETCH_RECENT_UPDATES_FAILURE';

export const POST_RECENT_UPDATES_REQUEST = 'POST_RECENT_UPDATES_REQUEST';
export const POST_RECENT_UPDATES_SUCCESS = 'POST_RECENT_UPDATES_SUCCESS';
export const POST_RECENT_UPDATES_FAILURE = 'POST_RECENT_UPDATES_FAILURE';
