export const ADMIN_FETCH_RECENTLY_EXTENDED_REQUEST = 'ADMIN_FETCH_RECENTLY_EXTENDED_REQUEST';
export const ADMIN_FETCH_RECENTLY_EXTENDED_SUCCESS = 'ADMIN_FETCH_RECENTLY_EXTENDED_SUCCESS';
export const ADMIN_FETCH_RECENTLY_EXTENDED_FAILURE = 'ADMIN_FETCH_RECENTLY_EXTENDED_FAILURE';

export const FETCH_RECENTLY_EXTENDED_BY_SEARCH_FAILURE =
    'FETCH_RECENTLY_EXTENDED_BY_SEARCH_FAILURE';
export const FETCH_RECENTLY_EXTENDED_BY_SEARCH_SUCCESS =
    'FETCH_RECENTLY_EXTENDED_BY_SEARCH_SUCCESS';
export const FETCH_RECENTLY_EXTENDED_BY_SEARCH_REQUEST =
    'FETCH_RECENTLY_EXTENDED_BY_SEARCH_REQUEST';

export const FETCH_RECENTLY_EXTENDED_COUNT_REQUEST = 'FETCH_RECENTLY_EXTENDED_COUNT_REQUEST';
export const FETCH_RECENTLY_EXTENDED_COUNT_SUCCESS = 'FETCH_RECENTLY_EXTENDED_COUNT_SUCCESS';
export const FETCH_RECENTLY_EXTENDED_COUNT_FAILURE = 'FETCH_RECENTLY_EXTENDED_COUNT_FAILURE';

export const UPDATE_RECENTLY_EXTENDED_PAGE = 'UPDATE_RECENTLY_EXTENDED_PAGE';
