export const UPDATE_REPORT_FILTER = 'UPDATE_REPORT_FILTERS';
export const UPDATE_OPERATIVE_FILTER = 'UPDATE_OPERATIVE_FILTERS';
export const UPDATE_SELECTED_PINS = 'UPDATE_SELECTED_PINS';

export const POST_REPORT_REQUEST = 'POST_REPORT_REQUEST';
export const POST_REPORT_SUCCESS = 'POST_REPORT_SUCCESS';
export const POST_REPORT_NO_PINS = 'POST_REPORT_NO_PINS';
export const POST_REPORT_FAILURE = 'POST_REPORT_FAILURE';

export const POST_CUSTOM_FILTERS_REQUEST = 'POST_CUSTOM_FILTERS_REQUEST';
export const POST_CUSTOM_FILTERS_SUCCESS = 'POST_CUSTOM_FILTERS_SUCCESS';
export const POST_CUSTOM_FILTERS_FAILURE = 'POST_CUSTOM_FILTERS_FAILURE';

export const UPDATE_FURTHER_FILTRATION_OPTION =
    'UPDATE_FURTHER_FILTRATION_OPTION';
export const UPDATE_FILTER_QUESTION_FIELDS = 'UPDATE_FILTER_QUESTION_FIELDS';
export const UPDATE_FILTER_QUESTION_FIELD = 'UPDATE_FILTER_QUESTION_FIELD';
export const UPDATE_FILTER_QUESTION_VALS = 'UPDATE_FILTER_QUESTION_VALS';
export const ADD_FILTER_QUESTION = 'ADD_FILTER_QUESTION';
export const REMOVE_FILTER_QUESTION = 'REMOVE_FILTER_QUESTION';
export const REMOVE_FILTER_QUESTIONS = 'REMOVE_FILTER_QUESTIONS';
export const UPDATE_FILTER_OPTION = 'UPDATE_FILTER_OPTION';
export const RESET_FILTER_OPTIONS = 'RESET_FILTER_OPTIONS';

export const ADD_RECTANGLE = 'ADD_RECTANGLE';
export const REMOVE_RECTANGLE = 'REMOVE_RECTANGLE';
export const REMOVE_ALL_RECTANGLES = 'REMOVE_ALL_RECTANGLES';
export const UPDATE_IS_PIN_EXCLUDED = 'UPDATE_IS_PIN_EXCLUDED';
export const REMOVE_ALL_EXCLUDED_PINS = 'REMOVE_ALL_EXCLUDED_PINS';
