export const UPDATE_REPORT_FILTER = 'UPDATE_REPORT_FILTERS';

export const POST_REPORT_REQUEST = 'POST_REPORT_REQUEST';
export const POST_REPORT_SUCCESS = 'POST_REPORT_SUCCESS';
export const POST_REPORT_FAILURE = 'POST_REPORT_FAILURE';
