export const POST_REQUEST_DEMO_REQUEST = 'POST_REQUEST_DEMO_REQUEST';
export const POST_REQUEST_DEMO_SUCCESS = 'POST_REQUEST_DEMO_SUCCESS';
export const POST_REQUEST_DEMO_FAILURE = 'POST_REQUEST_DEMO_FAILURE';
