// superAdmin
export const CREATE_SERVICE_REQUEST = 'CREATE_SERVICE_REQUEST';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_FAILURE';

export const FETCH_ALL_SERVICES_REQUEST = 'FETCH_ALL_SERVICES_REQUEST';
export const FETCH_ALL_SERVICES_SUCCESS = 'FETCH_ALL_SERVICES_SUCCESS';
export const FETCH_ALL_SERVICES_FAILURE = 'FETCH_ALL_SERVICES_FAILURE';

export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST';
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';
export const EDIT_SERVICE_FAILURE = 'EDIT_SERVICE_FAILURE';

// companyAdmin

export const COMPANY_FETCH_ALL_SERVICES_REQUEST =
    'COMPANY_FETCH_ALL_SERVICES_REQUEST';
export const COMPANY_FETCH_ALL_SERVICES_SUCCESS =
    'COMPANY_FETCH_ALL_SERVICES_SUCCESS';
export const COMPANY_FETCH_ALL_SERVICES_FAILURE =
    'COMPANY_FETCH_ALL_SERVICES_FAILURE';
