export const UPDATE_SITES_SEARCH_TERM = 'UPDATE_SITES_SEARCH_TERM';
export const SET_SITES_FILTER_STATUS = 'SET_SITES_FILTER_STATUS';

export const FETCH_SITES_REQUEST = 'FETCH_SITES_REQUEST';
export const FETCH_SITES_SUCCESS = 'FETCH_SITES_SUCCESS';
export const FETCH_SITES_FAILURE = 'FETCH_SITES_FAILURE';
