export const ADMIN_SITE_MANAGEMENT_SELECT_HIERARCHY =
    'ADMIN_SITE_MANAGEMENT_SELECT_HIERARCHY';
export const ADMIN_SITE_MANAGEMENT_SELECT_OPTION =
    'ADMIN_SITE_MANAGEMENT_SELECT_OPTION';

export const ADMIN_MOVE_BUILDING_REQUEST = 'ADMIN_MOVE_BUILDING_REQUEST';
export const ADMIN_MOVE_BUILDING_SUCCESS = 'ADMIN_MOVE_BUILDING_SUCCESS';
export const ADMIN_MOVE_BUILDING_FAILURE = 'ADMIN_MOVE_BUILDING_FAILURE';

export const ADMIN_MOVE_FLOOR_REQUEST = 'ADMIN_MOVE_FLOOR_REQUEST';
export const ADMIN_MOVE_FLOOR_SUCCESS = 'ADMIN_MOVE_FLOOR_SUCCESS';
export const ADMIN_MOVE_FLOOR_FAILURE = 'ADMIN_MOVE_FLOOR_FAILURE';

export const ADMIN_MOVE_DRAWING_REQUEST = 'ADMIN_MOVE_DRAWING_REQUEST';
export const ADMIN_MOVE_DRAWING_SUCCESS = 'ADMIN_MOVE_DRAWING_SUCCESS';
export const ADMIN_MOVE_DRAWING_FAILURE = 'ADMIN_MOVE_DRAWING_FAILURE';
