export const UPDATE_SITES_FILTERS = 'UPDATE_SITES_FILTERS';

export const FETCH_ALL_SITES_REQUEST = 'FETCH_ALL_SITES_REQUEST';
export const FETCH_ALL_SITES_SUCCESS = 'FETCH_ALL_SITES_SUCCESS';
export const FETCH_ALL_SITES_FAILURE = 'FETCH_ALL_SITES_FAILURE';

export const FETCH_SINGLE_SITE_REQUEST = 'FETCH_SINGLE_SITE_REQUEST';
export const FETCH_SINGLE_SITE_SUCCESS = 'FETCH_SINGLE_SITE_SUCCESS';
export const FETCH_SINGLE_SITE_FAILURE = 'FETCH_SINGLE_SITE_FAILURE';

export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

export const CREATE_SITE_REQUEST = 'CREATE_SITE_REQUEST';
export const CREATE_SITE_SUCCESS = 'CREATE_SITE_SUCCESS';
export const CREATE_SITE_FAILURE = 'CREATE_SITE_FAILURE';

export const EDIT_SITE_REQUEST = 'EDIT_SITE_REQUEST';
export const EDIT_SITE_SUCCESS = 'EDIT_SITE_SUCCESS';
export const EDIT_SITE_FAILURE = 'EDIT_SITE_FAILURE';

export const DELETE_SITE_REQUEST = 'DELETE_SITE_REQUEST';
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS';
export const DELETE_SITE_FAILURE = 'DELETE_SITE_FAILURE';
