export const FETCH_PIN_STATS_REQUEST = 'FETCH_PIN_STATS_REQUEST';
export const FETCH_PIN_STATS_SUCCESS = 'FETCH_PIN_STATS_SUCCESS';
export const FETCH_PIN_STATS_FAILURE = 'FETCH_PIN_STATS_FAILURE';

export const POST_FILTER_PIN_STATS_REQUEST = 'POST_FILTER_PIN_STATS_REQUEST';
export const POST_FILTER_PIN_STATS_SUCCESS = 'POST_FILTER_PIN_STATS_SUCCESS';
export const POST_FILTER_PIN_STATS_FAILURE = 'POST_FILTER_PIN_STATS_FAILURE';
