export const FETCH_ALL_SUBSCRIPTIONS_REQUEST =
    'FETCH_ALL_SUBSCRIPTIONS_REQUEST';
export const FETCH_ALL_SUBSCRIPTIONS_SUCCESS =
    'FETCH_ALL_SUBSCRIPTIONS_SUCCESS';
export const FETCH_ALL_SUBSCRIPTIONS_FAILURE =
    'FETCH_ALL_SUBSCRIPTIONS_FAILURE';
