export const FETCH_ALL_SUBSCRIPTIONS_REQUEST =
    'FETCH_ALL_SUBSCRIPTIONS_REQUEST';
export const FETCH_ALL_SUBSCRIPTIONS_SUCCESS =
    'FETCH_ALL_SUBSCRIPTIONS_SUCCESS';
export const FETCH_ALL_SUBSCRIPTIONS_FAILURE =
    'FETCH_ALL_SUBSCRIPTIONS_FAILURE';

export const EDIT_SERVICE_RENEWAL_STATUS_REQUEST =
    'EDIT_SERVICE_RENEWAL_STATUS_REQUEST';
export const EDIT_SERVICE_RENEWAL_STATUS_SUCCESS =
    'EDIT_SERVICE_RENEWAL_STATUS_SUCCESS';
export const EDIT_SERVICE_RENEWAL_STATUS_FAILURE =
    'EDIT_SERVICE_RENEWAL_STATUS_FAILURE';

export const EDIT_SUBSCRIPTION_RENEWAL_STATUS_REQUEST =
    'EDIT_SUBSCRIPTION_RENEWAL_STATUS_REQUEST';
export const EDIT_SUBSCRIPTION_RENEWAL_STATUS_SUCCESS =
    'EDIT_SUBSCRIPTION_RENEWAL_STATUS_SUCCESS';
export const EDIT_SUBSCRIPTION_RENEWAL_STATUS_FAILURE =
    'EDIT_SUBSCRIPTION_RENEWAL_STATUS_FAILURE';

export const FETCH_PRO_RATA_SUBSCRIPTION_COST_REQUEST =
    'FETCH_PRO_RATA_SUBSCRIPTION_COST_REQUEST';
export const FETCH_PRO_RATA_SUBSCRIPTION_COST_SUCCESS =
    'FETCH_PRO_RATA_SUBSCRIPTION_COST_SUCCESS';
export const FETCH_PRO_RATA_SUBSCRIPTION_COST_FAILURE =
    'FETCH_PRO_RATA_SUBSCRIPTION_COST_FAILURE';
