export const SA_FETCH_ALL_INVOICES_REQUEST = 'SA_FETCH_ALL_INVOICES_REQUEST';
export const SA_FETCH_ALL_INVOICES_SUCCESS = 'SA_FETCH_ALL_INVOICES_SUCCESS';
export const SA_FETCH_ALL_INVOICES_FAILURE = 'SA_FETCH_ALL_INVOICES_FAILURE';

export const SA_RECORD_INVOICE_PAYMENT_REQUEST =
    'SA_RECORD_INVOICE_PAYMENT_REQUEST';
export const SA_RECORD_INVOICE_PAYMENT_SUCCESS =
    'SA_RECORD_INVOICE_PAYMENT_SUCCESS';
export const SA_RECORD_INVOICE_PAYMENT_FAILURE =
    'SA_RECORD_INVOICE_PAYMENT_FAILURE';

export const SA_FETCH_PAYMENTS_BY_INVOICE_REQUEST =
    'SA_FETCH_PAYMENTS_BY_INVOICE_REQUEST';
export const SA_FETCH_PAYMENTS_BY_INVOICE_SUCCESS =
    'SA_FETCH_PAYMENTS_BY_INVOICE_SUCCESS';
export const SA_FETCH_PAYMENTS_BY_INVOICE_FAILURE =
    'SA_FETCH_PAYMENTS_BY_INVOICE_FAILURE';

export const SA_EDIT_INVOICE_PAYMENT_REQUEST =
    'SA_EDIT_INVOICE_PAYMENT_REQUEST';
export const SA_EDIT_INVOICE_PAYMENT_SUCCESS =
    'SA_EDIT_INVOICE_PAYMENT_SUCCESS';
export const SA_EDIT_INVOICE_PAYMENT_FAILURE =
    'SA_EDIT_INVOICE_PAYMENT_FAILURE';

export const SA_DELETE_INVOICE_PAYMENT_REQUEST =
    'SA_DELETE_INVOICE_PAYMENT_REQUEST';
export const SA_DELETE_INVOICE_PAYMENT_SUCCESS =
    'SA_DELETE_INVOICE_PAYMENT_SUCCESS';
export const SA_DELETE_INVOICE_PAYMENT_FAILURE =
    'SA_DELETE_INVOICE_PAYMENT_FAILURE';

export const SA_MAKE_INVOICE_FREE_REQUEST = 'SA_MAKE_INVOICE_FREE_REQUEST';
export const SA_MAKE_INVOICE_FREE_SUCCESS = 'SA_MAKE_INVOICE_FREE_SUCCESS';
export const SA_MAKE_INVOICE_FREE_FAILURE = 'SA_MAKE_INVOICE_FREE_FAILURE';
