export const CREATE_SOS_CODE_REQUEST = 'CREATE_SOS_CODE_REQUEST';
export const CREATE_SOS_CODE_SUCCESS = 'CREATE_SOS_CODE_SUCCESS';
export const CREATE_SOS_CODE_FAILURE = 'CREATE_SOS_CODE_FAILURE';

export const FETCH_ALL_SOS_CODES_REQUEST = 'FETCH_ALL_SOS_CODES_REQUEST';
export const FETCH_ALL_SOS_CODES_SUCCESS = 'FETCH_ALL_SOS_CODES_SUCCESS';
export const FETCH_ALL_SOS_CODES_FAILURE = 'FETCH_ALL_SOS_CODES_FAILURE';
