export const SA_FETCH_PIN_OPTION_MANUFACTURERS_REQUEST =
    'SA_FETCH_PIN_OPTION_MANUFACTURERS_REQUEST';
export const SA_FETCH_PIN_OPTION_MANUFACTURERS_SUCCESS =
    'SA_FETCH_PIN_OPTION_MANUFACTURERS_SUCCESS';
export const SA_FETCH_PIN_OPTION_MANUFACTURERS_FAILURE =
    'SA_FETCH_PIN_OPTION_MANUFACTURERS_FAILURE';

export const SA_FETCH_SINGLE_MANUFACTURER_REQUEST = 'SA_FETCH_SINGLE_MANUFACTURER_REQUEST';
export const SA_FETCH_SINGLE_MANUFACTURER_SUCCESS = 'SA_FETCH_SINGLE_MANUFACTURER_SUCCESS';
export const SA_FETCH_SINGLE_MANUFACTURER_FAILURE = 'SA_FETCH_SINGLE_MANUFACTURER_FAILURE';

export const SA_CREATE_MANUFACTURER_REQUEST = 'SA_CREATE_MANUFACTURER_REQUEST';
export const SA_CREATE_MANUFACTURER_SUCCESS = 'SA_CREATE_MANUFACTURER_SUCCESS';
export const SA_CREATE_MANUFACTURER_FAILURE = 'SA_CREATE_MANUFACTURER_FAILURE';

export const SA_EDIT_MANUFACTURER_REQUEST = 'SA_EDIT_MANUFACTURER_REQUEST';
export const SA_EDIT_MANUFACTURER_SUCCESS = 'SA_EDIT_MANUFACTURER_SUCCESS';
export const SA_EDIT_MANUFACTURER_FAILURE = 'SA_EDIT_MANUFACTURER_FAILURE';

export const SA_FETCH_OPTION_VALUES_BY_MANUFACTURER_REQUEST =
    'SA_FETCH_OPTION_VALUES_BY_MANUFACTURER_REQUEST';
export const SA_FETCH_OPTION_VALUES_BY_MANUFACTURER_SUCCESS =
    'SA_FETCH_OPTION_VALUES_BY_MANUFACTURER_SUCCESS';
export const SA_FETCH_OPTION_VALUES_BY_MANUFACTURER_FAILURE =
    'SA_FETCH_OPTION_VALUES_BY_MANUFACTURER_FAILURE';
