// export const CREATE_NEW_FEATURE_REQUEST = 'CREATE_NEW_FEATURE_REQUEST';
// export const CREATE_NEW_FEATURE_SUCCESS = 'CREATE_NEW_FEATURE_SUCCESS';
// export const CREATE_NEW_FEATURE_FAILURE = 'CREATE_NEW_FEATURE_FAILURE';

export const FETCH_ALL_NEW_FEATURES_REQUEST = 'FETCH_ALL_NEW_FEATURES_REQUEST';
export const FETCH_ALL_NEW_FEATURES_SUCCESS = 'FETCH_ALL_NEW_FEATURES_SUCCESS';
export const FETCH_ALL_NEW_FEATURES_FAILURE = 'FETCH_ALL_NEW_FEATURES_FAILURE';
