export const FETCH_ALL_BANNER_NOTIFICATIONS_REQUEST = 'FETCH_ALL_BANNER_NOTIFICATIONS_REQUEST';
export const FETCH_ALL_BANNER_NOTIFICATIONS_SUCCESS = 'FETCH_ALL_BANNER_NOTIFICATIONS_SUCCESS';
export const FETCH_ALL_BANNER_NOTIFICATIONS_FAILURE = 'FETCH_ALL_BANNER_NOTIFICATIONS_FAILURE';

export const EDIT_BANNER_NOTIFICATION_REQUEST = 'EDIT_BANNER_NOTIFICATION_REQUEST';
export const EDIT_BANNER_NOTIFICATION_SUCCESS = 'EDIT_BANNER_NOTIFICATION_SUCCESS';
export const EDIT_BANNER_NOTIFICATION_FAILURE = 'EDIT_BANNER_NOTIFICATION_FAILURE';

export const ADD_BANNER_NOTIFICATION_REQUEST = 'ADD_BANNER_NOTIFICATION_REQUEST';
export const ADD_BANNER_NOTIFICATION_SUCCESS = 'ADD_BANNER_NOTIFICATION_SUCCESS';
export const ADD_BANNER_NOTIFICATION_FAILURE = 'ADD_BANNER_NOTIFICATION_FAILURE';

export const DELETE_BANNER_NOTIFICATION_REQUEST = 'DELETE_BANNER_NOTIFICATION_REQUEST';
export const DELETE_BANNER_NOTIFICATION_SUCCESS = 'DELETE_BANNER_NOTIFICATION_SUCCESS';
export const DELETE_BANNER_NOTIFICATION_FAILURE = 'DELETE_BANNER_NOTIFICATION_FAILURE';
