export const SA_FETCH_PIN_OPTION_MANUFACTURERS_REQUEST =
    'SA_FETCH_PIN_OPTION_MANUFACTURERS_REQUEST';
export const SA_FETCH_PIN_OPTION_MANUFACTURERS_SUCCESS =
    'SA_FETCH_PIN_OPTION_MANUFACTURERS_SUCCESS';
export const SA_FETCH_PIN_OPTION_MANUFACTURERS_FAILURE =
    'SA_FETCH_PIN_OPTION_MANUFACTURERS_FAILURE';
