export const ADD_NEW_FEATURE_REQUEST = 'ADD_NEW_FEATURE_REQUEST';
export const ADD_NEW_FEATURE_SUCCESS = 'ADD_NEW_FEATURE_SUCCESS';
export const ADD_NEW_FEATURE_FAILURE = 'ADD_NEW_FEATURE_FAILURE';

export const FETCH_ALL_NEW_FEATURES_REQUEST = 'FETCH_ALL_NEW_FEATURES_REQUEST';
export const FETCH_ALL_NEW_FEATURES_SUCCESS = 'FETCH_ALL_NEW_FEATURES_SUCCESS';
export const FETCH_ALL_NEW_FEATURES_FAILURE = 'FETCH_ALL_NEW_FEATURES_FAILURE';

export const FETCH_SINGLE_FEATURE_REQUEST = 'FETCH_SINGLE_FEATURE_REQUEST';
export const FETCH_SINGLE_FEATURE_SUCCESS = 'FETCH_SINGLE_FEATURE_SUCCESS';
export const FETCH_SINGLE_FEATURE_FAILURE = 'FETCH_SINGLE_FEATURE_FAILURE';
