export const SA_FETCH_ALL_INVOICES_REQUEST = 'SA_FETCH_ALL_INVOICES_REQUEST';
export const SA_FETCH_ALL_INVOICES_SUCCESS = 'SA_FETCH_ALL_INVOICES_SUCCESS';
export const SA_FETCH_ALL_INVOICES_FAILURE = 'SA_FETCH_ALL_INVOICES_FAILURE';
