export const SA_FETCH_COMPANY_SUBSCRIPTION_REQUEST =
    'SA_FETCH_COMPANY_SUBSCRIPTION_REQUEST';
export const SA_FETCH_COMPANY_SUBSCRIPTION_SUCCESS =
    'SA_FETCH_COMPANY_SUBSCRIPTION_SUCCESS';
export const SA_FETCH_COMPANY_SUBSCRIPTION_FAILURE =
    'SA_FETCH_COMPANY_SUBSCRIPTION_FAILURE';
