export const SA_FETCH_ALL_INVOICES_REQUEST = 'SA_FETCH_ALL_INVOICES_REQUEST';
export const SA_FETCH_ALL_INVOICES_SUCCESS = 'SA_FETCH_ALL_INVOICES_SUCCESS';
export const SA_FETCH_ALL_INVOICES_FAILURE = 'SA_FETCH_ALL_INVOICES_FAILURE';

export const SA_FETCH_INVOICES_BY_PAGE_REQUEST = 'SA_FETCH_INVOICES_BY_PAGE_REQUEST';
export const SA_FETCH_INVOICES_BY_PAGE_SUCCESS = 'SA_FETCH_INVOICES_BY_PAGE_SUCCESS';
export const SA_FETCH_INVOICES_BY_PAGE_FAILURE = 'SA_FETCH_INVOICES_BY_PAGE_FAILURE';

export const SA_FETCH_INVOICES_COUNT_REQUEST = 'SA_FETCH_INVOICES_COUNT_REQUEST';
export const SA_FETCH_INVOICES_COUNT_SUCCESS = 'SA_FETCH_INVOICES_COUNT_SUCCESS';
export const SA_FETCH_INVOICES_COUNT_FAILURE = 'SA_FETCH_INVOICES_COUNT_FAILURE';

export const ADMIN_FETCH_COMPANY_INVOICE_ITEMS_REQUEST =
    'ADMIN_FETCH_COMPANY_INVOICE_ITEMS_REQUEST';
export const ADMIN_FETCH_COMPANY_INVOICE_ITEMS_SUCCESS =
    'ADMIN_FETCH_COMPANY_INVOICE_ITEMS_SUCCESS';
export const ADMIN_FETCH_COMPANY_INVOICE_ITEMS_FAILURE =
    'ADMIN_FETCH_COMPANY_INVOICE_ITEMS_FAILURE';

export const ADMIN_FETCH_COMPANY_INVOICES_REQUEST = 'ADMIN_FETCH_COMPANY_INVOICES_REQUEST';
export const ADMIN_FETCH_COMPANY_INVOICES_SUCCESS = 'ADMIN_FETCH_COMPANY_INVOICES_SUCCESS';
export const ADMIN_FETCH_COMPANY_INVOICES_FAILURE = 'ADMIN_FETCH_COMPANY_INVOICES_FAILURE';

export const SA_RECORD_INVOICE_PAYMENT_REQUEST = 'SA_RECORD_INVOICE_PAYMENT_REQUEST';
export const SA_RECORD_INVOICE_PAYMENT_SUCCESS = 'SA_RECORD_INVOICE_PAYMENT_SUCCESS';
export const SA_RECORD_INVOICE_PAYMENT_FAILURE = 'SA_RECORD_INVOICE_PAYMENT_FAILURE';

export const SA_FETCH_PAYMENTS_BY_INVOICE_REQUEST = 'SA_FETCH_PAYMENTS_BY_INVOICE_REQUEST';
export const SA_FETCH_PAYMENTS_BY_INVOICE_SUCCESS = 'SA_FETCH_PAYMENTS_BY_INVOICE_SUCCESS';
export const SA_FETCH_PAYMENTS_BY_INVOICE_FAILURE = 'SA_FETCH_PAYMENTS_BY_INVOICE_FAILURE';

export const SA_EDIT_INVOICE_PAYMENT_REQUEST = 'SA_EDIT_INVOICE_PAYMENT_REQUEST';
export const SA_EDIT_INVOICE_PAYMENT_SUCCESS = 'SA_EDIT_INVOICE_PAYMENT_SUCCESS';
export const SA_EDIT_INVOICE_PAYMENT_FAILURE = 'SA_EDIT_INVOICE_PAYMENT_FAILURE';

export const SA_DELETE_INVOICE_PAYMENT_REQUEST = 'SA_DELETE_INVOICE_PAYMENT_REQUEST';
export const SA_DELETE_INVOICE_PAYMENT_SUCCESS = 'SA_DELETE_INVOICE_PAYMENT_SUCCESS';
export const SA_DELETE_INVOICE_PAYMENT_FAILURE = 'SA_DELETE_INVOICE_PAYMENT_FAILURE';

export const SA_DELETE_INVOICE_REQUEST = 'SA_DELETE_INVOICE_REQUEST';
export const SA_DELETE_INVOICE_SUCCESS = 'SA_DELETE_INVOICE_SUCCESS';
export const SA_DELETE_INVOICE_FAILURE = 'SA_DELETE_INVOICE_FAILURE';

export const SA_MAKE_INVOICE_FREE_REQUEST = 'SA_MAKE_INVOICE_FREE_REQUEST';
export const SA_MAKE_INVOICE_FREE_SUCCESS = 'SA_MAKE_INVOICE_FREE_SUCCESS';
export const SA_MAKE_INVOICE_FREE_FAILURE = 'SA_MAKE_INVOICE_FREE_FAILURE';

export const SA_SET_IS_INVOICE_PAID_REQUEST = 'SA_SET_IS_INVOICE_PAID_REQUEST';
export const SA_SET_IS_INVOICE_PAID_SUCCESS = 'SA_SET_IS_INVOICE_PAID_SUCCESS';
export const SA_SET_IS_INVOICE_PAID_FAILURE = 'SA_SET_IS_INVOICE_PAID_FAILURE';

export const UPDATE_INVOICE_FILTERS = 'UPDATE_INVOICE_FILTERS';
