export const FETCH_ALL_TEMPLATES_REQUEST = 'FETCH_ALL_TEMPLATES_REQUEST';
export const FETCH_ALL_TEMPLATES_SUCCESS = 'FETCH_ALL_TEMPLATES_SUCCESS';
export const FETCH_ALL_TEMPLATES_FAILURE = 'FETCH_ALL_TEMPLATES_FAILURE';

export const SELECT_QUESTION = 'SELECT_QUESTION';

export const EDIT_TEMPLATE_QUESTION_REQUEST = 'EDIT_TEMPLATE_QUESTION_REQUEST';
export const EDIT_TEMPLATE_QUESTION_SUCCESS = 'EDIT_TEMPLATE_QUESTION_SUCCESS';
export const EDIT_TEMPLATE_QUESTION_FAILURE = 'EDIT_TEMPLATE_QUESTION_FAILURE';
