export const POST_TEMPLATE_REQUEST = 'POST_TEMPLATE_REQUEST';
export const POST_TEMPLATE_SUCCESS = 'POST_TEMPLATE_SUCCESS';
export const POST_TEMPLATE_FAILURE = 'POST_TEMPLATE_FAILURE';

export const FETCH_TEMPLATES_REQUEST = 'FETCH_TEMPLATES_REQUEST';
export const FETCH_TEMPLATES_SUCCESS = 'FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAILURE = 'FETCH_TEMPLATES_FAILURE';

export const FETCH_TEMPLATES_SIMPLE_REQUEST = 'FETCH_TEMPLATES_SIMPLE_REQUEST';
export const FETCH_TEMPLATES_SIMPLE_SUCCESS = 'FETCH_TEMPLATES_SIMPLE_SUCCESS';
export const FETCH_TEMPLATES_SIMPLE_FAILURE = 'FETCH_TEMPLATES_SIMPLE_FAILURE';

export const FETCH_TEMPLATE_REQUEST = 'FETCH_TEMPLATE_REQUEST';
export const FETCH_TEMPLATE_SUCCESS = 'FETCH_TEMPLATE_SUCCESS';
export const FETCH_TEMPLATE_FAILURE = 'FETCH_TEMPLATE_FAILURE';

export const DELETE_TEMPLATE_REQUEST = 'DELETE_TEMPLATE_REQUEST';
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_FAILURE = 'DELETE_TEMPLATE_FAILURE';
export const DELETE_TEMPLATE_UNAVAILABLE = 'DELETE_TEMPLATE_UNAVAILABLE';

export const RESET_QUESTION_FIELDS = 'RESET_QUESTION_FIELDS';
export const UPDATE_QUESTION_FIELD = 'UPDATE_QUESTION_FIELD';
export const UPDATE_QUESTION_FIELDS = 'UPDATE_QUESTION_FIELDS';
export const SET_TEMPLATE = 'SET_TEMPLATE';
export const SET_LABEL_FIELDS = 'SET_LABEL_FIELDS';
export const SET_SECTION = 'SET_SECTION';
export const SET_QUESTION = 'SET_QUESTION';
export const CHANGE_QUESTION_SECTION = 'CHANGE_QUESTION_SECTION';
export const SWAP_QUESTION_SORTS = 'SWAP_QUESTION_SORTS';
export const DELETE_SECTION = 'DELETE_SECTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const RESET_SAVE_REQUIRED = 'RESET_SAVE_REQUIRED';
