export const SET_TEMPLATE = 'SET_TEMPLATE';
export const SET_SECTION = 'SET_SECTION';
export const SET_QUESTION = 'SET_QUESTION';
export const CHANGE_QUESTION_SECTION = 'CHANGE_QUESTION_SECTION';
export const SWAP_QUESTION_SORTS = 'SWAP_QUESTION_SORTS';
export const DELETE_SECTION = 'DELETE_SECTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const RESET_SAVE_REQUIRED = 'RESET_SAVE_REQUIRED';
