export const FETCH_ALL_TEMPLATES_REQUEST = 'FETCH_ALL_TEMPLATES_REQUEST';
export const FETCH_ALL_TEMPLATES_SUCCESS = 'FETCH_ALL_TEMPLATES_SUCCESS';
export const FETCH_ALL_TEMPLATES_FAILURE = 'FETCH_ALL_TEMPLATES_FAILURE';

export const SELECT_QUESTION = 'SELECT_QUESTION';
