export const FETCH_TIMEZONES_REQUEST = 'FETCH_TIMEZONES_REQUEST';
export const FETCH_TIMEZONES_FAILURE = 'FETCH_TIMEZONES_FAILURE';
export const FETCH_TIMEZONES_SUCCESS = 'FETCH_TIMEZONES_SUCCESS';

export const FETCH_DATE_FORMATS_REQUEST = 'FETCH_DATE_FORMATS_REQUEST';
export const FETCH_DATE_FORMATS_FAILURE = 'FETCH_DATE_FORMATS_FAILURE';
export const FETCH_DATE_FORMATS_SUCCESS = 'FETCH_DATE_FORMATS_SUCCESS';
