export const FETCH_TIMESHEET_WEEK_REQUEST = 'FETCH_TIMESHEET_WEEK_REQUEST';
export const FETCH_TIMESHEET_WEEK_FAILURE = 'FETCH_TIMESHEET_WEEK_FAILURE';
export const FETCH_TIMESHEET_WEEK_SUCCESS = 'FETCH_TIMESHEET_WEEK_SUCCESS';

export const FETCH_TIMESHEET_DAY_REQUEST = 'FETCH_TIMESHEET_DAY_REQUEST';
export const FETCH_TIMESHEET_DAY_FAILURE = 'FETCH_TIMESHEET_DAY_FAILURE';
export const FETCH_TIMESHEET_DAY_SUCCESS = 'FETCH_TIMESHEET_DAY_SUCCESS';

export const SET_SELECTED_COMPANY_ID = 'SET_SELECTED_COMPANY_ID';

export const TOGGLE_FILTER_BY_HAS_CLOCKED_IN = 'TOGGLE_FILTER_BY_HAS_CLOCKED_IN';
