export const FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_REQUEST =
    'FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_REQUEST';
export const FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_FAILURE =
    'FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_FAILURE';
export const FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_SUCCESS =
    'FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_SUCCESS';

export const FETCH_TIMESHEET_WEEK_REQUEST = 'FETCH_TIMESHEET_WEEK_REQUEST';
export const FETCH_TIMESHEET_WEEK_FAILURE = 'FETCH_TIMESHEET_WEEK_FAILURE';
export const FETCH_TIMESHEET_WEEK_SUCCESS = 'FETCH_TIMESHEET_WEEK_SUCCESS';

export const SET_SELECTED_COMPANY_ID = 'SET_SELECTED_COMPANY_ID';

export const TOGGLE_FILTER_BY_HAS_CLOCKED_IN = 'TOGGLE_FILTER_BY_HAS_CLOCKED_IN';

export const POST_OVERRIDE_SHIFT_REQUEST = 'POST_OVERRIDE_SHIFT_REQUEST';
export const POST_OVERRIDE_SHIFT_FAILURE = 'POST_OVERRIDE_SHIFT_FAILURE';
export const POST_OVERRIDE_SHIFT_SUCCESS = 'POST_OVERRIDE_SHIFT_SUCCESS';
