export const FETCH_TIMESHEET_PIN_STATS_REQUEST = 'FETCH_TIMESHEET_PIN_STATS_REQUEST';
export const FETCH_TIMESHEET_PIN_STATS_SUCCESS = 'FETCH_TIMESHEET_PIN_STATS_SUCCESS';
export const FETCH_TIMESHEET_PIN_STATS_FAILURE = 'FETCH_TIMESHEET_PIN_STATS_FAILURE';
