export const FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_REQUEST =
    'FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_REQUEST';
export const FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_FAILURE =
    'FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_FAILURE';
export const FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_SUCCESS =
    'FETCH_TIMESHEET_WEEK_PIN_OPTION_TYPES_SUCCESS';

export const FETCH_TIMESHEET_WEEK_REQUEST = 'FETCH_TIMESHEET_WEEK_REQUEST';
export const FETCH_TIMESHEET_WEEK_FAILURE = 'FETCH_TIMESHEET_WEEK_FAILURE';
export const FETCH_TIMESHEET_WEEK_SUCCESS = 'FETCH_TIMESHEET_WEEK_SUCCESS';

export const SET_SELECTED_COMPANY_ID = 'SET_SELECTED_COMPANY_ID';
export const SET_SELECTED_JOB_REFERENCE_ID = 'SET_SELECTED_JOB_REFERENCE_ID';

export const TOGGLE_FILTER_BY_HAS_CLOCKED_IN = 'TOGGLE_FILTER_BY_HAS_CLOCKED_IN';

export const POST_OVERRIDE_SHIFT_REQUEST = 'POST_OVERRIDE_SHIFT_REQUEST';
export const POST_OVERRIDE_SHIFT_FAILURE = 'POST_OVERRIDE_SHIFT_FAILURE';
export const POST_OVERRIDE_SHIFT_SUCCESS = 'POST_OVERRIDE_SHIFT_SUCCESS';

export const POST_REJECT_SHIFT_REQUEST = 'POST_REJECT_SHIFT_REQUEST';
export const POST_REJECT_SHIFT_FAILURE = 'POST_REJECT_SHIFT_FAILURE';
export const POST_REJECT_SHIFT_SUCCESS = 'POST_REJECT_SHIFT_SUCCESS';

export const POST_APPROVE_SHIFT_REQUEST = 'POST_APPROVE_SHIFT_REQUEST';
export const POST_APPROVE_SHIFT_FAILURE = 'POST_APPROVE_SHIFT_FAILURE';
export const POST_APPROVE_SHIFT_SUCCESS = 'POST_APPROVE_SHIFT_SUCCESS';

export const DELETE_SHIFT_REQUEST = 'DELETE_SHIFT_REQUEST';
export const DELETE_SHIFT_FAILURE = 'DELETE_SHIFT_FAILURE';
export const DELETE_SHIFT_SUCCESS = 'DELETE_SHIFT_SUCCESS';

export const PATCH_CLOCKER_ENTRY_REQUEST = 'PATCH_CLOCKER_ENTRY_REQUEST';
export const PATCH_CLOCKER_ENTRY_FAILURE = 'PATCH_CLOCKER_ENTRY_FAILURE';
export const PATCH_CLOCKER_ENTRY_SUCCESS = 'PATCH_CLOCKER_ENTRY_SUCCESS';

export const POST_GENERATE_TIMESHEETS_CSV_REQUEST = 'POST_GENERATE_TIMESHEETS_CSV_REQUEST';
export const POST_GENERATE_TIMESHEETS_CSV_FAILURE = 'POST_GENERATE_TIMESHEETS_CSV_FAILURE';
export const POST_GENERATE_TIMESHEETS_CSV_SUCCESS = 'POST_GENERATE_TIMESHEETS_CSV_SUCCESS';

export const POST_ADD_EXPENSE_TO_SHIFT_REQUEST = 'POST_ADD_EXPENSE_TO_SHIFT_REQUEST';
export const POST_ADD_EXPENSE_TO_SHIFT_FAILURE = 'POST_ADD_EXPENSE_TO_SHIFT_FAILURE';
export const POST_ADD_EXPENSE_TO_SHIFT_SUCCESS = 'POST_ADD_EXPENSE_TO_SHIFT_SUCCESS';

export const DELETE_EXPENSE_FROM_SHIFT_REQUEST = 'DELETE_EXPENSE_FROM_SHIFT_REQUEST';
export const DELETE_EXPENSE_FROM_SHIFT_FAILURE = 'DELETE_EXPENSE_FROM_SHIFT_FAILURE';
export const DELETE_EXPENSE_FROM_SHIFT_SUCCESS = 'DELETE_EXPENSE_FROM_SHIFT_SUCCESS';
