export const FETCH_INCOMING_TRANSFER_REQUESTS_REQUEST =
    'FETCH_INCOMING_TRANSFER_REQUESTS_REQUEST';
export const FETCH_INCOMING_TRANSFER_REQUESTS_SUCCESS =
    'FETCH_INCOMING_TRANSFER_REQUESTS_SUCCESS';
export const FETCH_INCOMING_TRANSFER_REQUESTS_FAILURE =
    'FETCH_INCOMING_TRANSFER_REQUESTS_FAILURE';

export const FETCH_OUTGOING_TRANSFER_REQUESTS_REQUEST =
    'FETCH_OUTGOING_TRANSFER_REQUESTS_REQUEST';
export const FETCH_OUTGOING_TRANSFER_REQUESTS_SUCCESS =
    'FETCH_OUTGOING_TRANSFER_REQUESTS_SUCCESS';
export const FETCH_OUTGOING_TRANSFER_REQUESTS_FAILURE =
    'FETCH_OUTGOING_TRANSFER_REQUESTS_FAILURE';
