export const FETCH_INCOMING_TRANSFER_REQUESTS_REQUEST =
    'FETCH_INCOMING_TRANSFER_REQUESTS_REQUEST';
export const FETCH_INCOMING_TRANSFER_REQUESTS_SUCCESS =
    'FETCH_INCOMING_TRANSFER_REQUESTS_SUCCESS';
export const FETCH_INCOMING_TRANSFER_REQUESTS_FAILURE =
    'FETCH_INCOMING_TRANSFER_REQUESTS_FAILURE';

export const FETCH_OUTGOING_TRANSFER_REQUESTS_REQUEST =
    'FETCH_OUTGOING_TRANSFER_REQUESTS_REQUEST';
export const FETCH_OUTGOING_TRANSFER_REQUESTS_SUCCESS =
    'FETCH_OUTGOING_TRANSFER_REQUESTS_SUCCESS';
export const FETCH_OUTGOING_TRANSFER_REQUESTS_FAILURE =
    'FETCH_OUTGOING_TRANSFER_REQUESTS_FAILURE';

export const RESPOND_TO_TRANSFER_REQUEST_REQUEST =
    'RESPOND_TO_TRANSFER_REQUEST_REQUEST';
export const RESPOND_TO_TRANSFER_REQUEST_SUCCESS =
    'RESPOND_TO_TRANSFER_REQUEST_SUCCESS';
export const RESPOND_TO_TRANSFER_REQUEST_FAILURE =
    'RESPOND_TO_TRANSFER_REQUEST_FAILURE';

export const DELETE_TRANSFER_REQUEST_REQUEST =
    'DELETE_TRANSFER_REQUEST_REQUEST';
export const DELETE_TRANSFER_REQUEST_FAILURE =
    'DELETE_TRANSFER_REQUEST_FAILURE';
export const DELETE_TRANSFER_REQUEST_SUCCESS =
    'DELETE_TRANSFER_REQUEST_SUCCESS';
