export const UPLOAD_USER_GUIDE_REQUEST = 'UPLOAD_USER_GUIDE_REQUEST';
export const UPLOAD_USER_GUIDE_SUCCESS = 'UPLOAD_USER_GUIDE_SUCCESS';
export const UPLOAD_USER_GUIDE_FAILURE = 'UPLOAD_USER_GUIDE_FAILURE';
