export const FETCH_USER_GUIDE_REQUEST = 'FETCH_USER_GUIDE_REQUEST';
export const FETCH_USER_GUIDE_SUCCESS = 'FETCH_USER_GUIDE_SUCCESS';
export const FETCH_USER_GUIDE_FAILURE = 'FETCH_USER_GUIDE_FAILURE';

export const ADMIN_UPLOAD_USER_GUIDE_REQUEST = 'ADMIN_UPLOAD_USER_GUIDE_REQUEST';
export const ADMIN_UPLOAD_USER_GUIDE_SUCCESS = 'ADMIN_UPLOAD_USER_GUIDE_SUCCESS';
export const ADMIN_UPLOAD_USER_GUIDE_FAILURE = 'ADMIN_UPLOAD_USER_GUIDE_FAILURE';

export const ADMIN_FETCH_USER_GUIDE_REQUEST = 'ADMIN_FETCH_USER_GUIDE_REQUEST';
export const ADMIN_FETCH_USER_GUIDE_SUCCESS = 'ADMIN_FETCH_USER_GUIDE_SUCCESS';
export const ADMIN_FETCH_USER_GUIDE_FAILURE = 'ADMIN_FETCH_USER_GUIDE_FAILURE';
export const ADMIN_FETCH_ALL_USER_GUIDE_VERSIONS_SUCCESS =
    'ADMIN_FETCH_ALL_USER_GUIDE_VERSIONS_SUCCESS';
export const ADMIN_FETCH_ALL_USER_GUIDE_VERSIONS_REQUEST =
    'ADMIN_FETCH_ALL_USER_GUIDE_VERSIONS_REQUEST';
export const ADMIN_FETCH_ALL_USER_GUIDE_VERSIONS_FAILURE =
    'ADMIN_FETCH_ALL_USER_GUIDE_VERSIONS_FAILURE';
