export const FETCH_COMPANY_USERS_REQUEST = 'FETCH_COMPANY_USERS_REQUEST';
export const FETCH_COMPANY_USERS_SUCCESS = 'FETCH_COMPANY_USERS_SUCCESS';
export const FETCH_COMPANY_USERS_FAILURE = 'FETCH_COMPANY_USERS_FAILURE';

export const FETCH_CLIENT_USERS_REQUEST = 'FETCH_CLIENT_USERS_REQUEST';
export const FETCH_CLIENT_USERS_SUCCESS = 'FETCH_CLIENT_USERS_SUCCESS';
export const FETCH_CLIENT_USERS_FAILURE = 'FETCH_CLIENT_USERS_FAILURE';

export const FETCH_SINGLE_COMPANY_USER_REQUEST =
    'FETCH_SINGLE_COMPANY_USER_REQUEST';
export const FETCH_SINGLE_COMPANY_USER_SUCCESS =
    'FETCH_SINGLE_COMPANY_USER_SUCCESS';
export const FETCH_SINGLE_COMPANY_USER_FAILURE =
    'FETCH_SINGLE_COMPANY_USER_FAILURE';

export const CREATE_COMPANY_USER_REQUEST = 'CREATE_COMPANY_USER_REQUEST';
export const CREATE_COMPANY_USER_SUCCESS = 'CREATE_COMPANY_USER_SUCCESS';
export const CREATE_COMPANY_USER_FAILURE = 'CREATE_COMPANY_USER_FAILURE';

export const ADMIN_CREATE_COMPANY_USER_REQUEST =
    'ADMIN_CREATE_COMPANY_USER_REQUEST';
export const ADMIN_CREATE_COMPANY_USER_SUCCESS =
    'ADMIN_CREATE_COMPANY_USER_SUCCESS';
export const ADMIN_CREATE_COMPANY_USER_FAILURE =
    'ADMIN_CREATE_COMPANY_USER_FAILURE';

export const EDIT_COMPANY_USER_REQUEST = 'EDIT_COMPANY_USER_REQUEST';
export const EDIT_COMPANY_USER_SUCCESS = 'EDIT_COMPANY_USER_SUCCESS';
export const EDIT_COMPANY_USER_FAILURE = 'EDIT_COMPANY_USER_FAILURE';

export const EDIT_COMPANY_USER_PASSWORD_REQUEST =
    'EDIT_COMPANY_USER_PASSWORD_REQUEST';
export const EDIT_COMPANY_USER_PASSWORD_SUCCESS =
    'EDIT_COMPANY_USER_PASSWORD_SUCCESS';
export const EDIT_COMPANY_USER_PASSWORD_FAILURE =
    'EDIT_COMPANY_USER_PASSWORD_FAILURE';

export const EDIT_COMPANY_USER_TYPE_REQUEST = 'EDIT_COMPANY_USER_TYPE_REQUEST';
export const EDIT_COMPANY_USER_TYPE_SUCCESS = 'EDIT_COMPANY_USER_TYPE_SUCCESS';
export const EDIT_COMPANY_USER_TYPE_FAILURE = 'EDIT_COMPANY_USER_TYPE_FAILURE';

export const DELETE_COMPANY_USER_REQUEST = 'DELETE_COMPANY_USER_REQUEST';
export const DELETE_COMPANY_USER_SUCCESS = 'DELETE_COMPANY_USER_SUCCESS';
export const DELETE_COMPANY_USER_FAILURE = 'DELETE_COMPANY_USER_FAILURE';

export const UNLINK_OPERATIVE_DEVICE_REQUEST =
    'UNLINK_OPERATIVE_DEVICE_REQUEST';
export const UNLINK_OPERATIVE_DEVICE_FAILURE =
    'UNLINK_OPERATIVE_DEVICE_FAILURE';
export const UNLINK_OPERATIVE_DEVICE_SUCCESS =
    'UNLINK_OPERATIVE_DEVICE_SUCCESS';

export const CHANGE_USER_TYPE_REQUEST = 'CHANGE_USER_TYPE_REQUEST';
export const CHANGE_USER_TYPE_SUCCESS = 'CHANGE_USER_TYPE_SUCCESS';
export const CHANGE_USER_TYPE_FAILURE = 'CHANGE_USER_TYPE_FAILURE';
export const FETCH_USER_DRAWINGS_REQUEST = 'FETCH_USER_DRAWINGS_REQUEST';
export const FETCH_USER_DRAWINGS_SUCCESS = 'FETCH_USER_DRAWINGS_SUCCESS';
export const FETCH_USER_DRAWINGS_FAILURE = 'FETCH_USER_DRAWINGS_FAILURE';

export const REMOVE_USER_DRAWINGS_ACCESS_REQUEST =
    'REMOVE_USER_DRAWINGS_ACCESS_REQUEST';
export const REMOVE_USER_DRAWINGS_ACCESS_SUCCESS =
    'REMOVE_USER_DRAWINGS_ACCESS_SUCCESS';
export const REMOVE_USER_DRAWINGS_ACCESS_FAILURE =
    'REMOVE_USER_DRAWINGS_ACCESS_FAILURE';

export const TOGGLE_RESTRICT_USER_PAYMENTS_REQUEST =
    'TOGGLE_RESTRICT_USER_PAYMENTS_REQUEST';
export const TOGGLE_RESTRICT_USER_PAYMENTS_SUCCESS =
    'TOGGLE_RESTRICT_USER_PAYMENTS_SUCCESS';
export const TOGGLE_RESTRICT_USER_PAYMENTS_FAILURE =
    'TOGGLE_RESTRICT_USER_PAYMENTS_FAILURE';
