export const FETCH_ALL_USERS_REQUEST = 'FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE';

export const FETCH_USER_CREATIONS_REQUEST = 'FETCH_USER_CREATIONS_REQUEST';
export const FETCH_USER_CREATIONS_SUCCESS = 'FETCH_USER_CREATIONS_SUCCESS';
export const FETCH_USER_CREATIONS_FAILURE = 'FETCH_USER_CREATIONS_FAILURE';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const EDIT_USER_PASSWORD_REQUEST = 'EDIT_USER_PASSWORD_REQUEST';
export const EDIT_USER_PASSWORD_SUCCESS = 'EDIT_USER_PASSWORD_SUCCESS';
export const EDIT_USER_PASSWORD_FAILURE = 'EDIT_USER_PASSWORD_FAILURE';

export const ADMIN_EDIT_USER_EMAIL_REQUEST = 'EDIT_USER_EMAIL_REQUEST';
export const ADMIN_EDIT_USER_EMAIL_SUCCESS = 'EDIT_USER_EMAIL_SUCCESS';
export const ADMIN_EDIT_USER_EMAIL_FAILURE = 'EDIT_USER_EMAIL_FAILURE';
export const ADMIN_EDIT_USER_EMAIL_SHOW_MODAL = 'EDIT_USER_EMAIL_SHOW_MODAL';

export const UPDATE_USERS_FILTERS = 'UPDATE_USERS_FILTERS';

export const ADMIN_FETCH_COMPANY_USERS_REQUEST = 'ADMIN_FETCH_COMPANY_USERS_REQUEST';
export const ADMIN_FETCH_COMPANY_USERS_SUCCESS = 'ADMIN_FETCH_COMPANY_USERS_SUCCESS';
export const ADMIN_FETCH_COMPANY_USERS_FAILURE = 'ADMIN_FETCH_COMPANY_USERS_FAILURE';

export const ADMIN_FETCH_COMPANY_USERS_INFO_REQUEST = 'ADMIN_FETCH_COMPANY_USERS_INFO_REQUEST';
export const ADMIN_FETCH_COMPANY_USERS_INFO_SUCCESS = 'ADMIN_FETCH_COMPANY_USERS_INFO_SUCCESS';
export const ADMIN_FETCH_COMPANY_USERS_INFO_FAILURE = 'ADMIN_FETCH_COMPANY_USERS_INFO_FAILURE';

export const ADMIN_FETCH_USERS_BY_SEARCH_REQUEST = 'ADMIN_FETCH_USERS_BY_SEARCH_REQUEST';
export const ADMIN_FETCH_USERS_BY_SEARCH_SUCCESS = 'ADMIN_FETCH_USERS_BY_SEARCH_SUCCESS';
export const ADMIN_FETCH_USERS_BY_SEARCH_FAILURE = 'ADMIN_FETCH_USERS_BY_SEARCH_FAILURE';

export const FORCE_CONFIRM_USER_EMAIL_REQUEST = 'FORCE_CONFIRM_USER_EMAIL_REQUEST';
export const FORCE_CONFIRM_USER_EMAIL_SUCCESS = 'FORCE_CONFIRM_USER_EMAIL_SUCCESS';
export const FORCE_CONFIRM_USER_EMAIL_FAILURE = 'FORCE_CONFIRM_USER_EMAIL_FAILURE';

export const REMOVE_USER_LOCKOUT_REQUEST = 'REMOVE_USER_LOCKOUT_REQUEST';
export const REMOVE_USER_LOCKOUT_SUCCESS = 'REMOVE_USER_LOCKOUT_SUCCESS';
export const REMOVE_USER_LOCKOUT_FAILURE = 'REMOVE_USER_LOCKOUT_FAILURE';

export const FETCH_COMPANY_ADMIN_USERS_REQUEST = 'FETCH_COMPANY_ADMIN_USERS_REQUEST';
export const FETCH_COMPANY_ADMIN_USERS_SUCCESS = 'FETCH_COMPANY_ADMIN_USERS_SUCCESS';
export const FETCH_COMPANY_ADMIN_USERS_FAILURE = 'FETCH_COMPANY_ADMIN_USERS_FAILURE';
