export const FETCH_ALL_USERS_REQUEST = 'FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const EDIT_USER_PASSWORD_REQUEST = 'EDIT_USER_PASSWORD_REQUEST';
export const EDIT_USER_PASSWORD_SUCCESS = 'EDIT_USER_PASSWORD_SUCCESS';
export const EDIT_USER_PASSWORD_FAILURE = 'EDIT_USER_PASSWORD_FAILURE';

export const UPDATE_USERS_FILTERS = 'UPDATE_USERS_FILTERS';

export const ADMIN_FETCH_COMPANY_USERS_REQUEST =
    'ADMIN_FETCH_COMPANY_USERS_REQUEST';
export const ADMIN_FETCH_COMPANY_USERS_SUCCESS =
    'ADMIN_FETCH_COMPANY_USERS_SUCCESS';
export const ADMIN_FETCH_COMPANY_USERS_FAILURE =
    'ADMIN_FETCH_COMPANY_USERS_FAILURE';
