export const FETCH_COMPANY_USERS_REQUEST = 'FETCH_COMPANY_USERS_REQUEST';
export const FETCH_COMPANY_USERS_SUCCESS = 'FETCH_COMPANY_USERS_SUCCESS';
export const FETCH_COMPANY_USERS_FAILURE = 'FETCH_COMPANY_USERS_FAILURE';

export const FETCH_SINGLE_COMPANY_USER_REQUEST =
    'FETCH_SINGLE_COMPANY_USER_REQUEST';
export const FETCH_SINGLE_COMPANY_USER_SUCCESS =
    'FETCH_SINGLE_COMPANY_USER_SUCCESS';
export const FETCH_SINGLE_COMPANY_USER_FAILURE =
    'FETCH_SINGLE_COMPANY_USER_FAILURE';

export const CREATE_COMPANY_USER_REQUEST = 'CREATE_COMPANY_USER_REQUEST';
export const CREATE_COMPANY_USER_SUCCESS = 'CREATE_COMPANY_USER_SUCCESS';
export const CREATE_COMPANY_USER_FAILURE = 'CREATE_COMPANY_USER_FAILURE';

export const EDIT_COMPANY_USER_REQUEST = 'EDIT_COMPANY_USER_REQUEST';
export const EDIT_COMPANY_USER_SUCCESS = 'EDIT_COMPANY_USER_SUCCESS';
export const EDIT_COMPANY_USER_FAILURE = 'EDIT_COMPANY_USER_FAILURE';

export const EDIT_COMPANY_USER_PASSWORD_REQUEST =
    'EDIT_COMPANY_USER_PASSWORD_REQUEST';
export const EDIT_COMPANY_USER_PASSWORD_SUCCESS =
    'EDIT_COMPANY_USER_PASSWORD_SUCCESS';
export const EDIT_COMPANY_USER_PASSWORD_FAILURE =
    'EDIT_COMPANY_USER_PASSWORD_FAILURE';

export const DELETE_COMPANY_USER_REQUEST = 'DELETE_COMPANY_USER_REQUEST';
export const DELETE_COMPANY_USER_SUCCESS = 'DELETE_COMPANY_USER_SUCCESS';
export const DELETE_COMPANY_USER_FAILURE = 'DELETE_COMPANY_USER_FAILURE';
