export const FETCH_ALL_WORKING_HOURS_REQUEST = 'FETCH_ALL_WORKING_HOURS_REQUEST';
export const FETCH_ALL_WORKING_HOURS_FAILURE = 'FETCH_ALL_WORKING_HOURS_FAILURE';
export const FETCH_ALL_WORKING_HOURS_SUCCESS = 'FETCH_ALL_WORKING_HOURS_SUCCESS';
