export const SET_ZONE_ADD_MODE = 'SET_ZONE_ADD_MODE';
export const SET_ZONES_OPACITY = 'SET_ZONES_OPACITY';

export const CREATE_DRAWING_ZONE_REQUEST = 'CREATE_DRAWING_ZONE_REQUEST';
export const CREATE_DRAWING_ZONE_SUCCESS = 'CREATE_DRAWING_ZONE_SUCCESS';
export const CREATE_DRAWING_ZONE_FAILURE = 'CREATE_DRAWING_ZONE_FAILURE';

export const EDIT_DRAWING_ZONE_REQUEST = 'EDIT_DRAWING_ZONE_REQUEST';
export const EDIT_DRAWING_ZONE_SUCCESS = 'EDIT_DRAWING_ZONE_SUCCESS';
export const EDIT_DRAWING_ZONE_FAILURE = 'EDIT_DRAWING_ZONE_FAILURE';

export const FETCH_DRAWING_ZONES_REQUEST = 'FETCH_DRAWING_ZONES_REQUEST';
export const FETCH_DRAWING_ZONES_SUCCESS = 'FETCH_DRAWING_ZONES_SUCCESS';
export const FETCH_DRAWING_ZONES_FAILURE = 'FETCH_DRAWING_ZONES_FAILURE';

export const FETCH_DRAWING_ZONES_FOR_REPORT_REQUEST = 'FETCH_DRAWING_ZONES_FOR_REPORT_REQUEST';
export const FETCH_DRAWING_ZONES_FOR_REPORT_SUCCESS = 'FETCH_DRAWING_ZONES_FOR_REPORT_SUCCESS';
export const FETCH_DRAWING_ZONES_FOR_REPORT_FAILURE = 'FETCH_DRAWING_ZONES_FOR_REPORT_FAILURE';

export const DELETE_DRAWING_ZONE_REQUEST = 'DELETE_DRAWING_ZONE_REQUEST';
export const DELETE_DRAWING_ZONE_SUCCESS = 'DELETE_DRAWING_ZONE_SUCCESS';
export const DELETE_DRAWING_ZONE_FAILURE = 'DELETE_DRAWING_ZONE_FAILURE';

export const SET_ZONE_FORM_COORDINATES = 'SET_ZONE_FORM_COORDINATES';
