export const SET_ZONE_ADD_MODE = 'SET_ZONE_ADD_MODE';
export const SET_ZONES_OPACITY = 'SET_ZONES_OPACITY';

export const CREATE_DRAWING_ZONE_REQUEST = 'CREATE_DRAWING_ZONE_REQUEST';
export const CREATE_DRAWING_ZONE_SUCCESS = 'CREATE_DRAWING_ZONE_SUCCESS';
export const CREATE_DRAWING_ZONE_FAILURE = 'CREATE_DRAWING_ZONE_FAILURE';

export const SET_ZONE_FORM_FIELD = 'SET_ZONE_FORM_FIELD';
